// Authored Regents problem-bank — Exponential Functions: reading the parts of an
// exponential model y = a·b^t (AI-F.LE.5). The recurring skills: the initial
// value is a (the value at t = 0); the base b is the growth/decay FACTOR, and the
// percent rate is r where b = 1 + r (growth) or b = 1 − r (decay) — so 0.75 is a
// 25% decay, not 75%. Complements "Linear vs. Exponential" (which only asks WHICH
// model fits); here you work WITH the model. Real released Algebra I Regents
// questions mined from the official NYSED administrations (via JMAP), cited to the
// exam + question number. Every answer independently re-derived; SME-ratified.

import type { RegentsItem } from "@/lib/regents/bank";

const bank: RegentsItem[] = [
  // ——— The initial value a (the value at t = 0) ———
  {
    id: "exp-mc-0126-q08",
    mode: "mc",
    standard: "AI-F.LE.5",
    topic: "Exponential models — initial value",
    examCitation: "regents-algI-0126-q08",
    part: "I",
    credits: 2,
    prompt: String.raw`The value of a diamond ring, in dollars, $t$ years after it is purchased is modeled by $v(t) = 500(1.08)^t$. What was the original price of the ring, in dollars?`,
    choices: [String.raw`\$108`, String.raw`\$460`, String.raw`\$500`, String.raw`\$540`],
    answer: 2,
    explanation: String.raw`The original price is the value at $t = 0$: $v(0) = 500(1.08)^0 = 500(1) = 500$. The coefficient $a$ is the initial value.`,
  },
  {
    id: "exp-mc-0115-q15",
    mode: "mc",
    standard: "AI-F.LE.5",
    topic: "Exponential models — the y-intercept in context",
    examCitation: "regents-algI-0115-q15",
    part: "I",
    credits: 2,
    prompt: String.raw`A bank charges a fee on accounts left inactive. The value $y$ of one account left inactive for $x$ years is $y = 5000(0.98)^x$. What is the $y$-intercept of this equation, and what does it represent?`,
    choices: [
      String.raw`$0.98$, the percent of money in the account initially`,
      String.raw`$0.98$, the percent of money in the account after $x$ years`,
      String.raw`$5000$, the amount of money in the account initially`,
      String.raw`$5000$, the amount of money in the account after $x$ years`,
    ],
    answer: 2,
    explanation: String.raw`The $y$-intercept is the value at $x = 0$: $y = 5000(0.98)^0 = 5000$. That is the amount in the account at the start — initially.`,
  },
  {
    id: "exp-mc-0120-q14",
    mode: "mc",
    standard: "AI-F.LE.5",
    topic: "Exponential models — which statement is true",
    examCitation: "regents-algI-0120-q14",
    part: "I",
    credits: 2,
    prompt: String.raw`The equation $V(t) = 12{,}000(0.75)^t$ represents the value of a motorcycle $t$ years after it was purchased. Which statement is true?`,
    choices: [
      String.raw`The motorcycle cost \$9000 when purchased.`,
      String.raw`The motorcycle cost \$12,000 when purchased.`,
      String.raw`The motorcycle's value is decreasing at a rate of $75\%$ each year.`,
      String.raw`The motorcycle's value is decreasing at a rate of $0.25\%$ each year.`,
    ],
    answer: 1,
    explanation: String.raw`The purchase price is $V(0) = 12{,}000$. The base $0.75 = 1 - 0.25$, so the value decreases $25\%$ per year (not $75\%$) — making choice 2 the true statement.`,
  },

  // ——— The exponent is the number of time periods ———
  {
    id: "exp-mc-0623-q08",
    mode: "mc",
    standard: "AI-F.LE.5",
    topic: "Exponential models — meaning of the exponent",
    examCitation: "regents-algI-0623-q08",
    part: "I",
    credits: 2,
    prompt: String.raw`Mike models bacteria growth with $b = 1300(2.65)^x$. The exponent represents`,
    choices: [
      "the total number of bacteria currently present",
      "the percent at which the bacteria are growing",
      "the initial amount of bacteria",
      "the number of time periods",
    ],
    answer: 3,
    explanation: String.raw`In $a \cdot b^x$, the exponent $x$ counts how many times the quantity is multiplied by the factor $b$ — the number of time periods. (Here $1300$ is the initial amount and $2.65$ is the growth factor.)`,
  },

  // ——— Growth rate from the base: b = 1 + r ———
  {
    id: "exp-mc-0626-q20",
    mode: "mc",
    standard: "AI-F.LE.5",
    topic: "Exponential models — growth rate from the base",
    examCitation: "regents-algI-0626-q20",
    part: "I",
    credits: 2,
    prompt: String.raw`The value of a home is modeled by $V(t) = 96{,}949(1.0448)^t$, where $t$ is years. What is the percent increase in the home's value each year?`,
    choices: [String.raw`$1.0448\%$`, String.raw`$0.0448\%$`, String.raw`$0.448\%$`, String.raw`$4.48\%$`],
    answer: 3,
    explanation: String.raw`Write the base as $1 + r$: $1.0448 = 1 + 0.0448$, so $r = 0.0448 = 4.48\%$ growth per year.`,
  },
  {
    id: "exp-mc-0615-q17",
    mode: "mc",
    standard: "AI-F.LE.5",
    topic: "Exponential models — growth rate from the base",
    examCitation: "regents-algI-0615-q17",
    part: "I",
    credits: 2,
    prompt: String.raw`The function $V(t) = 1350(1.017)^t$ gives the value, in dollars, of a comic book $t$ years after purchase. The yearly rate of appreciation is`,
    choices: [String.raw`$17\%$`, String.raw`$1.7\%$`, String.raw`$1.017\%$`, String.raw`$0.017\%$`],
    answer: 1,
    explanation: String.raw`$1.017 = 1 + 0.017$, so $r = 0.017 = 1.7\%$ appreciation each year.`,
  },
  {
    id: "exp-mc-0823-q12",
    mode: "mc",
    standard: "AI-F.LE.5",
    topic: "Exponential models — rate from A = P(1 + r)^t",
    examCitation: "regents-algI-0823-q12",
    part: "I",
    credits: 2,
    prompt: String.raw`Jim uses $A = P(1 + 0.05)^t$ to find the amount $A$ of an investment $P$ after $t$ years. Which phrase describes the yearly rate of change?`,
    choices: [
      "decreasing by 5%",
      "decreasing by 0.05%",
      "increasing by 5%",
      "increasing by 0.05%",
    ],
    answer: 2,
    explanation: String.raw`The form $P(1 + r)^t$ with $r = 0.05$ is growth: the amount is increasing by $5\%$ each year.`,
  },

  // ——— Decay rate from the base: b = 1 − r ———
  {
    id: "exp-mc-0619-q23",
    mode: "mc",
    standard: "AI-F.LE.5",
    topic: "Exponential models — decay rate from the base",
    examCitation: "regents-algI-0619-q23",
    part: "I",
    credits: 2,
    prompt: String.raw`A bacteria population is modeled by $f(t) = 1000(0.98)^t$, where $t$ is time since it started decaying. What is the rate of decay?`,
    choices: [String.raw`$98\%$`, String.raw`$2\%$`, String.raw`$0.98\%$`, String.raw`$0.02\%$`],
    answer: 1,
    explanation: String.raw`For decay, write the base as $1 - r$: $0.98 = 1 - 0.02$, so $r = 0.02 = 2\%$ decay. (The population keeps $98\%$ and loses $2\%$ each period.)`,
  },
  {
    id: "exp-mc-0816-q24",
    mode: "mc",
    standard: "AI-F.LE.5",
    topic: "Exponential models — decay rate from the base",
    examCitation: "regents-algI-0816-q24",
    part: "I",
    credits: 2,
    prompt: String.raw`Milton's stock portfolio is modeled by $v(x) = 30{,}000(0.78)^x$, where $x$ is years since he invested. Which statement describes the rate of change of the value?`,
    choices: [
      "It decreases 78% per year.",
      "It decreases 22% per year.",
      "It increases 78% per year.",
      "It increases 22% per year.",
    ],
    answer: 1,
    explanation: String.raw`$0.78 = 1 - 0.22$, so the value keeps $78\%$ and loses $22\%$ each year — it decreases $22\%$ per year.`,
  },
  {
    id: "exp-mc-0622-q21",
    mode: "mc",
    standard: "AI-F.LE.5",
    topic: "Exponential models — relate base to interest rate",
    examCitation: "regents-algI-0622-q21",
    part: "I",
    credits: 2,
    prompt: String.raw`In $A = P(1 + r)^t$, $r$ is the annual interest rate. Which statement correctly relates the rate to its equation?`,
    choices: [
      String.raw`For $A = P(1.025)^t$, the money is increasing at a $25\%$ rate.`,
      String.raw`For $A = P(1.0052)^t$, the money is increasing at a $52\%$ rate.`,
      String.raw`For $A = P(0.86)^t$, the money is decreasing at a $14\%$ rate.`,
      String.raw`For $A = P(0.68)^t$, the money is decreasing at a $68\%$ rate.`,
    ],
    answer: 2,
    explanation: String.raw`Compare each base to $1 \pm r$: $0.86 = 1 - 0.14$, a $14\%$ decrease — correct. The others misread the rate: $1.025$ is $2.5\%$ (not $25\%$), $1.0052$ is $0.52\%$ (not $52\%$), and $0.68 = 1 - 0.32$ is a $32\%$ decrease (not $68\%$).`,
  },
  {
    id: "exp-mc-0116-q08",
    mode: "mc",
    standard: "AI-F.LE.5",
    topic: "Exponential models — growth rate from the base",
    examCitation: "regents-algI-0116-q08",
    part: "I",
    credits: 2,
    prompt: String.raw`The equation $A = 1300(1.02)^7$ is being used to calculate the amount of money in a savings account. What does $1.02$ represent in this equation?`,
    choices: [
      String.raw`$0.02\%$ decay`,
      String.raw`$0.02\%$ growth`,
      String.raw`$2\%$ decay`,
      String.raw`$2\%$ growth`,
    ],
    answer: 3,
    explanation: String.raw`The base is the yearly factor. Write it as $1 + r$: $1.02 = 1 + 0.02$, so $r = 0.02 = 2\%$. Because the base exceeds $1$, it represents $2\%$ growth.`,
  },
  {
    id: "exp-mc-0117-q24",
    mode: "mc",
    standard: "AI-F.LE.5",
    topic: "Exponential models — interpreting the model",
    examCitation: "regents-algI-0117-q24",
    part: "I",
    credits: 2,
    prompt: String.raw`The 2014 winner of the Boston Marathon runs as many as 120 miles per week. During the last few weeks of his training for an event, his mileage can be modeled by $M(w) = 120(.90)^{w-1}$, where $w$ represents the number of weeks since training began. Which statement is true about the model $M(w)$?`,
    choices: [
      "The number of miles he runs will increase by 90% each week.",
      "The number of miles he runs will be 10% of the previous week.",
      String.raw`$M(w)$ represents the total mileage run in a given week.`,
      String.raw`$w$ represents the number of weeks left until his marathon.`,
    ],
    answer: 2,
    explanation: String.raw`$M(w)$ is the output — the mileage run in week $w$. The base $0.90 = 1 - 0.10$ means each week is $90\%$ of the previous week (a $10\%$ decrease), so choices 1 and 2 misread the base; $w$ counts weeks since training began, not weeks remaining.`,
  },

  // ——— Rewriting an exponential with the laws of exponents (AI-A.SSE.3) ———
  {
    id: "exp-mc-0623-q13",
    mode: "mc",
    standard: "AI-A.SSE.3",
    topic: "Equivalent exponential expressions",
    examCitation: "regents-algI-0623-q13",
    part: "I",
    credits: 2,
    prompt: String.raw`The expression $300(4)^{x+3}$ is equivalent to`,
    choices: [
      String.raw`$300(4)^x(4)^3$`,
      String.raw`$300(4^x)^3$`,
      String.raw`$300(4)^x + 300(4)^3$`,
      String.raw`$300^x(4)^3$`,
    ],
    answer: 0,
    explanation: String.raw`Adding exponents corresponds to multiplying powers of the same base: $4^{x+3} = 4^x \cdot 4^3$. So $300(4)^{x+3} = 300(4)^x(4)^3$.`,
  },
  {
    id: "exp-mc-0817-q16",
    mode: "mc",
    standard: "AI-A.SSE.3",
    topic: "Equivalent exponential expressions",
    examCitation: "regents-algI-0817-q16",
    part: "I",
    credits: 2,
    prompt: String.raw`Mario's \$15,000 car depreciates in value at a rate of $19\%$ per year. The value, $V$, after $t$ years can be modeled by the function $V = 15{,}000(0.81)^t$. Which function is equivalent to the original function?`,
    choices: [
      String.raw`$V = 15{,}000(0.9)^{9t}$`,
      String.raw`$V = 15{,}000(0.9)^{2t}$`,
      String.raw`$V = 15{,}000(0.9)^{\frac{t}{9}}$`,
      String.raw`$V = 15{,}000(0.9)^{\frac{t}{2}}$`,
    ],
    answer: 1,
    explanation: String.raw`Since $0.81 = 0.9^2$, $(0.81)^t = (0.9^2)^t = (0.9)^{2t}$. So $V = 15{,}000(0.9)^{2t}$.`,
  },
  {
    id: "exp-mc-0819-q13",
    mode: "mc",
    standard: "AI-A.SSE.3",
    topic: "Rewriting an exponential to reveal a rate",
    examCitation: "regents-algI-0819-q13",
    part: "I",
    credits: 2,
    prompt: String.raw`The population of a city can be modeled by $P(t) = 3810(1.0005)^{7t}$, where $P(t)$ is the population after $t$ years. Which function is approximately equivalent to $P(t)$?`,
    choices: [
      String.raw`$P(t) = 3810(0.1427)^t$`,
      String.raw`$P(t) = 3810(1.0035)^t$`,
      String.raw`$P(t) = 26{,}670(0.1427)^t$`,
      String.raw`$P(t) = 26{,}670(1.0035)^t$`,
    ],
    answer: 1,
    explanation: String.raw`Collapse the exponent into the base: $(1.0005)^{7t} = \left((1.0005)^7\right)^t \approx (1.0035)^t$. The initial value $3810$ (at $t = 0$) does not change.`,
  },
  {
    id: "exp-mc-0115-q19",
    mode: "mc",
    standard: "AI-A.SSE.3",
    topic: "Equivalent exponential expressions",
    examCitation: "regents-algI-0115-q19",
    part: "I",
    credits: 2,
    prompt: String.raw`Miriam and Jessica are growing bacteria in a laboratory. Miriam uses the growth function $f(t) = n^{2t}$ while Jessica uses the function $g(t) = n^{4t}$, where $n$ represents the initial number of bacteria and $t$ is the time, in hours. If Miriam starts with 16 bacteria, how many bacteria should Jessica start with to achieve the same growth over time?`,
    choices: ["32", "16", "8", "4"],
    answer: 3,
    explanation: String.raw`Miriam's function is $16^{2t} = (4^2)^{2t} = 4^{4t}$. For Jessica's $n^{4t}$ to equal $4^{4t}$, she must start with $n = 4$.`,
  },
  {
    id: "exp-mc-0120-q19",
    mode: "mc",
    standard: "AI-A.SSE.3",
    topic: "Equivalent exponential expressions",
    examCitation: "regents-algI-0120-q19",
    part: "I",
    credits: 2,
    prompt: String.raw`A laboratory technician used the function $t(m) = 2(3)^{2m+1}$ to model her research. Consider the following expressions: $\text{I. } 6(3)^{2m} \quad \text{II. } 6(6)^{2m} \quad \text{III. } 6(9)^m$. The function $t(m)$ is equivalent to`,
    choices: ["I, only", "II, only", "I and III", "II and III"],
    answer: 2,
    explanation: String.raw`$t(m) = 2(3)^{2m+1} = 2 \cdot 3^{2m} \cdot 3^1 = 6(3)^{2m}$ (expression I). Then $3^{2m} = (3^2)^m = 9^m$, giving $6(9)^m$ (expression III). Expression II uses base $6$, which is incorrect.`,
  },

  // ——— Building an exponential model from a table (AI-F.LE.2) ———
  {
    id: "exp-mc-0816-q17",
    mode: "mc",
    standard: "AI-F.LE.2",
    topic: "Building an exponential model from a table",
    examCitation: "regents-algI-0816-q17",
    part: "I",
    credits: 2,
    prompt: String.raw`The table below shows the temperature, $T(m)$, of a cup of hot chocolate that is allowed to chill over several minutes, $m$. Which expression best fits the data for $T(m)$?`,
    figure: {
      kind: "table",
      headers: ["Time, m (minutes)", "Temperature, T(m) (°F)"],
      rows: [
        [0, 150],
        [2, 108],
        [4, 78],
        [6, 56],
        [8, 41],
      ],
    },
    choices: [
      String.raw`$150(0.85)^m$`,
      String.raw`$150(1.15)^m$`,
      String.raw`$150(0.85)^{m-1}$`,
      String.raw`$150(1.15)^{m-1}$`,
    ],
    answer: 0,
    explanation: String.raw`At $m = 0$ the temperature is $150$, so the initial value is $150$ and the exponent must be $m$ (not $m-1$, which would put $150$ at $m = 1$). The temperature falls, so the base is below $1$: $150(0.85)^m$. Check $m = 2$: $150(0.85)^2 \approx 108$.`,
  },
  {
    id: "exp-mc-0119-q12",
    mode: "mc",
    standard: "AI-F.LE.2",
    topic: "Building an exponential model from a table",
    examCitation: "regents-algI-0119-q12",
    part: "I",
    credits: 2,
    prompt: String.raw`Marc bought a new laptop for \$1250. He kept track of the value of the laptop over the next three years, as shown in the table below. Which function can be used to determine the value of the laptop for $x$ years after the purchase?`,
    figure: {
      kind: "table",
      headers: ["Years After Purchase", "Value in Dollars"],
      rows: [
        [1, 1000],
        [2, 800],
        [3, 640],
      ],
    },
    choices: [
      String.raw`$f(x) = 1000(1.2)^x$`,
      String.raw`$f(x) = 1000(0.8)^x$`,
      String.raw`$f(x) = 1250(1.2)^x$`,
      String.raw`$f(x) = 1250(0.8)^x$`,
    ],
    answer: 3,
    explanation: String.raw`The initial value (at $x = 0$) is the \$1250 purchase price, so $a = 1250$. Each year the value is multiplied by $1000 / 1250 = 0.8$ (a $20\%$ drop): $f(x) = 1250(0.8)^x$. Check $x = 1$: $1250(0.8) = 1000$.`,
  },
  {
    id: "exp-mc-0118-q02",
    mode: "mc",
    standard: "AI-F.LE.2",
    topic: "Building an exponential model from a table",
    examCitation: "regents-algI-0118-q02",
    part: "I",
    credits: 2,
    prompt: String.raw`Jill invests \$400 in a savings bond. The value of the bond, $V(x)$, in hundreds of dollars after $x$ years is illustrated in the table below. Which equation and statement illustrate the approximate value of the bond in hundreds of dollars over time in years?`,
    figure: {
      kind: "table",
      headers: ["x", "V(x)"],
      rows: [
        [0, 4],
        [1, 5.4],
        [2, 7.29],
        [3, 9.84],
      ],
    },
    choices: [
      String.raw`$V(x) = 4(0.65)^x$ and it grows.`,
      String.raw`$V(x) = 4(0.65)^x$ and it decays.`,
      String.raw`$V(x) = 4(1.35)^x$ and it grows.`,
      String.raw`$V(x) = 4(1.35)^x$ and it decays.`,
    ],
    answer: 2,
    explanation: String.raw`At $x = 0$, $V = 4$, so $a = 4$. The ratio between successive values is $5.4 / 4 = 1.35$, so $V(x) = 4(1.35)^x$. Since the base $1.35 > 1$, the value grows.`,
  },

  // ——— Constructed-response (self-score against the official rubric) ———
  {
    id: "exp-cr-0815-q30",
    mode: "self-score",
    standard: "AI-F.LE.5",
    topic: "Exponential models — percent of change from the base",
    examCitation: "regents-algI-0815-q30",
    part: "II",
    credits: 2,
    prompt: String.raw`The number of carbon atoms in a fossil is given by the function $y = 5100(0.95)^x$, where $x$ represents the number of years since being discovered. What is the percent of change each year? Explain how you arrived at your answer.`,
    answerSummary: String.raw`$5\%$ (a $5\%$ decrease each year)`,
    modelSolution: String.raw`In an exponential model $y = ab^x$, the base $b$ is the yearly factor. Write it as $1 - r$ for decay: $0.95 = 1 - 0.05$, so $r = 0.05 = 5\%$. Because the base is less than $1$, the number of carbon atoms decreases by $5\%$ each year.`,
    rubric: [
      { credits: 2, criteria: String.raw`5, and a correct explanation is written.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but one conceptual error is made. OR 5, but the explanation is incomplete, incorrect, or missing.` },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "exp-cr-0617-q28",
    mode: "self-score",
    standard: "AI-F.LE.5",
    topic: "Exponential models — percent decrease from the base",
    examCitation: "regents-algI-0617-q28",
    part: "II",
    credits: 2,
    prompt: String.raw`The value, $v(t)$, of a car depreciates according to the function $v(t) = P(.85)^t$, where $P$ is the purchase price of the car and $t$ is the time, in years, since the car was purchased. State the percent that the value of the car decreases by each year. Justify your answer.`,
    answerSummary: String.raw`$15\%$`,
    modelSolution: String.raw`The base is the yearly decay factor. For decay, write it as $1 - r$: $0.85 = 1 - 0.15$, so $r = 0.15 = 15\%$. The value of the car decreases by $15\%$ each year.`,
    rubric: [
      { credits: 2, criteria: String.raw`15, and a correct justification is written.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but one conceptual error is made. OR 15, but the justification is missing or incorrect.` },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "exp-cr-0614-q26",
    mode: "self-score",
    standard: "AI-F.LE.5",
    topic: "Exponential models — meaning of a and b",
    examCitation: "regents-algI-0614-q26",
    part: "II",
    credits: 2,
    prompt: String.raw`The breakdown of a sample of a chemical compound is represented by the function $p(t) = 300(0.5)^t$, where $p(t)$ represents the number of milligrams of the substance and $t$ represents the time, in years. In the function $p(t)$, explain what $0.5$ and $300$ represent.`,
    answerSummary: String.raw`$0.5$ is the rate of decay (the amount is halved each year) and $300$ is the initial amount, in milligrams.`,
    modelSolution: String.raw`In $p(t) = ab^t$, the coefficient $a = 300$ is the value at $t = 0$ — the initial amount of the compound, in milligrams. The base $b = 0.5$ is the decay factor: each year the amount is multiplied by $0.5$, i.e., cut in half.`,
    rubric: [
      { credits: 2, criteria: String.raw`Correct explanations are made, such as 0.5 is the rate of decay and 300 is the initial amount.` },
      { credits: 1, criteria: String.raw`One conceptual error is made. OR A correct explanation is made for 0.5 or 300.` },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "exp-cr-0116-q32",
    mode: "self-score",
    standard: "AI-A.SSE.3",
    topic: "Equivalent exponential expressions — evaluate and compare",
    examCitation: "regents-algI-0116-q32",
    part: "II",
    credits: 2,
    prompt: String.raw`Jacob and Jessica are studying the spread of dandelions. Jacob discovers that the growth over $t$ weeks can be defined by the function $f(t) = (8) \cdot 2^t$. Jessica finds that the growth function over $t$ weeks is $g(t) = 2^{t+3}$. Calculate the number of dandelions that Jacob and Jessica will each have after 5 weeks. Based on the growth from both functions, explain the relationship between $f(t)$ and $g(t)$.`,
    answerSummary: String.raw`Jacob: $256$; Jessica: $256$. The functions are equivalent: $f(t) = g(t)$.`,
    modelSolution: String.raw`Jacob: $f(5) = 8 \cdot 2^5 = 8 \cdot 32 = 256$. Jessica: $g(5) = 2^{5+3} = 2^8 = 256$. They are equal because $8 = 2^3$, so $f(t) = 2^3 \cdot 2^t = 2^{t+3} = g(t)$ — the two functions are equivalent.`,
    rubric: [
      { credits: 2, criteria: String.raw`Jacob has 256, Jessica has 256, and a correct explanation is written.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but one conceptual error is made. OR Jacob has 256, Jessica has 256, but no further correct work is shown. OR A correct explanation is written, but no further correct work is shown.` },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "exp-cr-0621-q29",
    mode: "self-score",
    standard: "AI-F.LE.2",
    topic: "Exponential vs. linear — constant ratio, not constant difference",
    examCitation: "regents-algI-0621-q29",
    part: "II",
    credits: 2,
    prompt: String.raw`Mike knows that $(3, 6.5)$ and $(4, 17.55)$ are points on the graph of an exponential function, $g(x)$, and he wants to find another point on the graph of this function. First, he subtracts $6.5$ from $17.55$ to get $11.05$. Next, he adds $11.05$ and $17.55$ to get $28.6$. He states that $(5, 28.6)$ is a point on $g(x)$. Is he correct? Explain your reasoning.`,
    answerSummary: String.raw`No. An exponential function grows by a constant ratio, not a constant difference; $g(5) = 17.55 \times 2.7 = 47.385$, not $28.6$.`,
    modelSolution: String.raw`No. Mike added a constant difference ($+11.05$), which is how a linear function behaves. An exponential function changes by a constant ratio. From the two points the ratio is $\frac{17.55}{6.5} = 2.7$, so each step multiplies by $2.7$. Then $g(5) = 17.55 \times 2.7 = 47.385$, not $28.6$, so $(5, 28.6)$ is not on $g(x)$.`,
    rubric: [
      { credits: 2, criteria: String.raw`No, and a correct explanation is written.` },
      { credits: 1, criteria: String.raw`One conceptual error is made. OR No, but the explanation is incomplete.` },
      { credits: 0, criteria: "No, but the explanation is missing or incorrect. OR A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },

  // ——— Build & use an exponential model: write it, then evaluate (AI-F.LE.2) ———
  {
    id: "exp-cr-0814-q26",
    mode: "self-score",
    standard: "AI-F.LE.2",
    topic: "Writing an exponential model (compound interest)",
    examCitation: "regents-algI-0814-q26",
    part: "II",
    credits: 2,
    prompt: String.raw`Rhonda deposited \$3000 in an account in the Merrick National Bank, earning $4.2\%$ interest, compounded annually. She made no deposits or withdrawals. Write an equation that can be used to find $B$, her account balance after $t$ years.`,
    answerSummary: String.raw`$B = 3000(1.042)^t$`,
    modelSolution: String.raw`Use the growth form $B = P(1 + r)^t$ with principal $P = 3000$ and annual rate $r = 0.042$: $B = 3000(1 + 0.042)^t = 3000(1.042)^t$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$B = 3000(1 + 0.042)^t$ or an equivalent equation in terms of $B$ and $t$ is written.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but one conceptual error is made. OR The expression $(1 + 0.042)^t$ is written.` },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "exp-cr-0615-q29",
    mode: "self-score",
    standard: "AI-F.LE.2",
    topic: "Evaluating an exponential model (compound interest)",
    examCitation: "regents-algI-0615-q29",
    part: "II",
    credits: 2,
    prompt: String.raw`Dylan invested \$600 in a savings account at a $1.6\%$ annual interest rate. He made no deposits or withdrawals on the account for 2 years. The interest was compounded annually. Find, to the nearest cent, the balance in the account after 2 years.`,
    answerSummary: String.raw`\$619.35`,
    modelSolution: String.raw`Use $A = P(1 + r)^t$ with $P = 600$, $r = 0.016$, and $t = 2$: $A = 600(1.016)^2 = 600(1.032256) = 619.3536$, which rounds to \$619.35.`,
    rubric: [
      { credits: 2, criteria: String.raw`$619.35$, and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational or rounding error is made. OR Appropriate work is shown, but one conceptual error is made. OR $A = 600(1 + .016)^2$ or an equivalent equation is written, but no further correct work is shown. OR $600(1 + .016)^2$ or an equivalent expression is written, but no further correct work is shown. OR $619.35$, but no work is shown.` },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "exp-cr-0119-q33",
    mode: "self-score",
    standard: "AI-F.LE.2",
    topic: "Writing and using an exponential model",
    examCitation: "regents-algI-0119-q33",
    part: "III",
    credits: 4,
    prompt: String.raw`Marilyn collects old dolls. She purchases a doll for \$450. Research shows this doll's value will increase by $2.5\%$ each year. Write an equation that determines the value, $V$, of the doll $t$ years after purchase. Assuming the doll's rate of appreciation remains the same, will the doll's value be doubled in 20 years? Justify your reasoning.`,
    answerSummary: String.raw`$V = 450(1.025)^t$; No — after 20 years the value is about \$737.38, which is far less than double (\$900).`,
    modelSolution: String.raw`The value grows by $2.5\%$ per year, so $V = 450(1 + 0.025)^t = 450(1.025)^t$. After 20 years, $V = 450(1.025)^{20} \approx 737.38$. Doubling the \$450 purchase price would require \$900, but \$737.38 is well short of that, so No — the doll's value will not be doubled in 20 years.`,
    rubric: [
      { credits: 4, criteria: String.raw`$V = 450(1.025)^t$, and a correct justification indicating a negative response is given.` },
      { credits: 3, criteria: String.raw`Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but the expression $450(1.025)^t$ is written. OR Appropriate work is shown, but the equation is not written in terms of $V$ and $t$. OR $V = 450(1.025)^t$, and $737.38$, the correct value after 20 years is found, but no further correct work is shown. OR An incorrect exponential equation in terms of $V$ and $t$ is written and used appropriately.` },
      { credits: 2, criteria: String.raw`$V = 450(1.025)^t$, but no further correct work is shown.` },
      { credits: 1, criteria: String.raw`The expression $450(1.025)^t$ is written, but no further correct work is shown.` },
      { credits: 0, criteria: "No is stated, but no work is shown. OR A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "exp-cr-0818-q34",
    mode: "self-score",
    standard: "AI-F.LE.2",
    topic: "Writing and using an exponential model (depreciation)",
    examCitation: "regents-algI-0818-q34",
    part: "III",
    credits: 4,
    prompt: String.raw`A car was purchased for \$25,000. Research shows that the car has an average yearly depreciation rate of $18.5\%$. Create a function that will determine the value, $V(t)$, of the car $t$ years after purchase. Determine, to the nearest cent, how much the car will depreciate from year 3 to year 4.`,
    answerSummary: String.raw`$V(t) = 25{,}000(0.815)^t$; the car depreciates about \$2503.71 from year 3 to year 4.`,
    modelSolution: String.raw`A depreciation rate of $18.5\%$ means the car keeps $1 - 0.185 = 0.815$ of its value each year: $V(t) = 25{,}000(0.815)^t$. Year 3: $V(3) = 25{,}000(0.815)^3 \approx 13{,}533.59$. Year 4: $V(4) = 25{,}000(0.815)^4 \approx 11{,}029.88$. The depreciation from year 3 to year 4 is $V(3) - V(4) \approx 13{,}533.59 - 11{,}029.88 = 2503.71$, or about \$2503.71.`,
    rubric: [
      { credits: 4, criteria: String.raw`$V(t) = 25{,}000(1 - 0.185)^t$ or $V(t) = 25{,}000(0.815)^t$, and $2503.71$, and correct work is shown.` },
      { credits: 3, criteria: String.raw`Appropriate work is shown, but one computational or rounding error is made. OR Appropriate work is shown, but the function is not written in terms of $V(t)$ and $t$. OR Appropriate work is shown, but an expression is written instead of a function. OR Appropriate work is shown, but the difference is not stated.` },
      { credits: 2, criteria: String.raw`Appropriate work is shown, but two or more computational or rounding errors are made. OR $V(t) = 25{,}000(1 - 0.185)^t$ is written, but no further correct work is shown.` },
      { credits: 1, criteria: String.raw`$2503.71$, but no work is shown.` },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "exp-cr-0819-q34",
    mode: "self-score",
    standard: "AI-F.LE.2",
    topic: "Writing and using an exponential model (investment)",
    examCitation: "regents-algI-0819-q34",
    part: "III",
    credits: 4,
    prompt: String.raw`On the day Alexander was born, his father invested \$5000 in an account with a $1.2\%$ annual growth rate. Write a function, $A(t)$, that represents the value of this investment $t$ years after Alexander's birth. Determine, to the nearest dollar, how much more the investment will be worth when Alexander turns 32 than when he turns 17.`,
    answerSummary: String.raw`$A(t) = 5000(1.012)^t$; about \$1200 more at age 32 than at age 17.`,
    modelSolution: String.raw`A growth rate of $1.2\%$ per year gives $A(t) = 5000(1 + 0.012)^t = 5000(1.012)^t$. At age 32: $A(32) = 5000(1.012)^{32} \approx 7323.74$. At age 17: $A(17) = 5000(1.012)^{17} \approx 6124.01$. The difference is $A(32) - A(17) \approx 7323.74 - 6124.01 = 1199.73$, or about \$1200 more.`,
    rubric: [
      { credits: 4, criteria: String.raw`$A(t) = 5000(1.012)^t$, $1200$, and correct work is shown.` },
      { credits: 3, criteria: String.raw`Appropriate work is shown, but one computational or rounding error is made. OR Appropriate work is shown, but the expression is written instead of an equation. OR Appropriate work is shown to find $A(32)$ and $A(17)$, but $1200$ is not stated. OR $A(t) = 5000(1.012)^t$ and $1200$ are stated, but no work is shown.` },
      { credits: 2, criteria: String.raw`Appropriate work is shown, but two or more computational or rounding errors are made. OR $A(t) = 5000(1.012)^t$, but no further correct work is shown.` },
      { credits: 1, criteria: String.raw`The expression $5000(1.012)^t$ is written, but no further correct work is shown. OR $1200$, but no work is shown.` },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
];

export default bank;
