// Authored Regents problem-bank — Factoring (AI-A.SSE.2): using the structure of
// an expression to factor it completely — greatest common factor, difference of
// two perfect squares, trinomials, and factoring by grouping. (Distinct from
// "Solving Quadratics", which uses factoring to find roots; here factoring is the
// goal.) Real released Algebra I Regents questions mined from the official NYSED
// administrations (via JMAP), cited to the exam + question number. Every answer
// independently re-derived; signs verified against the source PDFs. Every
// self-score rubric is transcribed verbatim from the official NYSED Rating Guide.
// SME-ratified.

import type { RegentsItem } from "@/lib/regents/bank";

const bank: RegentsItem[] = [
  // ——————————————————————— Part I multiple choice ———————————————————————

  // ——— Monic trinomials (leading coefficient 1) ———
  {
    id: "fac-mc-0622-q04",
    mode: "mc",
    standard: "AI-A.SSE.2",
    topic: "Factoring — trinomials (leading coefficient 1)",
    examCitation: "regents-algI-0622-q04",
    part: "I",
    credits: 2,
    prompt: String.raw`Which expression is equivalent to $x^2 + 5x - 6$?`,
    choices: [
      String.raw`$(x + 3)(x - 2)$`,
      String.raw`$(x + 2)(x - 3)$`,
      String.raw`$(x - 6)(x + 1)$`,
      String.raw`$(x + 6)(x - 1)$`,
    ],
    answer: 3,
    explanation: String.raw`Find two numbers whose product is $-6$ and whose sum is $+5$: that is $+6$ and $-1$. So $x^2 + 5x - 6 = (x + 6)(x - 1)$. Check: $(x + 6)(x - 1) = x^2 - x + 6x - 6 = x^2 + 5x - 6$.`,
  },
  {
    id: "fac-mc-0824-q01",
    mode: "mc",
    standard: "AI-A.SSE.2",
    topic: "Factoring — trinomials (leading coefficient 1)",
    examCitation: "regents-algI-0824-q01",
    part: "I",
    credits: 2,
    prompt: String.raw`What is the correct factorization of $x^2 + 4x - 12$?`,
    choices: [
      String.raw`$(x + 3)(x - 4)$`,
      String.raw`$(x - 3)(x + 4)$`,
      String.raw`$(x + 2)(x - 6)$`,
      String.raw`$(x - 2)(x + 6)$`,
    ],
    answer: 3,
    explanation: String.raw`Two numbers with product $-12$ and sum $+4$: $-2$ and $+6$. So $x^2 + 4x - 12 = (x - 2)(x + 6)$. Check: $(x - 2)(x + 6) = x^2 + 6x - 2x - 12 = x^2 + 4x - 12$.`,
  },
  {
    id: "fac-mc-0120-q12",
    mode: "mc",
    standard: "AI-A.SSE.2",
    topic: "Factoring — trinomials (leading coefficient 1)",
    examCitation: "regents-algI-0120-q12",
    part: "I",
    credits: 2,
    prompt: String.raw`The expression $x^2 - 10x + 24$ is equivalent to`,
    choices: [
      String.raw`$(x + 12)(x - 2)$`,
      String.raw`$(x - 12)(x + 2)$`,
      String.raw`$(x + 6)(x + 4)$`,
      String.raw`$(x - 6)(x - 4)$`,
    ],
    answer: 3,
    explanation: String.raw`Two numbers with product $+24$ and sum $-10$ are both negative: $-6$ and $-4$. So $x^2 - 10x + 24 = (x - 6)(x - 4)$. Check: $(x - 6)(x - 4) = x^2 - 4x - 6x + 24 = x^2 - 10x + 24$.`,
  },
  {
    id: "fac-mc-0818-q03",
    mode: "mc",
    standard: "AI-A.SSE.2",
    topic: "Factoring — trinomials (leading coefficient 1)",
    examCitation: "regents-algI-0818-q03",
    part: "I",
    credits: 2,
    prompt: String.raw`David correctly factored the expression $m^2 - 12m - 64$. Which expression did he write?`,
    choices: [
      String.raw`$(m - 8)(m - 8)$`,
      String.raw`$(m - 8)(m + 8)$`,
      String.raw`$(m - 16)(m + 4)$`,
      String.raw`$(m + 16)(m - 4)$`,
    ],
    answer: 2,
    explanation: String.raw`Two numbers with product $-64$ and sum $-12$: $-16$ and $+4$. So $m^2 - 12m - 64 = (m - 16)(m + 4)$. Check: $(m - 16)(m + 4) = m^2 + 4m - 16m - 64 = m^2 - 12m - 64$.`,
  },
  {
    id: "fac-mc-0618-q10",
    mode: "mc",
    standard: "AI-A.SSE.2",
    topic: "Factoring — perfect-square trinomials",
    examCitation: "regents-algI-0618-q10",
    part: "I",
    credits: 2,
    prompt: String.raw`The trinomial $x^2 - 14x + 49$ can be expressed as`,
    choices: [
      String.raw`$(x - 7)^2$`,
      String.raw`$(x + 7)^2$`,
      String.raw`$(x - 7)(x + 7)$`,
      String.raw`$(x - 7)(x + 2)$`,
    ],
    answer: 0,
    explanation: String.raw`This is a perfect-square trinomial: $49 = 7^2$ and the middle term $-14x = 2(-7)(x)$, so $x^2 - 14x + 49 = (x - 7)^2$. Check: $(x - 7)^2 = x^2 - 14x + 49$.`,
  },
  {
    id: "fac-mc-0126-q04",
    mode: "mc",
    standard: "AI-A.SSE.2",
    topic: "Factoring — trinomials (leading coefficient 1)",
    examCitation: "regents-algI-0126-q04",
    part: "I",
    credits: 2,
    prompt: String.raw`The expression $x^2 - 26x - 120$ is equivalent to`,
    choices: [
      String.raw`$(x + 4)(x - 30)$`,
      String.raw`$(x - 4)(x + 30)$`,
      String.raw`$(x - 20)(x + 6)$`,
      String.raw`$(x + 20)(x - 6)$`,
    ],
    answer: 0,
    explanation: String.raw`Two numbers with product $-120$ and sum $-26$: $+4$ and $-30$. So $x^2 - 26x - 120 = (x + 4)(x - 30)$. Check: $(x + 4)(x - 30) = x^2 - 30x + 4x - 120 = x^2 - 26x - 120$.`,
  },

  // ——— Leading-coefficient trinomials ———
  {
    id: "fac-mc-0119-q06",
    mode: "mc",
    standard: "AI-A.SSE.2",
    topic: "Factoring — trinomials (leading coefficient > 1)",
    examCitation: "regents-algI-0119-q06",
    part: "I",
    credits: 2,
    prompt: String.raw`The area of a rectangle is represented by $3x^2 - 10x - 8$. Which expression can also be used to represent the area of the same rectangle?`,
    choices: [
      String.raw`$(3x + 2)(x - 4)$`,
      String.raw`$(3x - 2)(x + 4)$`,
      String.raw`$(3x + 4)(x - 2)$`,
      String.raw`$(3x - 4)(x + 2)$`,
    ],
    answer: 0,
    explanation: String.raw`Split the middle term: $3x^2 - 10x - 8 = 3x^2 - 12x + 2x - 8 = 3x(x - 4) + 2(x - 4) = (3x + 2)(x - 4)$. Check: $(3x + 2)(x - 4) = 3x^2 - 12x + 2x - 8 = 3x^2 - 10x - 8$.`,
  },
  {
    id: "fac-mc-0619-q17",
    mode: "mc",
    standard: "AI-A.SSE.2",
    topic: "Factoring — trinomials (leading coefficient > 1)",
    examCitation: "regents-algI-0619-q17",
    part: "I",
    credits: 2,
    prompt: String.raw`When written in factored form, $4w^2 - 11w - 3$ is equivalent to`,
    choices: [
      String.raw`$(2w + 1)(2w - 3)$`,
      String.raw`$(2w - 1)(2w + 3)$`,
      String.raw`$(4w + 1)(w - 3)$`,
      String.raw`$(4w - 1)(w + 3)$`,
    ],
    answer: 2,
    explanation: String.raw`Find factors of $4 \cdot (-3) = -12$ that sum to $-11$: $+1$ and $-12$. Then $4w^2 + w - 12w - 3 = w(4w + 1) - 3(4w + 1) = (4w + 1)(w - 3)$. Check: $(4w + 1)(w - 3) = 4w^2 - 12w + w - 3 = 4w^2 - 11w - 3$.`,
  },
  {
    id: "fac-mc-0621-q10",
    mode: "mc",
    standard: "AI-A.SSE.2",
    topic: "Factoring — trinomials (leading coefficient > 1)",
    examCitation: "regents-algI-0621-q10",
    part: "I",
    credits: 2,
    prompt: String.raw`Which product is equivalent to $4x^2 - 3x - 27$?`,
    choices: [
      String.raw`$(2x + 9)(2x - 3)$`,
      String.raw`$(2x - 9)(2x + 3)$`,
      String.raw`$(4x + 9)(x - 3)$`,
      String.raw`$(4x - 9)(x + 3)$`,
    ],
    answer: 2,
    explanation: String.raw`Find factors of $4 \cdot (-27) = -108$ that sum to $-3$: $+9$ and $-12$. Then $4x^2 + 9x - 12x - 27 = x(4x + 9) - 3(4x + 9) = (4x + 9)(x - 3)$. Check: $(4x + 9)(x - 3) = 4x^2 - 12x + 9x - 27 = 4x^2 - 3x - 27$.`,
  },

  // ——— Factor completely (GCF, then a pattern) ———
  {
    id: "fac-mc-0123-q14",
    mode: "mc",
    standard: "AI-A.SSE.2",
    topic: "Factoring completely",
    examCitation: "regents-algI-0123-q14",
    part: "I",
    credits: 2,
    prompt: String.raw`Which expression is equivalent to $2x^2 + 8x - 10$?`,
    choices: [
      String.raw`$2(x - 1)(x + 5)$`,
      String.raw`$2(x + 1)(x - 5)$`,
      String.raw`$2(x - 1)(x - 5)$`,
      String.raw`$2(x + 1)(x + 5)$`,
    ],
    answer: 0,
    explanation: String.raw`Factor out the GCF first: $2x^2 + 8x - 10 = 2(x^2 + 4x - 5)$. Then $x^2 + 4x - 5 = (x - 1)(x + 5)$ (product $-5$, sum $+4$). So the expression is $2(x - 1)(x + 5)$.`,
  },
  {
    id: "fac-mc-0116-q12",
    mode: "mc",
    standard: "AI-A.SSE.2",
    topic: "Factoring completely",
    examCitation: "regents-algI-0116-q12",
    part: "I",
    credits: 2,
    prompt: String.raw`When factored completely, $x^3 - 13x^2 - 30x$ is`,
    choices: [
      String.raw`$x(x + 3)(x - 10)$`,
      String.raw`$x(x - 3)(x + 10)$`,
      String.raw`$x(x + 2)(x - 15)$`,
      String.raw`$x(x - 2)(x + 15)$`,
    ],
    answer: 2,
    explanation: String.raw`Factor out the common $x$: $x^3 - 13x^2 - 30x = x(x^2 - 13x - 30)$. Then $x^2 - 13x - 30 = (x + 2)(x - 15)$ (product $-30$, sum $-13$). So the expression is $x(x + 2)(x - 15)$.`,
  },

  // ——— Recognizing equivalent (which is NOT) ———
  {
    id: "fac-mc-0819-q16",
    mode: "mc",
    standard: "AI-A.SSE.2",
    topic: "Factoring — recognizing equivalent forms",
    examCitation: "regents-algI-0819-q16",
    part: "I",
    credits: 2,
    prompt: String.raw`Which expression is *not* equivalent to $2x^2 + 10x + 12$?`,
    choices: [
      String.raw`$(2x + 4)(x + 3)$`,
      String.raw`$(2x + 6)(x + 2)$`,
      String.raw`$(2x + 3)(x + 4)$`,
      String.raw`$2(x + 3)(x + 2)$`,
    ],
    answer: 2,
    explanation: String.raw`$2x^2 + 10x + 12 = 2(x^2 + 5x + 6) = 2(x + 3)(x + 2)$, which also equals $(2x + 4)(x + 3)$ and $(2x + 6)(x + 2)$. But $(2x + 3)(x + 4) = 2x^2 + 8x + 3x + 12 = 2x^2 + 11x + 12$, so it is *not* equivalent.`,
  },

  // ——— Difference of two perfect squares ———
  {
    id: "fac-mc-0626-q03",
    mode: "mc",
    standard: "AI-A.SSE.2",
    topic: "Factoring — difference of two squares",
    examCitation: "regents-algI-0626-q03",
    part: "I",
    credits: 2,
    prompt: String.raw`The binomial $4x^2 - 25$ is equivalent to`,
    choices: [
      String.raw`$4(x + 5)(x - 5)$`,
      String.raw`$4(x - 5)(x - 5)$`,
      String.raw`$(2x - 5)(2x + 5)$`,
      String.raw`$(2x - 5)(2x - 5)$`,
    ],
    answer: 2,
    explanation: String.raw`A difference of two squares, $a^2 - b^2 = (a - b)(a + b)$, with $a = 2x$ (since $(2x)^2 = 4x^2$) and $b = 5$: $4x^2 - 25 = (2x - 5)(2x + 5)$.`,
  },
  {
    id: "fac-mc-0817-q03",
    mode: "mc",
    standard: "AI-A.SSE.2",
    topic: "Factoring — difference of two squares",
    examCitation: "regents-algI-0817-q03",
    part: "I",
    credits: 2,
    prompt: String.raw`The expression $49x^2 - 36$ is equivalent to`,
    choices: [
      String.raw`$(7x - 6)^2$`,
      String.raw`$(24.5x - 18)^2$`,
      String.raw`$(7x - 6)(7x + 6)$`,
      String.raw`$(24.5x - 18)(24.5x + 18)$`,
    ],
    answer: 2,
    explanation: String.raw`A difference of two squares with $a = 7x$ (since $(7x)^2 = 49x^2$) and $b = 6$ (since $6^2 = 36$): $49x^2 - 36 = (7x - 6)(7x + 6)$.`,
  },
  {
    id: "fac-mc-0822-q03",
    mode: "mc",
    standard: "AI-A.SSE.2",
    topic: "Factoring — difference of two squares",
    examCitation: "regents-algI-0822-q03",
    part: "I",
    credits: 2,
    prompt: String.raw`The expression $36x^2 - 9$ is equivalent to`,
    choices: [
      String.raw`$(6x - 3)^2$`,
      String.raw`$(18x - 4.5)^2$`,
      String.raw`$(6x + 3)(6x - 3)$`,
      String.raw`$(18x + 4.5)(18x - 4.5)$`,
    ],
    answer: 2,
    explanation: String.raw`A difference of two squares with $a = 6x$ (since $(6x)^2 = 36x^2$) and $b = 3$ (since $3^2 = 9$): $36x^2 - 9 = (6x + 3)(6x - 3)$.`,
  },
  {
    id: "fac-mc-0819-q08",
    mode: "mc",
    standard: "AI-A.SSE.2",
    topic: "Factoring — difference of two squares",
    examCitation: "regents-algI-0819-q08",
    part: "I",
    credits: 2,
    prompt: String.raw`The expression $16x^2 - 81$ is equivalent to`,
    choices: [
      String.raw`$(8x + 9)(8x - 9)$`,
      String.raw`$(8x - 9)(8x - 9)$`,
      String.raw`$(4x - 9)(4x + 9)$`,
      String.raw`$(4x - 9)(4x - 9)$`,
    ],
    answer: 2,
    explanation: String.raw`A difference of two squares with $a = 4x$ (since $(4x)^2 = 16x^2$) and $b = 9$ (since $9^2 = 81$): $16x^2 - 81 = (4x - 9)(4x + 9)$.`,
  },

  // ——— Difference of squares with a GCF first (factor completely) ———
  {
    id: "fac-mc-0117-q01",
    mode: "mc",
    standard: "AI-A.SSE.2",
    topic: "Factoring completely",
    examCitation: "regents-algI-0117-q01",
    part: "I",
    credits: 2,
    prompt: String.raw`Which expression is equivalent to $16x^2 - 36$?`,
    choices: [
      String.raw`$4(2x - 3)(2x - 3)$`,
      String.raw`$4(2x + 3)(2x - 3)$`,
      String.raw`$(4x - 6)(4x + 6)$`,
      String.raw`$(4x + 6)(4x + 6)$`,
    ],
    answer: 1,
    explanation: String.raw`Factor out the GCF first: $16x^2 - 36 = 4(4x^2 - 9)$. Then $4x^2 - 9$ is a difference of squares, $(2x + 3)(2x - 3)$. So $16x^2 - 36 = 4(2x + 3)(2x - 3)$.`,
  },
  {
    id: "fac-mc-0816-q08",
    mode: "mc",
    standard: "AI-A.SSE.2",
    topic: "Factoring completely",
    examCitation: "regents-algI-0816-q08",
    part: "I",
    credits: 2,
    prompt: String.raw`Which expression is equivalent to $36x^2 - 100$?`,
    choices: [
      String.raw`$4(3x - 5)(3x - 5)$`,
      String.raw`$4(3x + 5)(3x - 5)$`,
      String.raw`$2(9x - 25)(9x + 25)$`,
      String.raw`$2(9x + 25)(9x - 25)$`,
    ],
    answer: 1,
    explanation: String.raw`Factor out the GCF first: $36x^2 - 100 = 4(9x^2 - 25)$. Then $9x^2 - 25$ is a difference of squares, $(3x + 5)(3x - 5)$. So $36x^2 - 100 = 4(3x + 5)(3x - 5)$.`,
  },
  {
    id: "fac-mc-0619-q01",
    mode: "mc",
    standard: "AI-A.SSE.2",
    topic: "Factoring — difference of two squares",
    examCitation: "regents-algI-0619-q01",
    part: "I",
    credits: 2,
    prompt: String.raw`The expression $w^4 - 36$ is equivalent to`,
    choices: [
      String.raw`$(w^2 - 18)(w^2 - 18)$`,
      String.raw`$(w^2 + 18)(w^2 - 18)$`,
      String.raw`$(w^2 - 6)(w^2 - 6)$`,
      String.raw`$(w^2 + 6)(w^2 - 6)$`,
    ],
    answer: 3,
    explanation: String.raw`A difference of two squares with $a = w^2$ (since $(w^2)^2 = w^4$) and $b = 6$ (since $6^2 = 36$): $w^4 - 36 = (w^2 + 6)(w^2 - 6)$.`,
  },

  // The original seed item (difference of two squares).
  {
    id: "fac-mc-0623-q01",
    mode: "mc",
    standard: "AI-A.SSE.2",
    topic: "Factoring — difference of two squares",
    examCitation: "regents-algI-0623-q01",
    part: "I",
    credits: 2,
    prompt: String.raw`The expression $9m^2 - 100$ is equivalent to`,
    choices: [
      String.raw`$(3m - 10)(3m + 10)$`,
      String.raw`$(3m - 10)(3m - 10)$`,
      String.raw`$(3m - 50)(3m + 50)$`,
      String.raw`$(3m - 50)(3m - 50)$`,
    ],
    answer: 0,
    explanation: String.raw`This is a difference of two squares, $a^2 - b^2 = (a - b)(a + b)$, with $a = 3m$ (since $(3m)^2 = 9m^2$) and $b = 10$ (since $10^2 = 100$): $9m^2 - 100 = (3m - 10)(3m + 10)$.`,
  },

  // ——————————— Constructed-response (self-score vs official rubric) ———————————

  {
    id: "fac-cr-0623-q31",
    mode: "self-score",
    standard: "AI-A.SSE.2",
    topic: "Factoring completely",
    examCitation: "regents-algI-0623-q31",
    part: "II",
    credits: 2,
    prompt: String.raw`Factor $2x^2 + 16x - 18$ completely.`,
    answerSummary: String.raw`$2(x + 9)(x - 1)$`,
    modelSolution: String.raw`Factor out the GCF of $2$: $2x^2 + 16x - 18 = 2(x^2 + 8x - 9)$. Then factor the trinomial $x^2 + 8x - 9$ — two numbers with product $-9$ and sum $+8$ are $+9$ and $-1$ — giving $(x + 9)(x - 1)$. So $2x^2 + 16x - 18 = 2(x + 9)(x - 1)$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$2(x + 9)(x - 1)$, and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational or factoring error is made. OR Appropriate work is shown, but one conceptual error is made. OR $2(x + 9)(x - 1)$, but no work is shown.` },
      { credits: 0, criteria: String.raw`A zero response does not contain enough relevant course-level work to receive any credit, does not satisfy the criteria for one or more credits, or is a correct response that was obtained by an obviously incorrect procedure.` },
    ],
  },
  {
    id: "fac-cr-0822-q32",
    mode: "self-score",
    standard: "AI-A.SSE.2",
    topic: "Factoring completely",
    examCitation: "regents-algI-0822-q32",
    part: "II",
    credits: 2,
    prompt: String.raw`Factor completely: $3y^2 - 12y - 288$`,
    answerSummary: String.raw`$3(y - 12)(y + 8)$`,
    modelSolution: String.raw`Factor out the GCF of $3$: $3y^2 - 12y - 288 = 3(y^2 - 4y - 96)$. Then factor the trinomial $y^2 - 4y - 96$ — two numbers with product $-96$ and sum $-4$ are $-12$ and $+8$ — giving $(y - 12)(y + 8)$. So $3y^2 - 12y - 288 = 3(y - 12)(y + 8)$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$3(y - 12)(y + 8)$, and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational or factoring error is made. OR Appropriate work is shown, but one conceptual error is made. OR $3(y - 12)(y + 8)$, but no work is shown.` },
      { credits: 0, criteria: String.raw`A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure.` },
    ],
  },
  {
    id: "fac-cr-0823-q31",
    mode: "self-score",
    standard: "AI-A.SSE.2",
    topic: "Factoring completely",
    examCitation: "regents-algI-0823-q31",
    part: "II",
    credits: 2,
    prompt: String.raw`Factor $18x^2 - 2$ completely.`,
    answerSummary: String.raw`$2(3x + 1)(3x - 1)$`,
    modelSolution: String.raw`Factor out the GCF of $2$: $18x^2 - 2 = 2(9x^2 - 1)$. The factor $9x^2 - 1$ is a difference of two squares with $a = 3x$ and $b = 1$, so $9x^2 - 1 = (3x + 1)(3x - 1)$. Thus $18x^2 - 2 = 2(3x + 1)(3x - 1)$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$2(3x + 1)(3x - 1)$ is written, and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational or factoring error is made. OR $2(3x + 1)(3x - 1)$, but no work is shown.` },
      { credits: 0, criteria: String.raw`$2(9x^2 - 1)$, but no further correct work is shown. OR A zero response does not contain enough relevant course-level work to receive any credit, does not satisfy the criteria for one or more credits, or is a correct response that was obtained by an obviously incorrect procedure.` },
    ],
  },
  {
    id: "fac-cr-0124-q32",
    mode: "self-score",
    standard: "AI-A.SSE.2",
    topic: "Factoring completely",
    examCitation: "regents-algI-0124-q32",
    part: "II",
    credits: 2,
    prompt: String.raw`Factor $36 - 4x^2$ completely.`,
    answerSummary: String.raw`$4(3 + x)(3 - x)$`,
    modelSolution: String.raw`Factor out the GCF of $4$: $36 - 4x^2 = 4(9 - x^2)$. The factor $9 - x^2$ is a difference of two squares with $a = 3$ and $b = x$, so $9 - x^2 = (3 + x)(3 - x)$. Thus $36 - 4x^2 = 4(3 + x)(3 - x)$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$4(3 + x)(3 - x)$, and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational or factoring error is made. OR Appropriate work is shown, but one conceptual error is made. OR $(6 + 2x)(6 - 2x)$ is stated, but no further correct work is shown. OR $4(3 + x)(3 - x)$, but no work is shown.` },
      { credits: 0, criteria: String.raw`$4(9 - x^2)$ is stated, but no further correct work is shown. OR A zero response does not contain enough relevant course-level work to receive any credit, does not satisfy the criteria for one or more credits, or is a correct response that was obtained by an obviously incorrect procedure.` },
    ],
  },
  {
    id: "fac-cr-0625-q30",
    mode: "self-score",
    standard: "AI-A.SSE.2",
    topic: "Factoring completely",
    examCitation: "regents-algI-0625-q30",
    part: "II",
    credits: 2,
    prompt: String.raw`Factor the expression $x^3 - 36x$ completely.`,
    answerSummary: String.raw`$x(x + 6)(x - 6)$`,
    modelSolution: String.raw`Factor out the common $x$: $x^3 - 36x = x(x^2 - 36)$. The factor $x^2 - 36$ is a difference of two squares with $a = x$ and $b = 6$, so $x^2 - 36 = (x + 6)(x - 6)$. Thus $x^3 - 36x = x(x + 6)(x - 6)$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$x(x + 6)(x - 6)$, and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but one conceptual error is made. OR $x(x^2 - 36)$, but no further correct work is shown. OR $x(x + 6)(x - 6)$, but no work is shown.` },
      { credits: 0, criteria: String.raw`A zero response does not contain enough relevant course-level work to receive any credit, does not satisfy the criteria for one or more credits, or is a correct response that was obtained by an obviously incorrect procedure.` },
    ],
  },
  {
    id: "fac-cr-0123-q31",
    mode: "self-score",
    standard: "AI-A.SSE.2",
    topic: "Factoring completely",
    examCitation: "regents-algI-0123-q31",
    part: "II",
    credits: 2,
    prompt: String.raw`Factor completely: $4x^3 - 49x$`,
    answerSummary: String.raw`$x(2x + 7)(2x - 7)$`,
    modelSolution: String.raw`Factor out the common $x$: $4x^3 - 49x = x(4x^2 - 49)$. The factor $4x^2 - 49$ is a difference of two squares with $a = 2x$ and $b = 7$, so $4x^2 - 49 = (2x + 7)(2x - 7)$. Thus $4x^3 - 49x = x(2x + 7)(2x - 7)$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$x(2x + 7)(2x - 7)$, and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational or factoring error is made. OR Appropriate work is shown, but one conceptual error is made. OR $x(2x + 7)(2x - 7)$, but no work is shown.` },
      { credits: 0, criteria: String.raw`A zero response does not contain enough relevant course-level work to receive any credit, does not satisfy the criteria for one or more credits, or is a correct response that was obtained by an obviously incorrect procedure.` },
    ],
  },
  {
    id: "fac-cr-0824-q30",
    mode: "self-score",
    standard: "AI-A.SSE.2",
    topic: "Factoring completely",
    examCitation: "regents-algI-0824-q30",
    part: "II",
    credits: 2,
    prompt: String.raw`Factor $5x^3 - 80x$ completely.`,
    answerSummary: String.raw`$5x(x + 4)(x - 4)$`,
    modelSolution: String.raw`Factor out the GCF of $5x$: $5x^3 - 80x = 5x(x^2 - 16)$. The factor $x^2 - 16$ is a difference of two squares with $a = x$ and $b = 4$, so $x^2 - 16 = (x + 4)(x - 4)$. Thus $5x^3 - 80x = 5x(x + 4)(x - 4)$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$5x(x + 4)(x - 4)$, and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational or factoring error is made. OR Appropriate work is shown, but one conceptual error is made. OR $5x(x^2 - 16)$, but no further correct work is shown. OR $5x(x + 4)(x - 4)$, but no work is shown.` },
      { credits: 0, criteria: String.raw`$5(x^3 - 16x)$ or $x(5x^2 - 80)$ but no work is shown. OR A zero response does not contain enough relevant course-level work to receive any credit, does not satisfy the criteria for one or more credits, or is a correct response that was obtained by an obviously incorrect procedure.` },
    ],
  },
  {
    id: "fac-cr-0622-q31",
    mode: "self-score",
    standard: "AI-A.SSE.2",
    topic: "Factoring completely",
    examCitation: "regents-algI-0622-q31",
    part: "II",
    credits: 2,
    prompt: String.raw`Factor the expression $x^4 - 36x^2$ completely.`,
    answerSummary: String.raw`$x^2(x + 6)(x - 6)$`,
    modelSolution: String.raw`Factor out the GCF of $x^2$: $x^4 - 36x^2 = x^2(x^2 - 36)$. The factor $x^2 - 36$ is a difference of two squares with $a = x$ and $b = 6$, so $x^2 - 36 = (x + 6)(x - 6)$. Thus $x^4 - 36x^2 = x^2(x + 6)(x - 6)$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$x^2(x + 6)(x - 6)$, and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational or factoring error is made. OR Appropriate work is shown, but one conceptual error is made. OR $x^2(x^2 - 36)$ or $(x^2 + 6x)(x^2 - 6x)$ is written, but no further correct work is shown.` },
      { credits: 0, criteria: String.raw`A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure.` },
    ],
  },
  {
    id: "fac-cr-0621-q28",
    mode: "self-score",
    standard: "AI-A.SSE.2",
    topic: "Factoring completely",
    examCitation: "regents-algI-0621-q28",
    part: "II",
    credits: 2,
    prompt: String.raw`Factor $x^4 - 16$ completely.`,
    answerSummary: String.raw`$(x + 2)(x - 2)(x^2 + 4)$`,
    modelSolution: String.raw`$x^4 - 16$ is a difference of two squares with $a = x^2$ and $b = 4$: $x^4 - 16 = (x^2 + 4)(x^2 - 4)$. The factor $x^2 - 4$ is itself a difference of two squares, $(x + 2)(x - 2)$, while $x^2 + 4$ does not factor over the integers. So $x^4 - 16 = (x + 2)(x - 2)(x^2 + 4)$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$(x + 2)(x - 2)(x^2 + 4)$, and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one factoring error is made. OR Appropriate work is shown, but one conceptual error is made. OR $(x^2 + 4)(x^2 - 4)$ is written, but no further correct work is shown. OR $(x + 2)(x - 2)(x^2 + 4)$, but no work is shown.` },
      { credits: 0, criteria: String.raw`A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure.` },
    ],
  },
  {
    id: "fac-cr-0614-q31",
    mode: "self-score",
    standard: "AI-A.SSE.2",
    topic: "Factoring completely",
    examCitation: "regents-algI-0614-q31",
    part: "II",
    credits: 2,
    prompt: String.raw`Factor completely: $x^4 + 6x^2 - 7$`,
    answerSummary: String.raw`$(x^2 + 7)(x + 1)(x - 1)$`,
    modelSolution: String.raw`Treat the expression as a trinomial in $x^2$: two numbers with product $-7$ and sum $+6$ are $+7$ and $-1$, so $x^4 + 6x^2 - 7 = (x^2 + 7)(x^2 - 1)$. The factor $x^2 - 1$ is a difference of two squares, $(x + 1)(x - 1)$, while $x^2 + 7$ does not factor over the integers. So $x^4 + 6x^2 - 7 = (x^2 + 7)(x + 1)(x - 1)$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$(x^2 + 7)(x + 1)(x - 1)$ and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one factoring error is made. OR Appropriate work is shown, but one conceptual error is made. OR $(x^2 + 7)(x^2 - 1)$ is written, but no further correct work is shown.` },
      { credits: 0, criteria: String.raw`A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure.` },
    ],
  },
];

export default bank;
