// Authored Regents problem-bank — Function Basics (AI-F.IF.1 / F.IF.5 / F.IF.9):
// what makes a relation a function (each input has exactly one output; the
// vertical-line test), domain and range — including the practical domain that
// makes sense in a context (discrete vs. continuous) — and comparing two
// functions presented in different forms (table vs. equation). Real released
// Algebra I Regents questions mined from the official NYSED administrations (via
// JMAP), cited to the exam + question number. Every answer independently
// re-derived; signs verified against the source PDFs (page renders for the
// table/sign-ambiguous items). Every self-score rubric is transcribed verbatim
// from the official NYSED Rating Guide. SME-ratified.

import type { RegentsItem, RubricLevel } from "@/lib/regents/bank";

// The standardized 0-credit boilerplate used across the newer (2024–25) guides.
const ZERO_NEW =
  "A zero response does not contain enough relevant course-level work to receive any credit, does not satisfy the criteria for one or more credits, or is a correct response that was obtained by an obviously incorrect procedure.";
// The standardized 0-credit boilerplate used across the older (2014–17) guides.
const ZERO_OLD =
  "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure.";

const bank: RegentsItem[] = [
  // ——————————————————————— Part I multiple choice ———————————————————————

  // ---- AI-F.IF.1 — identifying functions (ordered pairs) ----
  {
    id: "fnb-mc-0822-q04",
    mode: "mc",
    standard: "AI-F.IF.1",
    topic: "Identifying functions — relations as ordered pairs",
    examCitation: "regents-algI-0822-q04",
    part: "I",
    credits: 2,
    prompt: String.raw`Given the relation $R = \{(-4, 2), (3, 6), (x, 8), (-1, 4)\}$. Which value of $x$ would make this relation a function?`,
    choices: [
      String.raw`$-4$`,
      String.raw`$-1$`,
      String.raw`$3$`,
      String.raw`$0$`,
    ],
    answer: 3,
    explanation: String.raw`A relation is a function when each input (first coordinate) has exactly one output. The relation already uses the inputs $-4$, $3$, and $-1$, so reusing any of those would pair one input with two different outputs. Of the choices, only $0$ is a new input, so $x = 0$ keeps $R$ a function.`,
  },
  {
    id: "fnb-mc-0124-q02",
    mode: "mc",
    standard: "AI-F.IF.1",
    topic: "Identifying functions — relations as ordered pairs",
    examCitation: "regents-algI-0124-q02",
    part: "I",
    credits: 2,
    prompt: String.raw`Given the relation $\{(0, 4), (2, 6), (4, 8), (x, 7)\}$. Which value of $x$ will make this relation a function?`,
    choices: [String.raw`$0$`, String.raw`$2$`, String.raw`$6$`, String.raw`$4$`],
    answer: 2,
    explanation: String.raw`The inputs $0$, $2$, and $4$ are already used. Reusing any of them would give one input two different outputs. Only $6$ is a new input, so $x = 6$ keeps the relation a function.`,
  },
  {
    id: "fnb-mc-0626-q04",
    mode: "mc",
    standard: "AI-F.IF.1",
    topic: "Identifying functions — relations as ordered pairs",
    examCitation: "regents-algI-0626-q04",
    part: "I",
    credits: 2,
    prompt: String.raw`A function is defined by the following set of points: $\{(3, -4), (-4, 3), (1, 1), (x, 2)\}$. What is a possible value for $x$?`,
    choices: [String.raw`$1$`, String.raw`$2$`, String.raw`$3$`, String.raw`$-4$`],
    answer: 1,
    explanation: String.raw`The inputs $3$, $-4$, and $1$ are already used. For the set to stay a function, $x$ must be a new input. Of the choices, only $2$ has not been used, so $x = 2$ works.`,
  },
  {
    id: "fnb-mc-0618-q11",
    mode: "mc",
    standard: "AI-F.IF.1",
    topic: "Identifying functions — relations as ordered pairs",
    examCitation: "regents-algI-0618-q11",
    part: "I",
    credits: 2,
    prompt: String.raw`A function is defined as $\{(0, 1), (2, 3), (5, 8), (7, 2)\}$. Isaac is asked to create one more ordered pair for the function. Which ordered pair can he add to the set to keep it a function?`,
    choices: [
      String.raw`$(0, 2)$`,
      String.raw`$(5, 3)$`,
      String.raw`$(7, 0)$`,
      String.raw`$(1, 3)$`,
    ],
    answer: 3,
    explanation: String.raw`The inputs $0$, $2$, $5$, and $7$ already appear. Adding $(0,2)$, $(5,3)$, or $(7,0)$ would give an existing input a second output. Only $(1, 3)$ uses a new input, $1$, so it keeps the set a function.`,
  },

  // ---- AI-F.IF.1 — identifying functions (which table is a function) ----
  {
    id: "fnb-mc-0615-q04",
    mode: "mc",
    standard: "AI-F.IF.1",
    topic: "Identifying functions — reading a table",
    examCitation: "regents-algI-0615-q04",
    part: "I",
    credits: 2,
    prompt: String.raw`Which table represents a function?`,
    choices: ["Table (1)", "Table (2)", "Table (3)", "Table (4)"],
    choiceFigures: [
      { kind: "table", headers: ["x", "f(x)"], rows: [[2, 3], [4, 5], [2, 7], [4, 9]] },
      { kind: "table", headers: ["x", "f(x)"], rows: [[0, 0], [-1, 1], [0, -1], [1, 0]] },
      { kind: "table", headers: ["x", "f(x)"], rows: [[3, 2], [5, 4], [7, 2], [9, 4]] },
      { kind: "table", headers: ["x", "f(x)"], rows: [[0, 0], [1, -1], [-1, 0], [0, 1]] },
    ],
    answer: 2,
    explanation: String.raw`A table is a function when no $x$-value repeats. Table (1) repeats $x = 2$ and $x = 4$; Table (2) and Table (4) both repeat $x = 0$. Only Table (3) has four distinct inputs ($3, 5, 7, 9$), so it represents a function.`,
  },
  {
    id: "fnb-mc-0819-q02",
    mode: "mc",
    standard: "AI-F.IF.1",
    topic: "Identifying functions — reading a table",
    examCitation: "regents-algI-0819-q02",
    part: "I",
    credits: 2,
    prompt: String.raw`Which table represents a function?`,
    choices: ["Table (1)", "Table (2)", "Table (3)", "Table (4)"],
    choiceFigures: [
      { kind: "table", headers: ["x", "y"], rows: [[2, -3], [3, 0], [4, -3], [2, 1]] },
      { kind: "table", headers: ["x", "y"], rows: [[1, 2], [1, 3], [1, 4], [1, 5]] },
      { kind: "table", headers: ["x", "y"], rows: [[-3, 0], [-2, 1], [-3, 2], [2, 3]] },
      { kind: "table", headers: ["x", "y"], rows: [[-2, -4], [0, 2], [2, 4], [4, 6]] },
    ],
    answer: 3,
    explanation: String.raw`Table (1) repeats $x = 2$, Table (2) repeats $x = 1$, and Table (3) repeats $x = -3$ — each pairs an input with two outputs. Only Table (4) has four distinct inputs, so it represents a function.`,
  },
  {
    id: "fnb-mc-0120-q04",
    mode: "mc",
    standard: "AI-F.IF.1",
    topic: "Identifying functions — reading a table",
    examCitation: "regents-algI-0120-q04",
    part: "I",
    credits: 2,
    prompt: String.raw`Which table could represent a function?`,
    choices: ["Table (1)", "Table (2)", "Table (3)", "Table (4)"],
    choiceFigures: [
      { kind: "table", headers: ["x", "f(x)"], rows: [[1, 4], [2, 2], [3, 4], [2, 6]] },
      { kind: "table", headers: ["x", "g(x)"], rows: [[1, 2], [2, 4], [3, 6], [4, 2]] },
      { kind: "table", headers: ["x", "h(x)"], rows: [[2, 6], [0, 4], [1, 6], [2, 2]] },
      { kind: "table", headers: ["x", "k(x)"], rows: [[2, 2], [3, 2], [4, 6], [3, 6]] },
    ],
    answer: 1,
    explanation: String.raw`Table (1) repeats $x = 2$, Table (3) repeats $x = 2$, and Table (4) repeats $x = 3$, each with two different outputs. Only Table (2) has four distinct inputs ($1, 2, 3, 4$), so it could represent a function. (A repeated output, like the two $2$'s, is allowed.)`,
  },

  // ---- AI-F.IF.5 — an appropriate (practical) domain for a context ----
  {
    id: "fnb-mc-0123-q13",
    mode: "mc",
    standard: "AI-F.IF.5",
    topic: "Appropriate domain in context",
    examCitation: "regents-algI-0123-q13",
    part: "I",
    credits: 2,
    prompt: String.raw`Skyler mows lawns in the summer. The function $f(x)$ is used to model the amount of money earned, where $x$ is the number of lawns completely mowed. A reasonable domain for this function would be`,
    choices: ["real numbers", "rational numbers", "irrational numbers", "natural numbers"],
    answer: 3,
    explanation: String.raw`You can only mow a whole number of complete lawns ($1, 2, 3, \ldots$), so the input is restricted to the counting (natural) numbers — it cannot be negative, fractional, or irrational.`,
  },
  {
    id: "fnb-mc-0622-q06",
    mode: "mc",
    standard: "AI-F.IF.5",
    topic: "Appropriate domain in context",
    examCitation: "regents-algI-0622-q06",
    part: "I",
    credits: 2,
    prompt: String.raw`Which domain is most appropriate for a function that represents the number of items, $f(x)$, placed into a laundry basket each day, $x$, for the month of January?`,
    choices: ["integers", "whole numbers", "rational numbers", "irrational numbers"],
    answer: 1,
    explanation: String.raw`The day count $x$ runs $1, 2, 3, \ldots, 31$ — there is no day $0$ or negative or fractional day, and the items are counted. Whole numbers ($0, 1, 2, \ldots$) are the most appropriate of the choices.`,
  },
  {
    id: "fnb-mc-0115-q06",
    mode: "mc",
    standard: "AI-F.IF.5",
    topic: "Appropriate domain in context",
    examCitation: "regents-algI-0115-q06",
    part: "I",
    credits: 2,
    prompt: String.raw`Which domain would be the most appropriate set to use for a function that predicts the number of household online-devices in terms of the number of people in the household?`,
    choices: ["integers", "whole numbers", "irrational numbers", "rational numbers"],
    answer: 1,
    explanation: String.raw`The number of people in a household is counted and cannot be negative or fractional, so the whole numbers ($0, 1, 2, \ldots$) are the most appropriate domain.`,
  },
  {
    id: "fnb-mc-0621-q16",
    mode: "mc",
    standard: "AI-F.IF.5",
    topic: "Appropriate domain in context",
    examCitation: "regents-algI-0621-q16",
    part: "I",
    credits: 2,
    prompt: String.raw`Which domain would be the most appropriate to use for a function that compares the number of emails sent ($x$) to the amount of data used for a cell phone plan ($y$)?`,
    choices: ["integers", "whole numbers", "rational numbers", "irrational numbers"],
    answer: 1,
    explanation: String.raw`The number of emails sent is a count that cannot be negative or fractional, so the whole numbers ($0, 1, 2, \ldots$) are the most appropriate domain.`,
  },
  {
    id: "fnb-mc-0819-q21",
    mode: "mc",
    standard: "AI-F.IF.5",
    topic: "Appropriate domain in context — discrete vs. continuous",
    examCitation: "regents-algI-0819-q21",
    part: "I",
    credits: 2,
    prompt: String.raw`A dolphin jumps out of the water and then back into the water. His jump could be graphed on a set of axes where $x$ represents time and $y$ represents distance above or below sea level. The domain for this graph is best represented using a set of`,
    choices: ["integers", "positive integers", "real numbers", "positive real numbers"],
    answer: 3,
    explanation: String.raw`Time flows continuously (not in whole-number jumps) and cannot be negative, so the domain is best modeled by the positive real numbers.`,
  },
  {
    id: "fnb-mc-0116-q15",
    mode: "mc",
    standard: "AI-F.IF.5",
    topic: "Appropriate domain in context",
    examCitation: "regents-algI-0116-q15",
    part: "I",
    credits: 2,
    prompt: String.raw`A construction company uses the function $f(p)$, where $p$ is the number of people working on a project, to model the amount of money it spends to complete a project. A reasonable domain for this function would be`,
    choices: [
      "positive integers",
      "positive real numbers",
      "both positive and negative integers",
      "both positive and negative real numbers",
    ],
    answer: 0,
    explanation: String.raw`The number of people working is a whole count and must be positive (you cannot have a negative or fractional worker), so the positive integers are the most reasonable domain.`,
  },
  {
    id: "fnb-mc-0616-q23",
    mode: "mc",
    standard: "AI-F.IF.5",
    topic: "Appropriate domain in context — discrete vs. continuous",
    examCitation: "regents-algI-0616-q23",
    part: "I",
    credits: 2,
    prompt: String.raw`A store sells self-serve frozen yogurt sundaes. The function $C(w)$ represents the cost, in dollars, of a sundae weighing $w$ ounces. An appropriate domain for the function would be`,
    choices: ["integers", "rational numbers", "nonnegative integers", "nonnegative rational numbers"],
    answer: 3,
    explanation: String.raw`Weight is continuous, so a sundae can weigh a fractional number of ounces (e.g. $4.5$ oz), but it cannot be negative. The nonnegative rational numbers fit best.`,
  },
  {
    id: "fnb-mc-0823-q22",
    mode: "mc",
    standard: "AI-F.IF.5",
    topic: "Appropriate domain in context — discrete vs. continuous",
    examCitation: "regents-algI-0823-q22",
    part: "I",
    credits: 2,
    prompt: String.raw`The function $G(m)$ represents the amount of gasoline consumed by a car traveling $m$ miles. An appropriate domain for this function would be`,
    choices: ["integers", "rational numbers", "nonnegative integers", "nonnegative rational numbers"],
    answer: 3,
    explanation: String.raw`Distance traveled is continuous (a car can go a fractional number of miles) and cannot be negative, so the nonnegative rational numbers are the most appropriate domain.`,
  },
  {
    id: "fnb-mc-0619-q20",
    mode: "mc",
    standard: "AI-F.IF.5",
    topic: "Appropriate domain in context — discrete vs. continuous",
    examCitation: "regents-algI-0619-q20",
    part: "I",
    credits: 2,
    prompt: String.raw`A grocery store sells packages of beef. The function $C(w)$ represents the cost, in dollars, of a package of beef weighing $w$ pounds. The most appropriate domain for this function would be`,
    choices: ["integers", "rational numbers", "positive integers", "positive rational numbers"],
    answer: 3,
    explanation: String.raw`The weight of a package is continuous and must be greater than $0$ (a package has some positive weight), so the positive rational numbers are the most appropriate domain.`,
  },
  {
    id: "fnb-mc-0117-q19",
    mode: "mc",
    standard: "AI-F.IF.5",
    topic: "Appropriate domain in context",
    examCitation: "regents-algI-0117-q19",
    part: "I",
    credits: 2,
    prompt: String.raw`The daily cost of production in a factory is calculated using $c(x) = 200 + 16x$, where $x$ is the number of complete products manufactured. Which set of numbers best defines the domain of $c(x)$?`,
    choices: ["integers", "positive real numbers", "positive rational numbers", "whole numbers"],
    answer: 3,
    explanation: String.raw`The number of complete products is a count that cannot be negative or fractional, so the whole numbers ($0, 1, 2, \ldots$) best define the domain.`,
  },
  {
    id: "fnb-mc-0618-q21",
    mode: "mc",
    standard: "AI-F.IF.5",
    topic: "Appropriate domain in context",
    examCitation: "regents-algI-0618-q21",
    part: "I",
    credits: 2,
    prompt: String.raw`At an ice cream shop, the profit, $P(c)$, is modeled by the function $P(c) = 0.87c$, where $c$ represents the number of ice cream cones sold. An appropriate domain for this function is`,
    choices: [
      String.raw`an integer $\le 0$`,
      String.raw`an integer $\ge 0$`,
      String.raw`a rational number $\le 0$`,
      String.raw`a rational number $\ge 0$`,
    ],
    answer: 1,
    explanation: String.raw`The number of cones sold is a whole count ($0, 1, 2, \ldots$) — it is an integer and cannot be negative, so the domain is an integer $\ge 0$.`,
  },
  {
    id: "fnb-mc-0614-q02",
    mode: "mc",
    standard: "AI-F.IF.5",
    topic: "Appropriate domain in context",
    examCitation: "regents-algI-0614-q02",
    part: "I",
    credits: 2,
    prompt: String.raw`Officials in a town use a function, $C$, to analyze traffic patterns. $C(n)$ represents the rate of traffic through an intersection where $n$ is the number of observed vehicles in a specified time interval. What would be the most appropriate domain for the function?`,
    choices: [
      String.raw`$\{\ldots, -2, -1, 0, 1, 2, 3, \ldots\}$`,
      String.raw`$\{-2, -1, 0, 1, 2, 3\}$`,
      String.raw`$\left\{0, \tfrac{1}{2}, 1, 1\tfrac{1}{2}, 2, 2\tfrac{1}{2}\right\}$`,
      String.raw`$\{0, 1, 2, 3, \ldots\}$`,
    ],
    answer: 3,
    explanation: String.raw`The number of observed vehicles is a count that cannot be negative or fractional, so the appropriate domain is the whole numbers $\{0, 1, 2, 3, \ldots\}$.`,
  },
  {
    id: "fnb-mc-0814-q23",
    mode: "mc",
    standard: "AI-F.IF.5",
    topic: "Appropriate (restricted) domain in context",
    examCitation: "regents-algI-0814-q23",
    part: "I",
    credits: 2,
    prompt: String.raw`The function $h(t) = -16t^2 + 144$ represents the height, $h(t)$, in feet, of an object from the ground at $t$ seconds after it is dropped. A realistic domain for this function is`,
    choices: [
      String.raw`$-3 \le t \le 3$`,
      String.raw`$0 \le t \le 3$`,
      String.raw`$0 \le h(t) \le 144$`,
      "all real numbers",
    ],
    answer: 1,
    explanation: String.raw`Time starts at the moment of release ($t = 0$) and ends when the object lands. Setting $h(t) = 0$ gives $16t^2 = 144$, so $t^2 = 9$ and $t = 3$. A realistic domain is therefore $0 \le t \le 3$.`,
  },
  {
    id: "fnb-mc-0120-q21",
    mode: "mc",
    standard: "AI-F.IF.5",
    topic: "Appropriate (restricted) domain in context",
    examCitation: "regents-algI-0120-q21",
    part: "I",
    credits: 2,
    prompt: String.raw`A population of paramecia, $P$, can be modeled using the exponential function $P(t) = 3(2)^t$, where $t$ is the number of days since the population was first observed. Which domain is most appropriate to use to determine the population over the course of the first two weeks?`,
    choices: [
      String.raw`$t \le 0$`,
      String.raw`$t \le 2$`,
      String.raw`$0 \le t \le 2$`,
      String.raw`$0 \le t \le 14$`,
    ],
    answer: 3,
    explanation: String.raw`Two weeks is $14$ days, and $t$ is measured from the first observation ($t = 0$). So the appropriate domain is $0 \le t \le 14$.`,
  },

  // ---- AI-F.IF.9 — comparing two functions given in different forms ----
  {
    id: "fnb-mc-0819-q17",
    mode: "mc",
    standard: "AI-F.IF.9",
    topic: "Comparing functions — table vs. equation",
    examCitation: "regents-algI-0819-q17",
    part: "I",
    credits: 2,
    prompt: String.raw`The quadratic functions $r(x)$ and $q(x)$ are given below, with $q(x) = x^2 + 2x - 8$. The function with the smaller minimum value is`,
    figure: {
      kind: "table",
      headers: ["x", "r(x)"],
      rows: [[-4, -12], [-3, -15], [-2, -16], [-1, -15], [0, -12], [1, 7]],
      caption: "r(x)",
    },
    choices: [
      String.raw`$q(x)$, and the value is $-9$`,
      String.raw`$q(x)$, and the value is $-1$`,
      String.raw`$r(x)$, and the value is $-16$`,
      String.raw`$r(x)$, and the value is $-2$`,
    ],
    answer: 2,
    explanation: String.raw`From the table, $r(x)$ reaches its smallest value, $-16$, at $x = -2$. For $q(x) = x^2 + 2x - 8$ the vertex is at $x = -\tfrac{2}{2} = -1$, where $q(-1) = 1 - 2 - 8 = -9$. Since $-16 < -9$, $r(x)$ has the smaller minimum value, $-16$.`,
  },
  {
    id: "fnb-mc-0617-q17",
    mode: "mc",
    standard: "AI-F.IF.9",
    topic: "Comparing functions — table vs. equation",
    examCitation: "regents-algI-0617-q17",
    part: "I",
    credits: 2,
    prompt: String.raw`Which statement is true about the quadratic functions $g(x)$, shown in the table below, and $f(x) = (x - 3)^2 + 2$?`,
    figure: {
      kind: "table",
      headers: ["x", "g(x)"],
      rows: [[0, 4], [1, -1], [2, -4], [3, -5], [4, -4], [5, -1], [6, 4]],
    },
    choices: [
      "They have the same vertex.",
      "They have the same zeros.",
      "They have the same axis of symmetry.",
      "They intersect at two points.",
    ],
    answer: 2,
    explanation: String.raw`The table for $g(x)$ is symmetric about $x = 3$ (its lowest value, $-5$, occurs there), so its axis of symmetry is $x = 3$. The function $f(x) = (x - 3)^2 + 2$ has vertex $(3, 2)$, so its axis of symmetry is also $x = 3$. The vertices differ ($(3, -5)$ vs. $(3, 2)$), and $f$ has no real zeros, so the only true statement is that they share the axis of symmetry $x = 3$.`,
  },
  {
    id: "fnb-mc-0815-q21",
    mode: "mc",
    standard: "AI-F.IF.9",
    topic: "Comparing functions — equation vs. table",
    examCitation: "regents-algI-0815-q21",
    part: "I",
    credits: 2,
    prompt: String.raw`Given the quadratic functions $g(x) = -x^2 - x + 6$ and $n(x)$, shown in the table below. Which statement about these functions is true?`,
    figure: {
      kind: "table",
      headers: ["x", "n(x)"],
      rows: [[-3, -7], [-2, 0], [-1, 5], [0, 8], [1, 9], [2, 8], [3, 5], [4, 0], [5, -7]],
    },
    choices: [
      String.raw`Over the interval $-1 \le x \le 1$, the average rate of change for $n(x)$ is less than that for $g(x)$.`,
      String.raw`The $y$-intercept of $g(x)$ is greater than the $y$-intercept for $n(x)$.`,
      String.raw`The function $g(x)$ has a greater maximum value than $n(x)$.`,
      String.raw`The sum of the roots of $n(x) = 0$ is greater than the sum of the roots of $g(x) = 0$.`,
    ],
    answer: 3,
    explanation: String.raw`From the table, $n(x) = 0$ at $x = -2$ and $x = 4$, so its roots sum to $2$. For $g(x) = -x^2 - x + 6 = -(x + 3)(x - 2)$, the roots are $-3$ and $2$, summing to $-1$. Since $2 > -1$, the sum of the roots of $n$ is greater — choice (4). (The other statements are false: $n$'s rate of change over $[-1, 1]$ is $2$ vs. $-1$ for $g$; $n$'s $y$-intercept $8$ exceeds $g$'s $6$; and $n$'s maximum $9$ exceeds $g$'s $6.25$.)`,
  },

  // ——————————————— Parts II constructed-response (self-score) ———————————————
  // AI-F.IF.1 — explain/justify why a relation is or is not a function.

  {
    id: "fnb-cr-0115-q27",
    mode: "self-score",
    standard: "AI-F.IF.1",
    topic: "Identifying functions — explain (table)",
    examCitation: "regents-algI-0115-q27",
    part: "II",
    credits: 2,
    prompt: String.raw`A function is shown in the table below. If included in the table, which ordered pair, $(-4, 1)$ or $(1, -4)$, would result in a relation that is no longer a function? Explain your answer.`,
    figure: {
      kind: "table",
      headers: ["x", "f(x)"],
      rows: [[-4, 2], [-1, -4], [0, -2], [3, 16]],
    },
    answerSummary: String.raw`$(-4, 1)$`,
    modelSolution: String.raw`The table already pairs the input $-4$ with the output $2$. Adding $(-4, 1)$ would give the input $-4$ a second, different output, so that input would no longer have exactly one output — the relation would not be a function. Adding $(1, -4)$ is fine, because $1$ is a brand-new input that still has only one output.`,
    rubric: [
      { credits: 2, criteria: String.raw`$(-4, 1)$, and a correct explanation is given.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one conceptual error is made; OR $(-4, 1)$, but an incomplete or incorrect explanation is given.` },
      { credits: 0, criteria: String.raw`$(-4, 1)$, but no explanation is given; OR ${ZERO_OLD}` },
    ],
  },
  {
    id: "fnb-cr-0125-q27",
    mode: "self-score",
    standard: "AI-F.IF.1",
    topic: "Identifying functions — explain (table)",
    examCitation: "regents-algI-0125-q27",
    part: "II",
    credits: 2,
    prompt: String.raw`The function $f(x)$ is shown in the table below. State an appropriate value for $m$ in the table, so that $f(x)$ remains a function. Explain your reasoning.`,
    figure: {
      kind: "table",
      headers: ["x", "f(x)"],
      rows: [[0, 6], [3, 2], [2, 7], [6, 5], [1, 8], [5, 4], [4, 3], ["m", 9]],
    },
    answerSummary: String.raw`$m = 7$ (any value other than $0, 1, 2, 3, 4, 5, 6$).`,
    modelSolution: String.raw`The inputs already used are $0, 1, 2, 3, 4, 5,$ and $6$. For $f(x)$ to stay a function, the last input $m$ must not repeat any of these — a repeated input with a new output would give one input two outputs. So $m = 7$ works (and any value other than $0, 1, 2, 3, 4, 5, 6$ is acceptable).`,
    rubric: [
      { credits: 2, criteria: "A correct value for m is stated, and a correct explanation is written." },
      { credits: 1, criteria: "One conceptual error is made; OR a correct value for m is stated, but the explanation is missing, incomplete, or incorrect; OR a correct explanation is written, but no further correct work is shown." },
      { credits: 0, criteria: ZERO_NEW },
    ],
  },
  {
    id: "fnb-cr-0824-q27",
    mode: "self-score",
    standard: "AI-F.IF.1",
    topic: "Identifying functions — explain (table)",
    examCitation: "regents-algI-0824-q27",
    part: "II",
    credits: 2,
    prompt: String.raw`Explain why the relation shown in the table below is a function. Then complete a new table with values for both $x$ and $y$ so that the new relation is not a function.`,
    figure: {
      kind: "table",
      headers: ["x", "y"],
      rows: [[-1, 2], [0, 4], [1, 4], [2, 5]],
    },
    answerSummary: String.raw`It is a function because every $x$-value is paired with exactly one $y$-value. A non-function example: $\{(-1, 2), (0, 4), (1, 4), (1, 5)\}$.`,
    modelSolution: String.raw`The given relation is a function because the inputs $-1, 0, 1, 2$ are all different, so each input has exactly one output. (Two different inputs sharing the output $4$ is allowed.) To make a relation that is not a function, repeat an input with a different output — for example $\{(-1, 2), (0, 4), (1, 4), (1, 5)\}$: the input $1$ is now paired with both $4$ and $5$, so it is not a function.`,
    rubric: [
      { credits: 2, criteria: "A correct explanation is written, and correct values for x and y are written." },
      { credits: 1, criteria: "Appropriate work is shown, but one conceptual error is made; OR a correct explanation is written, but no further correct work is shown; OR correct values for x and y are written, but the explanation is missing, incomplete, or incorrect." },
      { credits: 0, criteria: ZERO_NEW },
    ],
  },
  {
    id: "fnb-cr-0624-q27",
    mode: "self-score",
    standard: "AI-F.IF.1",
    topic: "Identifying functions — explain (ordered pairs)",
    examCitation: "regents-algI-0624-q27",
    part: "II",
    credits: 2,
    prompt: String.raw`Given the relation $R = \{(-1, 1), (0, 3), (-2, -4), (x, 5)\}$. State a value for $x$ that will make this relation a function. Explain why your answer makes this a function.`,
    answerSummary: String.raw`$x$ may be any value other than $-2, -1, 0$ (for example, $x = 1$).`,
    modelSolution: String.raw`The inputs already used are $-1, 0,$ and $-2$. Choosing any of those for $x$ would pair one input with two different outputs, so $R$ would not be a function. Picking any other value — for example $x = 1$ — gives every input exactly one output, so $R$ is a function.`,
    rubric: [
      { credits: 2, criteria: "A correct value is stated, and a correct explanation is written." },
      { credits: 1, criteria: "One conceptual error is made; OR a correct value is stated, but the explanation is missing, incomplete, or incorrect; OR a correct explanation is written, but no further correct work is shown." },
      { credits: 0, criteria: ZERO_NEW },
    ],
  },
  {
    id: "fnb-cr-0614-q30",
    mode: "self-score",
    standard: "AI-F.IF.1",
    topic: "Identifying functions — domain, range, and ordered pairs",
    examCitation: "regents-algI-0614-q30",
    part: "II",
    credits: 2,
    prompt: String.raw`The function $f$ has a domain of $\{1, 3, 5, 7\}$ and a range of $\{2, 4, 6\}$. Could $f$ be represented by $\{(1, 2), (3, 4), (5, 6), (7, 2)\}$? Justify your answer.`,
    answerSummary: "Yes.",
    modelSolution: String.raw`Yes. Each input in the domain $\{1, 3, 5, 7\}$ appears exactly once and is paired with one output, so it is a function. The outputs used are $2, 4, 6,$ and $2$ — exactly the range $\{2, 4, 6\}$ (an output may be used more than once). So $f$ can be represented by this set of ordered pairs.`,
    rubric: [
      { credits: 2, criteria: "Yes, and a correct justification is given." },
      { credits: 1, criteria: "One conceptual error is made; OR Yes, but an incomplete or incorrect justification is given." },
      { credits: 0, criteria: String.raw`Yes, but no justification is given; OR ${ZERO_OLD}` },
    ],
  },
  {
    id: "fnb-cr-0117-q32",
    mode: "self-score",
    standard: "AI-F.IF.1",
    topic: "Identifying functions — the vertical-line test",
    examCitation: "regents-algI-0117-q32",
    part: "II",
    credits: 2,
    prompt: String.raw`Nora says that the graph of a circle is a function because she can trace the whole graph without picking up her pencil. Mia says that a circle graph is not a function because multiple values of $x$ map to the same $y$-value. Determine if either one is correct, and justify your answer completely.`,
    answerSummary: "Neither is correct.",
    modelSolution: String.raw`Neither student is correct. Nora is wrong: being able to trace a graph without lifting your pencil has nothing to do with being a function — a circle is not a function because it fails the vertical-line test (a single $x$-value maps to two different $y$-values). Mia has the right idea (the vertical-line test) but states it backwards: a circle is not a function because multiple values of $y$ map to the same $x$-value, not because multiple $x$-values map to the same $y$-value. So a circle is not a function, but neither student's reasoning is correct.`,
    rubric: [
      { credits: 2, criteria: "Neither, and a correct justification is given." },
      { credits: 1, criteria: "Appropriate work is shown, but one conceptual error is made; OR Neither, but an incomplete justification is given." },
      { credits: 0, criteria: String.raw`Neither is stated, but no further correct work is shown; OR ${ZERO_OLD}` },
    ],
  },
];

export default bank;
