// Authored Regents problem-bank — Functions: function notation / evaluation
// (AI-F.IF.2) and transforming a function's graph (AI-F.BF.3). Real released
// Next Generation Algebra I Regents questions, mined from the official NYSED
// administrations (via JMAP's by-standard archive) and cited to the exam +
// question number. Every MC answer is independently re-derived below; CR rubrics
// are verbatim from the NYSED Rating Guides (q30 piecewise = Jan '24) or the
// standardized 2-credit eval/solve template. SME-ratified. Math is inline LaTeX
// via String.raw.

import type { RegentsItem } from "@/lib/regents/bank";

const bank: RegentsItem[] = [
  // ——— Part I: evaluate a function (notation) ———
  {
    id: "func-mc-0619-q02",
    mode: "mc",
    standard: "AI-F.IF.2",
    topic: "Function notation — evaluate",
    examCitation: "regents-algI-0619-q02",
    part: "I",
    credits: 2,
    prompt: String.raw`If $f(x) = 4x + 5$, what is the value of $f(-3)$?`,
    choices: [String.raw`$-2$`, String.raw`$-7$`, String.raw`$17$`, String.raw`$4$`],
    answer: 1,
    explanation: String.raw`Substitute $x = -3$: $f(-3) = 4(-3) + 5 = -12 + 5 = -7$.`,
  },
  {
    id: "func-mc-0126-q14",
    mode: "mc",
    standard: "AI-F.IF.2",
    topic: "Function notation — evaluate",
    examCitation: "regents-algI-0126-q14",
    part: "I",
    credits: 2,
    prompt: String.raw`If $f(x) = \sqrt{x + 1} + 5$, what is the value of $f(3)$?`,
    choices: [String.raw`$9$`, String.raw`$7$`, String.raw`$3$`, String.raw`$10$`],
    answer: 1,
    explanation: String.raw`Substitute $x = 3$: $f(3) = \sqrt{3 + 1} + 5 = \sqrt{4} + 5 = 2 + 5 = 7$.`,
  },
  {
    id: "func-mc-0123-q04",
    mode: "mc",
    standard: "AI-F.IF.2",
    topic: "Function notation — evaluate (watch the signs)",
    examCitation: "regents-algI-0123-q04",
    part: "I",
    credits: 2,
    prompt: String.raw`Given $f(x) = -3x^2 + 10$, what is the value of $f(-2)$?`,
    choices: [String.raw`$-26$`, String.raw`$-2$`, String.raw`$22$`, String.raw`$46$`],
    answer: 1,
    explanation: String.raw`Square first, then multiply: $f(-2) = -3(-2)^2 + 10 = -3(4) + 10 = -12 + 10 = -2$. The exponent applies to $-2$ before the $-3$ multiplies.`,
  },
  {
    id: "func-mc-0124-q10",
    mode: "mc",
    standard: "AI-F.IF.2",
    topic: "Function notation — combine two functions",
    examCitation: "regents-algI-0124-q10",
    part: "I",
    credits: 2,
    prompt: String.raw`If $f(x) = x^2 + 2x + 1$ and $g(x) = 3x + 5$, then what is the value of $f(1) - g(3)$?`,
    choices: [String.raw`$10$`, String.raw`$8$`, String.raw`$-10$`, String.raw`$-8$`],
    answer: 2,
    explanation: String.raw`Evaluate each separately: $f(1) = 1 + 2 + 1 = 4$ and $g(3) = 9 + 5 = 14$. Then $f(1) - g(3) = 4 - 14 = -10$.`,
  },
  {
    id: "func-mc-0622-q02",
    mode: "mc",
    standard: "AI-F.IF.2",
    topic: "Function notation — which statement is true",
    examCitation: "regents-algI-0622-q02",
    part: "I",
    credits: 2,
    prompt: String.raw`Given $f(x) = 3x - 5$, which statement is true?`,
    choices: [String.raw`$f(0) = 0$`, String.raw`$f(3) = 4$`, String.raw`$f(4) = 3$`, String.raw`$f(5) = 0$`],
    answer: 1,
    explanation: String.raw`Test each: $f(0) = -5$, $f(3) = 9 - 5 = 4$ ✓, $f(4) = 7$, $f(5) = 10$. Only $f(3) = 4$ is true.`,
  },
  {
    id: "func-mc-0617-q05",
    mode: "mc",
    standard: "AI-F.IF.2",
    topic: "Function notation — evaluate (order of operations)",
    examCitation: "regents-algI-0617-q05",
    part: "I",
    credits: 2,
    prompt: String.raw`Lynn, Jude, and Anne were given the function $f(x) = -2x^2 + 32$ and asked to find $f(3)$. Lynn's answer was $14$, Jude's was $4$, and Anne's was $\pm 4$. Who is correct?`,
    choices: ["Lynn, only", "Jude, only", "Anne, only", "Both Lynn and Jude"],
    answer: 0,
    explanation: String.raw`$f(3) = -2(3)^2 + 32 = -2(9) + 32 = -18 + 32 = 14$. Only Lynn is correct. Jude and Anne mishandled the exponent and the sign.`,
  },

  {
    id: "func-mc-0822-q01",
    mode: "mc",
    standard: "AI-F.IF.2",
    topic: "Function notation — evaluate (rational rule)",
    examCitation: "regents-algI-0822-q01",
    part: "I",
    credits: 2,
    prompt: String.raw`If $f(x) = \dfrac{3x + 4}{2}$, then $f(8)$ is`,
    choices: [String.raw`$21$`, String.raw`$16$`, String.raw`$14$`, String.raw`$4$`],
    answer: 2,
    explanation: String.raw`Substitute $x = 8$ into the whole numerator before dividing: $f(8) = \dfrac{3(8) + 4}{2} = \dfrac{24 + 4}{2} = \dfrac{28}{2} = 14$.`,
  },
  {
    id: "func-mc-0621-q03",
    mode: "mc",
    standard: "AI-F.IF.2",
    topic: "Function notation — evaluate (watch the signs)",
    examCitation: "regents-algI-0621-q03",
    part: "I",
    credits: 2,
    prompt: String.raw`A function is defined as $K(x) = 2x^2 - 5x + 3$. The value of $K(-3)$ is`,
    choices: [String.raw`$54$`, String.raw`$36$`, String.raw`$0$`, String.raw`$-18$`],
    answer: 1,
    explanation: String.raw`Square first, and watch that $-5(-3) = +15$: $K(-3) = 2(-3)^2 - 5(-3) + 3 = 2(9) + 15 + 3 = 18 + 15 + 3 = 36$.`,
  },
  {
    id: "func-mc-0623-q11",
    mode: "mc",
    standard: "AI-F.IF.2",
    topic: "Function notation — evaluate (watch the signs)",
    examCitation: "regents-algI-0623-q11",
    part: "I",
    credits: 2,
    prompt: String.raw`If $g(x) = -x^2 - x + 5$, then $g(-4)$ is equal to`,
    choices: [String.raw`$-15$`, String.raw`$-7$`, String.raw`$17$`, String.raw`$25$`],
    answer: 1,
    explanation: String.raw`The leading minus applies after squaring: $g(-4) = -(-4)^2 - (-4) + 5 = -16 + 4 + 5 = -7$.`,
  },
  {
    id: "func-mc-0120-q01",
    mode: "mc",
    standard: "AI-F.IF.2",
    topic: "Function notation — evaluate (exponential rule)",
    examCitation: "regents-algI-0120-q01",
    part: "I",
    credits: 2,
    prompt: String.raw`If $f(x) = 2(3^x) + 1$, what is the value of $f(2)$?`,
    choices: [String.raw`$13$`, String.raw`$19$`, String.raw`$37$`, String.raw`$54$`],
    answer: 1,
    explanation: String.raw`Apply the exponent before multiplying: $f(2) = 2(3^2) + 1 = 2(9) + 1 = 18 + 1 = 19$.`,
  },

  // ——— Part I: transforming a function's graph ———
  {
    id: "func-mc-0626-q16",
    mode: "mc",
    standard: "AI-F.BF.3",
    topic: "Transforming a function's graph",
    examCitation: "regents-algI-0626-q16",
    part: "I",
    credits: 2,
    prompt: String.raw`The function $f(x)$ is shifted three units right and four units up. The result of this transformation is`,
    choices: [
      String.raw`$f(x - 3) + 4$`,
      String.raw`$f(x + 3) + 4$`,
      String.raw`$f(x + 4) - 3$`,
      String.raw`$f(x - 4) - 3$`,
    ],
    answer: 0,
    explanation: String.raw`A shift right by $3$ replaces $x$ with $x - 3$ (inside the function); a shift up by $4$ adds $4$ (outside). Together: $f(x - 3) + 4$.`,
  },
  {
    id: "func-mc-0126-q15",
    mode: "mc",
    standard: "AI-F.BF.3",
    topic: "Transforming a function's graph",
    examCitation: "regents-algI-0126-q15",
    part: "I",
    credits: 2,
    prompt: String.raw`Isabella wants to shift the graph of the function $f(x) = (x + 5)^2 - 2$ left 3 units. Which function represents the shifted graph?`,
    choices: [
      String.raw`$g(x) = (x + 2)^2 - 2$`,
      String.raw`$g(x) = (x + 8)^2 - 2$`,
      String.raw`$g(x) = (x + 5)^2 - 5$`,
      String.raw`$g(x) = (x + 5)^2 + 1$`,
    ],
    answer: 1,
    explanation: String.raw`Shifting left 3 replaces $x$ with $x + 3$: $f(x + 3) = ((x + 3) + 5)^2 - 2 = (x + 8)^2 - 2$.`,
  },
  {
    id: "func-mc-0625-q09",
    mode: "mc",
    standard: "AI-F.BF.3",
    topic: "Transforming a function's graph",
    examCitation: "regents-algI-0625-q09",
    part: "I",
    credits: 2,
    prompt: String.raw`Which function represents the graph of $w(x) = |x|$ shifted 2 units to the right?`,
    choices: [
      String.raw`$g(x) = |x + 2|$`,
      String.raw`$h(x) = |x - 2|$`,
      String.raw`$q(x) = |x| + 2$`,
      String.raw`$r(x) = |x| - 2$`,
    ],
    answer: 1,
    explanation: String.raw`A horizontal shift right by $2$ replaces $x$ with $x - 2$ inside the function: $|x - 2|$. (Adding outside, $|x| \pm 2$, would shift vertically.)`,
  },
  {
    id: "func-mc-0818-q08",
    mode: "mc",
    standard: "AI-F.BF.3",
    topic: "Transforming a function's graph",
    examCitation: "regents-algI-0818-q08",
    part: "I",
    credits: 2,
    prompt: String.raw`Compared to the graph of $f(x) = x^2$, the graph of $g(x) = (x - 2)^2 + 3$ is the result of translating $f(x)$`,
    choices: [
      "2 units up and 3 units right",
      "2 units down and 3 units up",
      "2 units right and 3 units up",
      "2 units left and 3 units right",
    ],
    answer: 2,
    explanation: String.raw`$(x - 2)$ shifts the graph $2$ units right; $+3$ shifts it $3$ units up. So $g$ is $f$ translated 2 right and 3 up.`,
  },
  {
    id: "func-mc-0623-q16",
    mode: "mc",
    standard: "AI-F.BF.3",
    topic: "Transforming a function's graph — stretch/compress",
    examCitation: "regents-algI-0623-q16",
    part: "I",
    credits: 2,
    prompt: String.raw`The function $f(x) = |x|$ is multiplied by $k$ to create the new function $g(x) = k|x|$. Which statement is true about the graphs of $f(x)$ and $g(x)$ if $k = \frac{1}{2}$?`,
    choices: [
      String.raw`$g(x)$ is a reflection of $f(x)$ over the $y$-axis.`,
      String.raw`$g(x)$ is a reflection of $f(x)$ over the $x$-axis.`,
      String.raw`$g(x)$ is wider than $f(x)$.`,
      String.raw`$g(x)$ is narrower than $f(x)$.`,
    ],
    answer: 2,
    explanation: String.raw`Multiplying by $0 < k < 1$ scales every output toward the $x$-axis (a vertical compression), which makes the V-shape open more — $g(x)$ is wider than $f(x)$.`,
  },

  {
    id: "func-mc-0621-q13",
    mode: "mc",
    standard: "AI-F.BF.3",
    topic: "Transforming a function's graph",
    examCitation: "regents-algI-0621-q13",
    part: "I",
    credits: 2,
    prompt: String.raw`If the parent function of $f(x)$ is $p(x) = x^2$, then the graph of the function $f(x) = (x - k)^2 + 5$, where $k > 0$, would be a shift of`,
    choices: [
      String.raw`$k$ units to the left and a move of $5$ units up`,
      String.raw`$k$ units to the left and a move of $5$ units down`,
      String.raw`$k$ units to the right and a move of $5$ units up`,
      String.raw`$k$ units to the right and a move of $5$ units down`,
    ],
    answer: 2,
    explanation: String.raw`Subtracting $k$ inside, $(x - k)^2$, shifts the graph $k$ units right (because $k > 0$); adding $5$ outside shifts it $5$ units up.`,
  },
  {
    id: "func-mc-0824-q11",
    mode: "mc",
    standard: "AI-F.BF.3",
    topic: "Transforming a function's graph",
    examCitation: "regents-algI-0824-q11",
    part: "I",
    credits: 2,
    prompt: String.raw`If $f(x) = x^2$, then which function represents a shift of the graph of $f(x)$ 4 units to the right and 3 units down?`,
    choices: [
      String.raw`$g(x) = (x + 4)^2 + 3$`,
      String.raw`$j(x) = (x + 4)^2 - 3$`,
      String.raw`$h(x) = (x - 4)^2 - 3$`,
      String.raw`$k(x) = (x - 4)^2 + 3$`,
    ],
    answer: 2,
    explanation: String.raw`A shift right by $4$ replaces $x$ with $x - 4$ inside the function; a shift down by $3$ subtracts $3$ outside: $(x - 4)^2 - 3$.`,
  },
  {
    id: "func-mc-0822-q11",
    mode: "mc",
    standard: "AI-F.BF.3",
    topic: "Transforming a function's graph — width/stretch",
    examCitation: "regents-algI-0822-q11",
    part: "I",
    credits: 2,
    prompt: String.raw`What would be the order of these quadratic functions when they are arranged from the narrowest graph to the widest graph?
$$f(x) = -5x^2 \qquad g(x) = 0.5x^2 \qquad h(x) = 3x^2$$`,
    choices: [
      String.raw`$f(x), g(x), h(x)$`,
      String.raw`$g(x), h(x), f(x)$`,
      String.raw`$h(x), f(x), g(x)$`,
      String.raw`$f(x), h(x), g(x)$`,
    ],
    answer: 3,
    explanation: String.raw`The larger the absolute value of the leading coefficient, the narrower the parabola. Since $|{-5}| = 5 > 3 > 0.5$, narrowest to widest is $f(x), h(x), g(x)$.`,
  },
  {
    id: "func-mc-0118-q19",
    mode: "mc",
    standard: "AI-F.BF.3",
    topic: "Transforming a function's graph",
    examCitation: "regents-algI-0118-q19",
    part: "I",
    credits: 2,
    prompt: String.raw`If the original function $f(x) = 2x^2 - 1$ is shifted to the left 3 units to make the function $g(x)$, which expression would represent $g(x)$?`,
    choices: [
      String.raw`$2(x - 3)^2 - 1$`,
      String.raw`$2(x + 3)^2 - 1$`,
      String.raw`$2x^2 + 2$`,
      String.raw`$2x^2 - 4$`,
    ],
    answer: 1,
    explanation: String.raw`Shifting left 3 replaces $x$ with $x + 3$ inside: $g(x) = 2(x + 3)^2 - 1$. The vertical stretch ($2$) and the $-1$ are unchanged.`,
  },
  {
    id: "func-mc-0115-q12",
    mode: "mc",
    standard: "AI-F.BF.3",
    topic: "Transforming a function's graph — stretch and shift",
    examCitation: "regents-algI-0115-q12",
    part: "I",
    credits: 2,
    prompt: String.raw`How does the graph of $f(x) = 3(x - 2)^2 + 1$ compare to the graph of $g(x) = x^2$?`,
    choices: [
      String.raw`The graph of $f(x)$ is wider than the graph of $g(x)$, and its vertex is moved to the left 2 units and up 1 unit.`,
      String.raw`The graph of $f(x)$ is narrower than the graph of $g(x)$, and its vertex is moved to the right 2 units and up 1 unit.`,
      String.raw`The graph of $f(x)$ is narrower than the graph of $g(x)$, and its vertex is moved to the left 2 units and up 1 unit.`,
      String.raw`The graph of $f(x)$ is wider than the graph of $g(x)$, and its vertex is moved to the right 2 units and up 1 unit.`,
    ],
    answer: 1,
    explanation: String.raw`The factor $3$ (greater than $1$) makes the parabola narrower; $(x - 2)$ moves the vertex right 2, and $+1$ moves it up 1.`,
  },

  // ——— Part II: constructed response (self-score) ———
  {
    id: "func-cr-0624-q26",
    mode: "self-score",
    standard: "AI-F.IF.2",
    topic: "Function notation — evaluate",
    examCitation: "regents-algI-0624-q26",
    part: "II",
    credits: 2,
    prompt: String.raw`Given $g(x) = x^3 + 2x^2 - x$, evaluate $g(-3)$.`,
    answerSummary: String.raw`$g(-3) = -6$`,
    modelSolution: String.raw`Substitute $x = -3$: $g(-3) = (-3)^3 + 2(-3)^2 - (-3) = -27 + 2(9) + 3 = -27 + 18 + 3 = -6$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$-6$, with correct work shown.` },
      { credits: 1, criteria: "Appropriate work, but one computational error; OR one conceptual error; OR the correct answer with no work shown." },
      { credits: 0, criteria: "A response with no relevant course-level work." },
    ],
  },
  {
    id: "func-cr-0819-q25",
    mode: "self-score",
    standard: "AI-F.IF.2",
    topic: "Function notation — evaluate",
    examCitation: "regents-algI-0819-q25",
    part: "II",
    credits: 2,
    prompt: String.raw`If $g(x) = -4x^2 - 3x + 2$, determine $g(-2)$.`,
    answerSummary: String.raw`$g(-2) = -8$`,
    modelSolution: String.raw`Substitute $x = -2$: $g(-2) = -4(-2)^2 - 3(-2) + 2 = -4(4) + 6 + 2 = -16 + 6 + 2 = -8$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$-8$, with correct work shown.` },
      { credits: 1, criteria: "Appropriate work, but one computational error; OR one conceptual error; OR the correct answer with no work shown." },
      { credits: 0, criteria: "A response with no relevant course-level work." },
    ],
  },
  {
    id: "func-cr-0125-q29",
    mode: "self-score",
    standard: "AI-F.IF.2",
    topic: "Function notation — solve for the input",
    examCitation: "regents-algI-0125-q29",
    part: "II",
    credits: 2,
    prompt: String.raw`If $f(x) = \dfrac{-3x - 5}{2}$, algebraically determine the value of $x$ when $f(x) = -22$.`,
    answerSummary: String.raw`$x = 13$`,
    modelSolution: String.raw`Set the function equal to $-22$ and solve: $-22 = \dfrac{-3x - 5}{2}$. Multiply both sides by $2$: $-44 = -3x - 5$. Add $5$: $-39 = -3x$. Divide by $-3$: $x = 13$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$x = 13$, and correct algebraic work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made; OR one conceptual error is made; OR $x = 13$ is found by a method other than algebraic; OR $x = 13$ with no work shown.` },
      { credits: 0, criteria: "A response with no relevant course-level work, or a correct answer obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "func-cr-0124-q30",
    mode: "self-score",
    standard: "AI-F.IF.2",
    topic: "Piecewise functions — evaluate and justify",
    examCitation: "regents-algI-0124-q30",
    part: "II",
    credits: 2,
    prompt: String.raw`The piecewise function $f(x)$ is given below.
$$f(x) = \begin{cases} 2x - 3, & x > 3 \\ -x^2 + 15, & x \le 3 \end{cases}$$
State the value of $f(3)$. Justify your answer.`,
    answerSummary: String.raw`$f(3) = 6$`,
    modelSolution: String.raw`Because $3 \le 3$, the input $x = 3$ falls in the second piece, $-x^2 + 15$ (the rule whose condition includes $x = 3$). So $f(3) = -(3)^2 + 15 = -9 + 15 = 6$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$6$, and a correct justification is given.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made; OR one conceptual error is made; OR $6$ is stated, but the justification is missing or incorrect.` },
      { credits: 0, criteria: "A response with no relevant course-level work, or a correct answer obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "func-cr-0824-q26",
    mode: "self-score",
    standard: "AI-F.IF.2",
    topic: "Function notation — evaluate (rational rule)",
    examCitation: "regents-algI-0824-q26",
    part: "II",
    credits: 2,
    prompt: String.raw`If $f(x) = \dfrac{30x^2}{x + 2}$, determine the value of $f\left(\frac{1}{2}\right)$.`,
    answerSummary: String.raw`$f\left(\frac{1}{2}\right) = 3$`,
    modelSolution: String.raw`Substitute $x = \frac{1}{2}$: $f\left(\tfrac{1}{2}\right) = \dfrac{30\left(\frac{1}{2}\right)^2}{\frac{1}{2} + 2} = \dfrac{30 \cdot \frac{1}{4}}{\frac{5}{2}} = \dfrac{\frac{30}{4}}{\frac{5}{2}} = \dfrac{15}{2} \cdot \dfrac{2}{5} = 3$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$3$, and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made; OR appropriate work is shown, but one conceptual error is made; OR $3$, but no work is shown.` },
      { credits: 0, criteria: "A zero response does not contain enough relevant course-level work to receive any credit, does not satisfy the criteria for one or more credits, or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "func-cr-0622-q26",
    mode: "self-score",
    standard: "AI-F.BF.3",
    topic: "Transforming a function's graph — describe",
    examCitation: "regents-algI-0622-q26",
    part: "II",
    credits: 2,
    prompt: String.raw`Describe the transformations performed on the graph of $f(x) = x^2$ to obtain the graph of $g(x)$ when $g(x) = (x - 3)^2 - 4$.`,
    answerSummary: String.raw`Shift right $3$ units and down $4$ units.`,
    modelSolution: String.raw`Inside the function, $x$ is replaced by $x - 3$, which shifts the graph $3$ units to the right. Outside, $4$ is subtracted, which shifts the graph $4$ units down. So $g(x)$ is $f(x)$ shifted right $3$ and down $4$.`,
    rubric: [
      { credits: 2, criteria: "It shifts to the right 3 and down 4." },
      { credits: 1, criteria: "One conceptual error is made; OR only one transformation is described correctly." },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "func-cr-0822-q30",
    mode: "self-score",
    standard: "AI-F.BF.3",
    topic: "Transforming a function's graph — describe",
    examCitation: "regents-algI-0822-q30",
    part: "II",
    credits: 2,
    prompt: String.raw`A student is given the functions $f(x) = (x + 1)^2$ and $g(x) = (x + 3)^2$. Describe the transformation that maps $f(x)$ onto $g(x)$.`,
    answerSummary: String.raw`A shift of $2$ units to the left.`,
    modelSolution: String.raw`The vertex of $f(x)$ is at $x = -1$ and the vertex of $g(x)$ is at $x = -3$. Going from $-1$ to $-3$ moves the graph $2$ units to the left. (Equivalently, $g(x) = f(x + 2)$, a shift left $2$.)`,
    rubric: [
      { credits: 2, criteria: "A shift of 2 to the left is stated." },
      { credits: 1, criteria: "One computational error is made; OR one conceptual error is made; OR an incomplete description is written." },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "func-cr-0617-q32",
    mode: "self-score",
    standard: "AI-F.BF.3",
    topic: "Transforming a function's graph — describe",
    examCitation: "regents-algI-0617-q32",
    part: "II",
    credits: 2,
    prompt: String.raw`Describe the effect that each transformation below has on the function $f(x) = |x|$, where $a > 0$.
$$g(x) = |x - a| \qquad h(x) = |x| - a$$`,
    answerSummary: String.raw`$g(x)$ is $f(x)$ shifted right by $a$; $h(x)$ is $f(x)$ shifted down by $a$.`,
    modelSolution: String.raw`In $g(x) = |x - a|$ the change is inside the absolute value, so the graph shifts horizontally $a$ units to the right. In $h(x) = |x| - a$ the change is outside, so the graph shifts vertically $a$ units down.`,
    rubric: [
      { credits: 2, criteria: String.raw`$f(x)$ is shifted right by $a$ and $f(x)$ is shifted down by $a$ are stated.` },
      { credits: 1, criteria: "Appropriate work is shown, but one conceptual error is made; OR only one shift is stated correctly." },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "func-cr-0614-q28",
    mode: "self-score",
    standard: "AI-F.BF.3",
    topic: "Transforming a function's graph — vertex of a translation",
    examCitation: "regents-algI-0614-q28",
    part: "II",
    credits: 2,
    prompt: String.raw`The vertex of the parabola represented by $f(x) = x^2 - 4x + 3$ has coordinates $(2, -1)$. Find the coordinates of the vertex of the parabola defined by $g(x) = f(x - 2)$. Explain how you arrived at your answer.`,
    answerSummary: String.raw`$(4, -1)$`,
    modelSolution: String.raw`Replacing $x$ with $x - 2$ produces a horizontal shift of $2$ units to the right, with no vertical change. Moving the vertex $(2, -1)$ right $2$ units gives $(4, -1)$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$(4, -1)$, and a correct explanation is given.` },
      { credits: 1, criteria: String.raw`One computational error is made; OR one conceptual error is made; OR $(4, -1)$, but no explanation or an incorrect explanation is given.` },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "func-cr-0615-q34",
    mode: "self-score",
    standard: "AI-F.IF.2",
    topic: "Piecewise functions — evaluate and solve (application)",
    examCitation: "regents-algI-0615-q34",
    part: "III",
    credits: 4,
    prompt: String.raw`The equation to determine the weekly earnings of an employee at The Hamburger Shack is given by $w(x)$, where $x$ is the number of hours worked.
$$w(x) = \begin{cases} 10x, & 0 \le x \le 40 \\ 15(x - 40) + 400, & x > 40 \end{cases}$$
Determine the difference in salary, in dollars, for an employee who works 52 hours versus one who works 38 hours. Determine the number of hours an employee must work in order to earn \$445. Explain how you arrived at this answer.`,
    answerSummary: String.raw`The difference is \$200; an employee must work $43$ hours to earn \$445.`,
    modelSolution: String.raw`For $52$ hours, use the $x > 40$ rule: $w(52) = 15(52 - 40) + 400 = 15(12) + 400 = 580$. For $38$ hours, use the $0 \le x \le 40$ rule: $w(38) = 10(38) = 380$. The difference is $w(52) - w(38) = 580 - 380 = 200$ dollars.
To earn \$445: since $445 > 400$, the hours must satisfy $x > 40$, so solve $15(x - 40) + 400 = 445$. Then $15(x - 40) = 45$, so $x - 40 = 3$, giving $x = 43$ hours.`,
    rubric: [
      { credits: 4, criteria: "200, and correct work is shown, 43 and a correct explanation is given." },
      { credits: 3, criteria: "Appropriate work is shown, but one computational error is made; OR appropriate work is shown, but the explanation is incomplete, incorrect, or missing." },
      { credits: 2, criteria: "Appropriate work is shown, but two or more computational errors are made; OR appropriate work is shown, but one conceptual error is made; OR appropriate work is shown to find 200, but no further correct work is shown; OR 200 and 43, but no work is shown." },
      { credits: 1, criteria: "Appropriate work is shown, but one computational and one conceptual error are made; OR 200 or 43, but no work is shown." },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
];

export default bank;
