// Authored Regents problem-bank — Linear Inequalities (AI-A.REI.3). Real released
// Next Generation Algebra I Regents questions, mined from the official NYSED
// administrations (via JMAP's by-standard archive) and cited to the exam +
// question number. Every MC answer is independently re-derived below; CR rubrics
// follow the standardized NYSED 2-credit "solve algebraically" template (verbatim
// from the June 2024 Rating Guide for q25, identical boilerplate for the rest).
// SME-ratified. Math is inline LaTeX via String.raw.
//
// The "which graph" MC items carry NUMBER-LINE figures as the four choices,
// transcribed from the source PDF (ray direction / open dot is vector art).

import type { RegentsItem } from "@/lib/regents/bank";

const bank: RegentsItem[] = [
  // ——— Part I: solve algebraically, multiple choice (easy → hard) ———
  {
    id: "ineq-mc-0816-q07",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving a linear inequality",
    examCitation: "regents-algI-0816-q07",
    part: "I",
    credits: 2,
    prompt: String.raw`What is the solution to $2h + 8 > 3h - 6$?`,
    choices: [String.raw`$h < 14$`, String.raw`$h > 14$`, String.raw`$h < \frac{14}{5}$`, String.raw`$h > \frac{14}{5}$`],
    answer: 0,
    explanation: String.raw`Collect the variable on one side: $2h + 8 > 3h - 6$ gives $8 + 6 > 3h - 2h$, so $14 > h$ — that is, $h < 14$.`,
  },
  {
    id: "ineq-mc-0618-q01",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving a linear inequality",
    examCitation: "regents-algI-0618-q01",
    part: "I",
    credits: 2,
    prompt: String.raw`The solution to $4p + 2 < 2(p + 5)$ is`,
    choices: [String.raw`$p > -6$`, String.raw`$p < -6$`, String.raw`$p > 4$`, String.raw`$p < 4$`],
    answer: 3,
    explanation: String.raw`Distribute: $4p + 2 < 2p + 10$. Then $2p < 8$, so $p < 4$.`,
  },
  {
    id: "ineq-mc-0616-q09",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving a linear inequality",
    examCitation: "regents-algI-0616-q09",
    part: "I",
    credits: 2,
    prompt: String.raw`When $3x + 2 \le 5(x - 4)$ is solved for $x$, the solution is`,
    choices: [String.raw`$x \le 3$`, String.raw`$x \ge 3$`, String.raw`$x \le -11$`, String.raw`$x \ge 11$`],
    answer: 3,
    explanation: String.raw`Distribute: $3x + 2 \le 5x - 20$. Then $2 + 20 \le 5x - 3x$, so $22 \le 2x$ and $11 \le x$ — that is, $x \ge 11$.`,
  },
  {
    id: "ineq-mc-0622-q07",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving a linear inequality",
    examCitation: "regents-algI-0622-q07",
    part: "I",
    credits: 2,
    prompt: String.raw`What is the solution to $\frac{3}{2}b + 5 < 17$?`,
    choices: [String.raw`$b < 8$`, String.raw`$b > 8$`, String.raw`$b < 18$`, String.raw`$b > 18$`],
    answer: 0,
    explanation: String.raw`Subtract 5: $\frac{3}{2}b < 12$. Multiply by $\frac{2}{3}$ (positive, so the sign stays): $b < 12 \cdot \frac{2}{3} = 8$.`,
  },
  {
    id: "ineq-mc-0823-q10",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving a linear inequality",
    examCitation: "regents-algI-0823-q10",
    part: "I",
    credits: 2,
    prompt: String.raw`What is the solution to $-3(x - 6) > 2x - 2$?`,
    choices: [String.raw`$x > 4$`, String.raw`$x < 4$`, String.raw`$x > -16$`, String.raw`$x < -16$`],
    answer: 1,
    explanation: String.raw`Distribute: $-3x + 18 > 2x - 2$. Collect: $18 + 2 > 2x + 3x$, so $20 > 5x$ and $4 > x$ — that is, $x < 4$.`,
  },
  {
    id: "ineq-mc-0824-q13",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving a linear inequality — reverse the sign",
    examCitation: "regents-algI-0824-q13",
    part: "I",
    credits: 2,
    prompt: String.raw`What is the solution to the inequality $2m - 4 \le 3(2m + 4)$?`,
    choices: [String.raw`$m \le -2$`, String.raw`$m \ge -2$`, String.raw`$m \le -4$`, String.raw`$m \ge -4$`],
    answer: 3,
    explanation: String.raw`Distribute: $2m - 4 \le 6m + 12$. Subtract $6m$: $-4m - 4 \le 12$, so $-4m \le 16$. Divide by $-4$ and **reverse** the inequality: $m \ge -4$.`,
  },
  {
    id: "ineq-mc-0124-q18",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving a linear inequality — reverse the sign",
    examCitation: "regents-algI-0124-q18",
    part: "I",
    credits: 2,
    prompt: String.raw`What is the solution to the inequality $2x - 7 > 2.5x + 3$?`,
    choices: [String.raw`$x > -5$`, String.raw`$x < -5$`, String.raw`$x > -20$`, String.raw`$x < -20$`],
    answer: 3,
    explanation: String.raw`Subtract $2.5x$: $-0.5x - 7 > 3$, so $-0.5x > 10$. Divide by $-0.5$ and **reverse** the inequality: $x < -20$.`,
  },
  {
    id: "ineq-mc-0115-q07",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving a linear inequality — fractions",
    examCitation: "regents-algI-0115-q07",
    part: "I",
    credits: 2,
    prompt: String.raw`The inequality $7 - \frac{2}{3}x < x - 8$ is equivalent to`,
    choices: [String.raw`$x > 9$`, String.raw`$x > -\frac{3}{5}$`, String.raw`$x < 9$`, String.raw`$x < -\frac{3}{5}$`],
    answer: 0,
    explanation: String.raw`Add $\frac{2}{3}x$ and $8$ to both sides: $15 < x + \frac{2}{3}x = \frac{5}{3}x$. Multiply by $\frac{3}{5}$ (positive, sign stays): $9 < x$ — that is, $x > 9$.`,
  },
  {
    id: "ineq-mc-0817-q11",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving a linear inequality — fractions, reverse the sign",
    examCitation: "regents-algI-0817-q11",
    part: "I",
    credits: 2,
    prompt: String.raw`What is the solution to the inequality $2 + \frac{4}{9}x \ge 4 + x$?`,
    choices: [String.raw`$x \le -\frac{18}{5}$`, String.raw`$x \ge -\frac{18}{5}$`, String.raw`$x \le \frac{54}{5}$`, String.raw`$x \ge \frac{54}{5}$`],
    answer: 0,
    explanation: String.raw`Subtract $4$ and $x$ from both sides: $-2 \ge x - \frac{4}{9}x = \frac{5}{9}x$. Multiply by $\frac{9}{5}$ (positive, sign stays): $-\frac{18}{5} \ge x$ — that is, $x \le -\frac{18}{5}$.`,
  },
  {
    id: "ineq-mc-0623-q22",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving a linear inequality — fractions, reverse the sign",
    examCitation: "regents-algI-0623-q22",
    part: "I",
    credits: 2,
    prompt: String.raw`What is the solution to the inequality $4 - \frac{2}{5}x \ge \frac{1}{3}x + 15$?`,
    choices: [String.raw`$x \le 11$`, String.raw`$x \ge 11$`, String.raw`$x \le -15$`, String.raw`$x \ge -15$`],
    answer: 2,
    explanation: String.raw`Subtract $4$: $-\frac{2}{5}x \ge \frac{1}{3}x + 11$. Subtract $\frac{1}{3}x$: $-\frac{6}{15}x - \frac{5}{15}x = -\frac{11}{15}x \ge 11$. Multiply by $-\frac{15}{11}$ and **reverse** the inequality: $x \le -15$.`,
  },
  {
    id: "ineq-mc-0619-q13",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving a linear inequality for a variable",
    examCitation: "regents-algI-0619-q13",
    part: "I",
    credits: 2,
    prompt: String.raw`When $3a + 7b > 2a - 8b$ is solved for $a$, the result is`,
    choices: [String.raw`$a > -b$`, String.raw`$a < -b$`, String.raw`$a < -15b$`, String.raw`$a > -15b$`],
    answer: 3,
    explanation: String.raw`Subtract $2a$ from both sides: $a + 7b > -8b$. Subtract $7b$: $a > -8b - 7b = -15b$.`,
  },
  {
    id: "ineq-mc-0120-q03",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving a linear inequality — interpret the solution set",
    examCitation: "regents-algI-0120-q03",
    part: "I",
    credits: 2,
    prompt: String.raw`Given $7x + 2 \ge 58$, which number is *not* in the solution set?`,
    choices: [String.raw`$6$`, String.raw`$8$`, String.raw`$10$`, String.raw`$12$`],
    answer: 0,
    explanation: String.raw`Subtract $2$: $7x \ge 56$. Divide by $7$ (positive, sign stays): $x \ge 8$. Of the choices, only $6$ is less than $8$, so $6$ is not in the solution set.`,
  },
  {
    id: "ineq-mc-0617-q13",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving a linear inequality — interpret, reverse the sign",
    examCitation: "regents-algI-0617-q13",
    part: "I",
    credits: 2,
    prompt: String.raw`Which value would be a solution for $x$ in the inequality $47 - 4x < 7$?`,
    choices: [String.raw`$-13$`, String.raw`$-10$`, String.raw`$10$`, String.raw`$11$`],
    answer: 3,
    explanation: String.raw`Subtract $47$: $-4x < -40$. Divide by $-4$ and **reverse** the inequality: $x > 10$. Of the choices, only $11$ is greater than $10$.`,
  },
  {
    id: "ineq-mc-0118-q17",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving a linear inequality — solution set over a domain",
    examCitation: "regents-algI-0118-q17",
    part: "I",
    credits: 2,
    prompt: String.raw`Given the set $\{x \mid -2 \le x \le 2, \text{ where } x \text{ is an integer}\}$, what is the solution of $-2(x - 5) < 10$?`,
    choices: [String.raw`$\{0, 1, 2\}$`, String.raw`$\{1, 2\}$`, String.raw`$\{-2, -1, 0\}$`, String.raw`$\{-2, -1\}$`],
    answer: 1,
    explanation: String.raw`Distribute: $-2x + 10 < 10$, so $-2x < 0$. Divide by $-2$ and **reverse** the inequality: $x > 0$. The integers in the set that are greater than $0$ are $1$ and $2$.`,
  },
  {
    id: "ineq-mc-0615-q24",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Modeling with a linear inequality",
    examCitation: "regents-algI-0615-q24",
    part: "I",
    credits: 2,
    prompt: String.raw`Natasha is planning a school celebration and wants to have live music and food for everyone who attends. She has found a band that will charge her \$750 and a caterer who will provide snacks and drinks for \$2.25 per person. If her goal is to keep the average cost per person between \$2.75 and \$3.25, how many people, $p$, must attend?`,
    choices: [String.raw`$225 < p < 325$`, String.raw`$325 < p < 750$`, String.raw`$500 < p < 1000$`, String.raw`$750 < p < 1500$`],
    answer: 3,
    explanation: String.raw`The average cost per person is $\frac{750 + 2.25p}{p}$, and it must satisfy $2.75 < \frac{750 + 2.25p}{p} < 3.25$. From $\frac{750 + 2.25p}{p} < 3.25$: $750 + 2.25p < 3.25p$, so $750 < p$. From $\frac{750 + 2.25p}{p} > 2.75$: $750 + 2.25p > 2.75p$, so $750 > 0.5p$ and $p < 1500$. Thus $750 < p < 1500$.`,
  },
  {
    id: "ineq-mc-0619-q10",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Modeling with a compound inequality",
    examCitation: "regents-algI-0619-q10",
    part: "I",
    credits: 2,
    prompt: String.raw`David wanted to go on an amusement park ride. A sign posted at the entrance read "You must be greater than 42 inches tall and no more than 57 inches tall for this ride." Which inequality would model the height, $x$, required for this amusement park ride?`,
    choices: [String.raw`$42 < x \le 57$`, String.raw`$42 \le x \le 57$`, String.raw`$42 < x \text{ or } x \le 57$`, String.raw`$42 < x \text{ or } x \ge 57$`],
    answer: 0,
    explanation: String.raw`"Greater than 42 inches" means $x > 42$ (strict, so an open boundary). "No more than 57 inches" means $x \le 57$ (at most 57, included). Both must hold at once, so $42 < x \le 57$.`,
  },
  {
    id: "ineq-mc-0616-q07",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Modeling with a compound inequality — average",
    examCitation: "regents-algI-0616-q07",
    part: "I",
    credits: 2,
    prompt: String.raw`The acidity in a swimming pool is considered normal if the average of three pH readings, $p$, is defined such that $7.0 < p < 7.8$. If the first two readings are 7.2 and 7.6, which value for the third reading will result in an overall rating of normal?`,
    choices: [String.raw`$6.2$`, String.raw`$7.3$`, String.raw`$8.6$`, String.raw`$8.8$`],
    answer: 1,
    explanation: String.raw`The average is $\frac{7.2 + 7.6 + x}{3} = \frac{14.8 + x}{3}$. Require $7.0 < \frac{14.8 + x}{3} < 7.8$, so $21 < 14.8 + x < 23.4$ and $6.2 < x < 8.6$. Of the choices, only $7.3$ lies strictly between $6.2$ and $8.6$.`,
  },
  // ——— Part I: "which graph" with number-line choices ———
  {
    id: "ineq-mc-0126-q11",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving a linear inequality — graph the solution",
    examCitation: "regents-algI-0126-q11",
    part: "I",
    credits: 2,
    prompt: String.raw`Which graph represents the solution to the inequality $4 + 3x > 9 - 7x$?`,
    choices: ["Graph (1)", "Graph (2)", "Graph (3)", "Graph (4)"],
    choiceFigures: [
      { kind: "number-line", min: 0, max: 3, step: 0.5, ray: { at: 2, dir: "left", closed: false } },
      { kind: "number-line", min: 0, max: 3, step: 0.5, ray: { at: 2, dir: "right", closed: false } },
      { kind: "number-line", min: 0, max: 3, step: 0.5, ray: { at: 0.5, dir: "right", closed: false } },
      { kind: "number-line", min: 0, max: 3, step: 0.5, ray: { at: 0.5, dir: "left", closed: false } },
    ],
    answer: 2,
    explanation: String.raw`Solve: $4 + 3x > 9 - 7x$ gives $10x > 5$, so $x > \frac{1}{2}$. Because the inequality is strict, the endpoint at $\frac{1}{2}$ is an open circle and the graph is shaded to the right — graph (3).`,
  },
  {
    id: "ineq-mc-0125-q22",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving a linear inequality — graph the solution, reverse the sign",
    examCitation: "regents-algI-0125-q22",
    part: "I",
    credits: 2,
    prompt: String.raw`Which graph is the solution to the inequality $6.4 - 4x \ge -2.8$?`,
    choices: ["Graph (1)", "Graph (2)", "Graph (3)", "Graph (4)"],
    choiceFigures: [
      { kind: "number-line", min: 2.1, max: 2.5, step: 0.1, ray: { at: 2.3, dir: "right", closed: false } },
      { kind: "number-line", min: 2.1, max: 2.5, step: 0.1, ray: { at: 2.3, dir: "right", closed: true } },
      { kind: "number-line", min: 2.1, max: 2.5, step: 0.1, ray: { at: 2.3, dir: "left", closed: false } },
      { kind: "number-line", min: 2.1, max: 2.5, step: 0.1, ray: { at: 2.3, dir: "left", closed: true } },
    ],
    answer: 3,
    explanation: String.raw`Solve: $6.4 - 4x \ge -2.8$ gives $-4x \ge -9.2$. Divide by $-4$ and **reverse** the inequality: $x \le 2.3$. Because of the "$\le$", the endpoint at $2.3$ is a closed (filled) dot and the graph is shaded to the left — graph (4).`,
  },

  // ——— Part II: solve algebraically, constructed response (self-score) ———
  {
    id: "ineq-cr-0624-q25",
    mode: "self-score",
    standard: "AI-A.REI.3",
    topic: "Solve a linear inequality algebraically",
    examCitation: "regents-algI-0624-q25",
    part: "II",
    credits: 2,
    prompt: String.raw`Solve $5(x - 2) \le 3x + 20$ algebraically.`,
    answerSummary: String.raw`$x \le 15$`,
    modelSolution: String.raw`Distribute: $5x - 10 \le 3x + 20$. Subtract $3x$ from both sides: $2x - 10 \le 20$. Add $10$: $2x \le 30$. Divide by $2$ (positive, sign stays): $x \le 15$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$x \le 15$, and correct algebraic work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made; OR one conceptual error is made; OR $x \le 15$ is found by a method other than algebraic; OR $x \le 15$ with no work shown.` },
      { credits: 0, criteria: "A response with no relevant course-level work, or a correct answer obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "ineq-cr-0625-q26",
    mode: "self-score",
    standard: "AI-A.REI.3",
    topic: "Solve a linear inequality algebraically — reverse the sign",
    examCitation: "regents-algI-0625-q26",
    part: "II",
    credits: 2,
    prompt: String.raw`Solve the inequality for $y$:  $5(2 - y) > -11y - 8$`,
    answerSummary: String.raw`$y > -3$`,
    modelSolution: String.raw`Distribute: $10 - 5y > -11y - 8$. Add $11y$ to both sides: $10 + 6y > -8$. Subtract $10$: $6y > -18$. Divide by $6$ (positive, sign stays): $y > -3$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$y > -3$, and correct algebraic work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made; OR one conceptual error is made; OR $y > -3$ is found by a method other than algebraic; OR $y > -3$ with no work shown.` },
      { credits: 0, criteria: "A response with no relevant course-level work, or a correct answer obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "ineq-cr-0123-q27",
    mode: "self-score",
    standard: "AI-A.REI.3",
    topic: "Solve a linear inequality algebraically — reverse the sign",
    examCitation: "regents-algI-0123-q27",
    part: "II",
    credits: 2,
    prompt: String.raw`Solve the inequality $-\frac{2}{3}x + 6 > -12$ algebraically for $x$.`,
    answerSummary: String.raw`$x < 27$`,
    modelSolution: String.raw`Subtract $6$ from both sides: $-\frac{2}{3}x > -18$. Multiply both sides by $-\frac{3}{2}$ and **reverse** the inequality (multiplying by a negative): $x < -18 \cdot \left(-\frac{3}{2}\right) = 27$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$x < 27$, and correct algebraic work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made; OR one conceptual error is made; OR $x < 27$ is found by a method other than algebraic; OR $x < 27$ with no work shown.` },
      { credits: 0, criteria: "A response with no relevant course-level work, or a correct answer obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "ineq-cr-0119-q25",
    mode: "self-score",
    standard: "AI-A.REI.3",
    topic: "Solve a linear inequality algebraically — modeling",
    examCitation: "regents-algI-0119-q25",
    part: "II",
    credits: 2,
    prompt: String.raw`Solve algebraically for $x$:  $3600 + 1.02x < 2000 + 1.04x$`,
    answerSummary: String.raw`$x > 80{,}000$`,
    modelSolution: String.raw`Subtract $2000$ and $1.02x$ from both sides: $1600 < 0.02x$. Divide by $0.02$ (positive, sign stays): $80{,}000 < x$ — that is, $x > 80{,}000$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$x > 80{,}000$, and correct algebraic work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made; OR one conceptual error is made; OR $x > 80{,}000$ is found by a method other than algebraic; OR $x > 80{,}000$ with no work shown.` },
      { credits: 0, criteria: "A response with no relevant course-level work, or a correct answer obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "ineq-cr-0621-q25",
    mode: "self-score",
    standard: "AI-A.REI.3",
    topic: "Solve a linear inequality algebraically",
    examCitation: "regents-algI-0621-q25",
    part: "II",
    credits: 2,
    prompt: String.raw`Solve algebraically for $y$:  $4(y - 3) \le 4(2y + 1)$`,
    answerSummary: String.raw`$y \ge -4$`,
    modelSolution: String.raw`Distribute both sides: $4y - 12 \le 8y + 4$. Subtract $8y$: $-4y - 12 \le 4$. Add $12$: $-4y \le 16$. Divide by $-4$ and **reverse** the inequality: $y \ge -4$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$y \ge -4$, and correct algebraic work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made; OR one conceptual error is made; OR $y \ge -4$ is found by a method other than algebraic; OR $y \ge -4$ with no work shown.` },
      { credits: 0, criteria: "A response with no relevant course-level work, or a correct answer obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "ineq-cr-0626-q27",
    mode: "self-score",
    standard: "AI-A.REI.3",
    topic: "Solve a linear inequality algebraically — distribute, reverse the sign",
    examCitation: "regents-algI-0626-q27",
    part: "II",
    credits: 2,
    prompt: String.raw`Solve the inequality algebraically:  $-4x + 1 > 9 + 3(2x + 1) + x$`,
    answerSummary: String.raw`$x < -1$`,
    modelSolution: String.raw`Distribute and combine on the right: $-4x + 1 > 9 + 6x + 3 + x$, so $-4x + 1 > 7x + 12$. Subtract $7x$: $-11x + 1 > 12$. Subtract $1$: $-11x > 11$. Divide by $-11$ and **reverse** the inequality: $x < -1$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$x < -1$, and correct algebraic work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made; OR one conceptual error is made; OR $x < -1$ is found by a method other than algebraic; OR $x < -1$ with no work shown.` },
      { credits: 0, criteria: "A response with no relevant course-level work, or a correct answer obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "ineq-cr-0117-q27",
    mode: "self-score",
    standard: "AI-A.REI.3",
    topic: "Solve a linear inequality algebraically — decimals",
    examCitation: "regents-algI-0117-q27",
    part: "II",
    credits: 2,
    prompt: String.raw`Solve the inequality below:  $1.8 - 0.4y \ge 2.2 - 2y$`,
    answerSummary: String.raw`$y \ge 0.25$`,
    modelSolution: String.raw`Add $2y$ to both sides: $1.8 + 1.6y \ge 2.2$. Subtract $1.8$: $1.6y \ge 0.4$. Divide by $1.6$ (positive, sign stays): $y \ge 0.25$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$y \ge 0.25$, and correct algebraic work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made; OR one conceptual error is made; OR $y \ge 0.25$ is found by a method other than algebraic; OR $y \ge 0.25$ with no work shown.` },
      { credits: 0, criteria: "A response with no relevant course-level work, or a correct answer obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "ineq-cr-0819-q29",
    mode: "self-score",
    standard: "AI-A.REI.3",
    topic: "Solve a linear inequality algebraically — fractions",
    examCitation: "regents-algI-0819-q29",
    part: "II",
    credits: 2,
    prompt: String.raw`Solve $\frac{3}{5}x + \frac{1}{3} < \frac{4}{5}x - \frac{1}{3}$ for $x$.`,
    answerSummary: String.raw`$x > \frac{10}{3}$`,
    modelSolution: String.raw`Subtract $\frac{3}{5}x$ from both sides: $\frac{1}{3} < \frac{1}{5}x - \frac{1}{3}$. Add $\frac{1}{3}$: $\frac{2}{3} < \frac{1}{5}x$. Multiply by $5$ (positive, sign stays): $\frac{10}{3} < x$ — that is, $x > \frac{10}{3}$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$x > \frac{10}{3}$, and correct algebraic work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made; OR one conceptual error is made; OR $x > \frac{10}{3}$ is found by a method other than algebraic; OR $x > \frac{10}{3}$ with no work shown.` },
      { credits: 0, criteria: "A response with no relevant course-level work, or a correct answer obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "ineq-cr-0615-q30",
    mode: "self-score",
    standard: "AI-A.REI.3",
    topic: "Solve a linear inequality and interpret the solution",
    examCitation: "regents-algI-0615-q30",
    part: "II",
    credits: 2,
    prompt: String.raw`Determine the smallest integer that makes $-3x + 7 - 5x < 15$ true.`,
    answerSummary: String.raw`$0$ (the solution is $x > -1$)`,
    modelSolution: String.raw`Combine like terms: $-8x + 7 < 15$. Subtract $7$: $-8x < 8$. Divide by $-8$ and **reverse** the inequality: $x > -1$. The smallest integer greater than $-1$ is $0$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$0$, and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational or rounding error is made; OR one conceptual error is made; OR appropriate work is shown to find $x > -1$, but the smallest integer is not stated or is stated incorrectly; OR $0$, but no work is shown.` },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "ineq-cr-0814-q30",
    mode: "self-score",
    standard: "AI-A.REI.3",
    topic: "Solve a linear inequality and interpret the solution",
    examCitation: "regents-algI-0814-q30",
    part: "II",
    credits: 2,
    prompt: String.raw`Solve the inequality below to determine and state the smallest possible value for $x$ in the solution set.\n\n$3(x + 3) \le 5x - 3$`,
    answerSummary: String.raw`$6$ (the solution is $x \ge 6$)`,
    modelSolution: String.raw`Distribute: $3x + 9 \le 5x - 3$. Subtract $3x$: $9 \le 2x - 3$. Add $3$: $12 \le 2x$. Divide by $2$ (positive, sign stays): $6 \le x$, so $x \ge 6$. The smallest possible value is $6$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$6$, and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made; OR one conceptual error is made; OR appropriate work is shown to find $x \ge 6$, but no further correct work is shown; OR $6$, but no work is shown.` },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "ineq-cr-0815-q34",
    mode: "self-score",
    standard: "AI-A.REI.3",
    topic: "Solve a linear inequality algebraically and interpret the solution set",
    examCitation: "regents-algI-0815-q34",
    part: "IV",
    credits: 4,
    prompt: String.raw`Solve for $x$ algebraically:  $7x - 3(4x - 8) \le 6x + 12 - 9x$\n\nIf $x$ is a number in the interval $[4, 8]$, state all integers that satisfy the given inequality. Explain how you determined these values.`,
    answerSummary: String.raw`$x \ge 6$; the integers in $[4, 8]$ that satisfy it are $6$, $7$, and $8$.`,
    modelSolution: String.raw`Distribute: $7x - 12x + 24 \le 6x + 12 - 9x$. Combine each side: $-5x + 24 \le -3x + 12$. Add $5x$: $24 \le 2x + 12$. Subtract $12$: $12 \le 2x$. Divide by $2$: $6 \le x$, so $x \ge 6$. The integers in $[4, 8]$ are $4, 5, 6, 7, 8$; those that are at least $6$ are $6$, $7$, and $8$.`,
    rubric: [
      { credits: 4, criteria: String.raw`$x \ge 6$, and correct algebraic work is shown. $6$, $7$, and $8$, and a correct explanation is written.` },
      { credits: 3, criteria: String.raw`Appropriate work is shown, but one computational error is made; OR appropriate work is shown, but the explanation is incomplete, incorrect, or missing.` },
      { credits: 2, criteria: String.raw`Appropriate work is shown, but two or more computational errors are made; OR one conceptual error is made; OR appropriate work is shown to find $x \ge 6$, but no further correct work is shown; OR $x \ge 6$ and $6, 7, 8$, but a method other than algebraic is used.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one conceptual error and one computational error are made; OR appropriate work is shown to find $-5x + 24 \le 12 - 3x$ or an equivalent inequality, but no further correct work is shown; OR $6, 7, 8$, but no work is shown.` },
      { credits: 0, criteria: String.raw`$7x - 12x + 24 \le 6x + 12 - 9x$, but no further correct work is shown; OR a zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure.` },
    ],
  },
];

export default bank;
