// Authored Regents problem-bank — Linear Functions & Rate of Change. The
// foundational linear-function skills the rest of Algebra I builds on: average
// rate of change / slope (AI-F.IF.6), interpreting a line's slope and intercept
// in context (AI-S.ID.7), writing a linear function (AI-F.LE.2), and creating /
// graphing linear equations (AI-A.CED.2). Real released Algebra I Regents
// questions mined from the official NYSED administrations (via JMAP), cited to the
// exam + question number. Every answer independently re-derived. Constructed-
// response rubrics are transcribed VERBATIM from the official NYSED Rating Guides.
// SME-ratified.

import type { RegentsItem } from "@/lib/regents/bank";

const bank: RegentsItem[] = [
  // ——— Average rate of change from a function / table (AI-F.IF.6) ———
  {
    id: "lin-mc-0115-q21",
    mode: "mc",
    standard: "AI-F.IF.6",
    topic: "Average rate of change over an interval",
    examCitation: "regents-algI-0115-q21",
    part: "I",
    credits: 2,
    prompt: String.raw`An astronaut drops a rock off the edge of a cliff on the Moon. The distance, $d(t)$, in meters, the rock travels after $t$ seconds is modeled by $d(t) = 0.8t^2$. What is the average speed, in meters per second, of the rock between $5$ and $10$ seconds after it was dropped?`,
    choices: [String.raw`$12$`, String.raw`$20$`, String.raw`$60$`, String.raw`$80$`],
    answer: 0,
    explanation: String.raw`Average rate of change is $\dfrac{d(10) - d(5)}{10 - 5}$. Here $d(10) = 0.8(100) = 80$ and $d(5) = 0.8(25) = 20$, so $\dfrac{80 - 20}{5} = \dfrac{60}{5} = 12$ m/s.`,
  },
  {
    id: "lin-mc-0621-q05",
    mode: "mc",
    standard: "AI-F.IF.6",
    topic: "Average rate of change from two values",
    examCitation: "regents-algI-0621-q05",
    part: "I",
    credits: 2,
    prompt: String.raw`The value of Tony's investment was \$1140 on January 1st. On this date three years later, his investment was worth \$1824. The average rate of change for this investment was \$19 per`,
    choices: ["day", "month", "quarter", "year"],
    answer: 1,
    explanation: String.raw`The total change is $1824 - 1140 = 684$ dollars over $3$ years, so $\dfrac{684}{3} = 228$ dollars per year. Dividing by the $12$ months in a year, $\dfrac{228}{12} = 19$ — the rate of change is \$19 per month.`,
  },
  {
    id: "lin-mc-0625-q07",
    mode: "mc",
    standard: "AI-F.IF.6",
    topic: "Average rate of change from a table",
    examCitation: "regents-algI-0625-q07",
    part: "I",
    credits: 2,
    prompt: String.raw`The function $h(x)$ gives the average height, in inches, of a tomato plant $x$ weeks after it is transplanted. These data are represented in the table below. Between weeks $4$ and $12$, the average rate of change, in inches per week, is`,
    figure: {
      kind: "table",
      headers: ["x", "h(x)"],
      rows: [
        [2, 6],
        [4, 12],
        [6, 24],
        [9, 51],
        [12, 60],
        [16, 64],
      ],
    },
    choices: [String.raw`$6$`, String.raw`$8$`, String.raw`$48$`, String.raw`$58$`],
    answer: 0,
    explanation: String.raw`$\dfrac{h(12) - h(4)}{12 - 4} = \dfrac{60 - 12}{12 - 4} = \dfrac{48}{8} = 6$ inches per week.`,
  },
  {
    id: "lin-mc-0825-q11",
    mode: "mc",
    standard: "AI-F.IF.6",
    topic: "Average rate of change from a table",
    examCitation: "regents-algI-0825-q11",
    part: "I",
    credits: 2,
    prompt: String.raw`The table below shows the radioactivity level of a substance after the given time, $t$, in seconds. What is the average rate of change in radioactivity level over the interval $1 \le t \le 3$?`,
    figure: {
      kind: "table",
      headers: ["Time (seconds)", "Radioactivity Level"],
      rows: [
        [0, 20],
        [1, 10],
        [2, 5],
        [3, 2.5],
        [4, 1.25],
      ],
    },
    choices: [String.raw`$3.75$`, String.raw`$-3.75$`, String.raw`$4.6875$`, String.raw`$-4.6875$`],
    answer: 1,
    explanation: String.raw`$\dfrac{f(3) - f(1)}{3 - 1} = \dfrac{2.5 - 10}{3 - 1} = \dfrac{-7.5}{2} = -3.75$ per second (the level is decreasing, so the rate is negative).`,
  },
  {
    id: "lin-mc-0824-q10",
    mode: "mc",
    standard: "AI-F.IF.6",
    topic: "Average rate of change from a table",
    examCitation: "regents-algI-0824-q10",
    part: "I",
    credits: 2,
    prompt: String.raw`A bookstore owner recorded the number of books sold and the profit made selling the books, as shown in the table below. What is the average rate of change, in dollars per book, between $100$ and $350$ books sold?`,
    figure: {
      kind: "table",
      headers: ["Books Sold", "Profit"],
      rows: [
        [100, "$50.00"],
        [250, "$275.00"],
        [300, "$350.00"],
        [350, "$425.00"],
      ],
    },
    choices: [String.raw`$0.50$`, String.raw`$0.67$`, String.raw`$1.50$`, String.raw`$2.00$`],
    answer: 2,
    explanation: String.raw`$\dfrac{425 - 50}{350 - 100} = \dfrac{375}{250} = 1.50$ dollars per book.`,
  },
  {
    id: "lin-mc-0814-q14",
    mode: "mc",
    standard: "AI-F.IF.6",
    topic: "Average rate of change from a table",
    examCitation: "regents-algI-0814-q14",
    part: "I",
    credits: 2,
    prompt: String.raw`The table below shows the average diameter of a pupil in a person's eye as he or she grows older. What is the average rate of change, in millimeters per year, of a person's pupil diameter from age $20$ to age $80$?`,
    figure: {
      kind: "table",
      headers: ["Age (years)", "Average Pupil Diameter (mm)"],
      rows: [
        [20, 4.7],
        [30, 4.3],
        [40, 3.9],
        [50, 3.5],
        [60, 3.1],
        [70, 2.7],
        [80, 2.3],
      ],
    },
    choices: [String.raw`$2.4$`, String.raw`$0.04$`, String.raw`$-2.4$`, String.raw`$-0.04$`],
    answer: 3,
    explanation: String.raw`$\dfrac{2.3 - 4.7}{80 - 20} = \dfrac{-2.4}{60} = -0.04$ mm per year (the diameter shrinks with age).`,
  },
  {
    id: "lin-mc-0116-q13",
    mode: "mc",
    standard: "AI-F.IF.6",
    topic: "Average rate of change — greatest interval",
    examCitation: "regents-algI-0116-q13",
    part: "I",
    credits: 2,
    prompt: String.raw`The table below shows the cost of mailing a postcard in different years. During which time interval did the cost increase at the greatest average rate?`,
    figure: {
      kind: "table",
      headers: ["Year", "Cost (¢)"],
      rows: [
        [1898, 1],
        [1971, 6],
        [1985, 14],
        [2006, 24],
        [2012, 35],
      ],
    },
    choices: ["1898–1971", "1971–1985", "1985–2006", "2006–2012"],
    answer: 3,
    explanation: String.raw`Compute the rate (change in cost ÷ change in years) for each interval: $1898$–$1971$: $\tfrac{5}{73} \approx 0.07$; $1971$–$1985$: $\tfrac{8}{14} \approx 0.57$; $1985$–$2006$: $\tfrac{10}{21} \approx 0.48$; $2006$–$2012$: $\tfrac{11}{6} \approx 1.83$. The steepest is $2006$–$2012$.`,
  },
  {
    id: "lin-mc-0616-q03",
    mode: "mc",
    standard: "AI-F.IF.6",
    topic: "Average rate of change — smallest interval",
    examCitation: "regents-algI-0616-q03",
    part: "I",
    credits: 2,
    prompt: String.raw`The table below shows the year and the number of households in a building that had high-speed broadband internet access. For which interval of time was the average rate of change the smallest?`,
    figure: {
      kind: "table",
      headers: ["Year", "Number of Households"],
      rows: [
        [2002, 11],
        [2003, 16],
        [2004, 23],
        [2005, 33],
        [2006, 42],
        [2007, 47],
      ],
    },
    choices: ["2002–2004", "2003–2005", "2004–2006", "2005–2007"],
    answer: 0,
    explanation: String.raw`Each interval spans $2$ years: $2002$–$2004$: $\tfrac{23 - 11}{2} = 6$; $2003$–$2005$: $\tfrac{33 - 16}{2} = 8.5$; $2004$–$2006$: $\tfrac{42 - 23}{2} = 9.5$; $2005$–$2007$: $\tfrac{47 - 33}{2} = 7$. The smallest rate is over $2002$–$2004$.`,
  },

  // ——— Interpret slope & y-intercept of a linear model in context (AI-S.ID.7) ———
  {
    id: "lin-mc-0117-q09",
    mode: "mc",
    standard: "AI-S.ID.7",
    topic: "Interpret the slope in context",
    examCitation: "regents-algI-0117-q09",
    part: "I",
    credits: 2,
    prompt: String.raw`A car leaves Albany, NY, and travels west toward Buffalo, NY. The equation $D = 280 - 59t$ can be used to represent the distance, $D$, from Buffalo after $t$ hours. In this equation, the $59$ represents the`,
    choices: [
      "car's distance from Albany",
      "speed of the car",
      "distance between Buffalo and Albany",
      "number of hours driving",
    ],
    answer: 1,
    explanation: String.raw`In $D = 280 - 59t$, the coefficient $59$ multiplies the time $t$, so it is a rate — miles per hour. It is the speed of the car (the distance from Buffalo drops $59$ miles each hour). The constant $280$ is the starting distance between the cities.`,
  },
  {
    id: "lin-mc-0624-q21",
    mode: "mc",
    standard: "AI-S.ID.7",
    topic: "Interpret the constant term in context",
    examCitation: "regents-algI-0624-q21",
    part: "I",
    credits: 2,
    prompt: String.raw`When babysitting, Nicole charges an hourly rate and an additional charge for gas. She uses the function $C(h) = 6h + 5$ to determine how much to charge for babysitting. The constant term of this function represents`,
    choices: [
      "the additional charge for gas",
      "the hourly rate Nicole charges",
      "the number of hours Nicole babysits",
      "the total Nicole earns from babysitting",
    ],
    answer: 0,
    explanation: String.raw`The constant term $5$ is the value of $C(h)$ when $h = 0$ hours — a fixed charge that does not depend on time. That is the additional charge for gas. The coefficient $6$ is the hourly rate.`,
  },
  {
    id: "lin-mc-0614-q07",
    mode: "mc",
    standard: "AI-S.ID.7",
    topic: "Interpret the slope in context",
    examCitation: "regents-algI-0614-q07",
    part: "I",
    credits: 2,
    prompt: String.raw`A company that manufactures radios first pays a start-up cost, and then spends a certain amount of money to manufacture each radio. If the cost of manufacturing $r$ radios is given by the function $c(r) = 5.25r + 125$, then the value $5.25$ best represents`,
    choices: [
      "the start-up cost",
      "the profit earned from the sale of one radio",
      "the amount spent to manufacture each radio",
      "the average number of radios manufactured",
    ],
    answer: 2,
    explanation: String.raw`The slope $5.25$ is the cost added for each additional radio — the amount spent to manufacture each radio. The constant $125$ is the fixed start-up cost.`,
  },
  {
    id: "lin-mc-0125-q05",
    mode: "mc",
    standard: "AI-S.ID.7",
    topic: "Interpret the slope in context",
    examCitation: "regents-algI-0125-q05",
    part: "I",
    credits: 2,
    prompt: String.raw`A landscaping company charges a set fee for a spring cleanup, plus an hourly labor rate. The total cost is modeled by the function $C(x) = 55x + 80$. In this function, what does the $55$ represent?`,
    choices: [
      "the set fee for the cleanup",
      "the hourly labor rate for a cleanup",
      "the profit earned by the company for one cleanup",
      "the number of hours of labor required for one cleanup",
    ],
    answer: 1,
    explanation: String.raw`The slope $55$ multiplies $x$ (the number of hours), so it is the cost per hour — the hourly labor rate. The constant $80$ is the set fee.`,
  },
  {
    id: "lin-mc-0115-q01",
    mode: "mc",
    standard: "AI-S.ID.7",
    topic: "Interpret the variable in a linear model",
    examCitation: "regents-algI-0115-q01",
    part: "I",
    credits: 2,
    prompt: String.raw`The owner of a small computer repair business has one employee, who is paid an hourly rate of \$22. The owner estimates his weekly profit using the function $P(x) = 8600 - 22x$. In this function, $x$ represents the number of`,
    choices: [
      "computers repaired per week",
      "hours worked per week",
      "customers served per week",
      "days worked per week",
    ],
    answer: 1,
    explanation: String.raw`The employee is paid \$22 per hour, so $22x$ is the wages paid. For that to make sense, $x$ must be the number of hours worked per week.`,
  },
  {
    id: "lin-mc-0824-q12",
    mode: "mc",
    standard: "AI-S.ID.7",
    topic: "Interpret the y-intercept in context",
    examCitation: "regents-algI-0824-q12",
    part: "I",
    credits: 2,
    prompt: String.raw`The amount of money a plumber charges is represented by the function $p(h) = 45 + 90h$. The best interpretation of the y-intercept of this function is that the plumber charges`,
    choices: [
      String.raw`\$45 to come to the house`,
      String.raw`\$45 per hour that he works`,
      String.raw`\$90 to come to the house`,
      String.raw`\$90 per hour that he works`,
    ],
    answer: 0,
    explanation: String.raw`The y-intercept is the value at $h = 0$: $p(0) = 45$. With no hours worked, the plumber still charges \$45 — a fixed fee to come to the house. The \$90 is the hourly rate.`,
  },
  {
    id: "lin-mc-0615-q01",
    mode: "mc",
    standard: "AI-S.ID.7",
    topic: "Interpret slope & y-intercept in context",
    examCitation: "regents-algI-0615-q01",
    part: "I",
    credits: 2,
    prompt: String.raw`The cost of airing a commercial on television is modeled by the function $C(n) = 110n + 900$, where $n$ is the number of times the commercial is aired. Based on this model, which statement is true?`,
    choices: [
      String.raw`The commercial costs \$0 to produce and \$110 per airing up to \$900.`,
      String.raw`The commercial costs \$110 to produce and \$900 each time it is aired.`,
      String.raw`The commercial costs \$900 to produce and \$110 each time it is aired.`,
      String.raw`The commercial costs \$1010 to produce and can air an unlimited number of times.`,
    ],
    answer: 2,
    explanation: String.raw`The y-intercept $900$ is the cost when $n = 0$ airings — the one-time production cost. The slope $110$ is added for each airing. So the commercial costs \$900 to produce and \$110 each time it is aired.`,
  },
  {
    id: "lin-mc-0818-q17",
    mode: "mc",
    standard: "AI-S.ID.7",
    topic: "Interpret slope & y-intercept in context",
    examCitation: "regents-algI-0818-q17",
    part: "I",
    credits: 2,
    prompt: String.raw`Each day, a local dog shelter spends an average of \$2.40 on food per dog. The manager estimates the shelter's daily expenses, assuming there is at least one dog in the shelter, using the function $E(x) = 30 + 2.40x$. Which statements regarding the function $E(x)$ are correct?
I. $x$ represents the number of dogs at the shelter per day.
II. $x$ represents the number of volunteers at the shelter per day.
III. $30$ represents the shelter's total expenses per day.
IV. $30$ represents the shelter's nonfood expenses per day.`,
    choices: ["I and III", "I and IV", "II and III", "II and IV"],
    answer: 1,
    explanation: String.raw`Since the \$2.40 is spent per dog, $x$ must be the number of dogs (I). The constant $30$ is the expense when $x = 0$ dogs — the fixed, nonfood expenses, not the total (IV). So I and IV.`,
  },
  {
    id: "lin-mc-0814-q02",
    mode: "mc",
    standard: "AI-S.ID.7",
    topic: "Interpret each part of a linear model",
    examCitation: "regents-algI-0814-q02",
    part: "I",
    credits: 2,
    prompt: String.raw`A satellite television company charges a one-time installation fee and a monthly service charge. The total cost is modeled by the function $y = 40 + 90x$. Which statement represents the meaning of each part of the function?`,
    choices: [
      String.raw`$y$ is the total cost, $x$ is the number of months of service, \$90 is the installation fee, and \$40 is the service charge per month.`,
      String.raw`$y$ is the total cost, $x$ is the number of months of service, \$40 is the installation fee, and \$90 is the service charge per month.`,
      String.raw`$x$ is the total cost, $y$ is the number of months of service, \$40 is the installation fee, and \$90 is the service charge per month.`,
      String.raw`$x$ is the total cost, $y$ is the number of months of service, \$90 is the installation fee, and \$40 is the service charge per month.`,
    ],
    answer: 1,
    explanation: String.raw`The output $y$ is the total cost and the input $x$ is the number of months. The constant $40$ (the cost at $x = 0$ months) is the one-time installation fee, and the slope $90$ is the monthly service charge.`,
  },

  // ——— Create a linear equation from a context (AI-A.CED.2) ———
  {
    id: "lin-mc-0614-q22",
    mode: "mc",
    standard: "AI-A.CED.2",
    topic: "Create a linear equation from a context",
    examCitation: "regents-algI-0614-q22",
    part: "I",
    credits: 2,
    prompt: String.raw`A cell phone company charges \$60.00 a month for up to 1 gigabyte of data. The cost of additional data is \$0.05 per megabyte. If $d$ represents the number of additional megabytes used and $c$ represents the total charges at the end of the month, which linear equation can be used to determine a user's monthly bill?`,
    choices: [
      String.raw`$c = 60 - 0.05d$`,
      String.raw`$c = 60.05d$`,
      String.raw`$c = 60d - 0.05$`,
      String.raw`$c = 60 + 0.05d$`,
    ],
    answer: 3,
    explanation: String.raw`Start with the flat \$60 charge and add \$0.05 for each of the $d$ additional megabytes: $c = 60 + 0.05d$.`,
  },
  {
    id: "lin-mc-0815-q08",
    mode: "mc",
    standard: "AI-A.CED.2",
    topic: "Create a linear equation from a context",
    examCitation: "regents-algI-0815-q08",
    part: "I",
    credits: 2,
    prompt: String.raw`A typical cell phone plan has a fixed base fee that includes a certain amount of data and an overage charge for data use beyond the plan. A cell phone plan charges a base fee of \$62 and an overage charge of \$30 per gigabyte of data that exceed 2 gigabytes. If $C$ represents the cost and $g$ represents the total number of gigabytes of data, which equation could represent this plan when more than 2 gigabytes are used?`,
    choices: [
      String.raw`$C = 30 + 62(2 - g)$`,
      String.raw`$C = 30 + 62(g - 2)$`,
      String.raw`$C = 62 + 30(2 - g)$`,
      String.raw`$C = 62 + 30(g - 2)$`,
    ],
    answer: 3,
    explanation: String.raw`The base fee is \$62. Data beyond the included 2 GB is $g - 2$ gigabytes, each charged \$30: $C = 62 + 30(g - 2)$.`,
  },

  // ——— Write a linear function from a table (AI-F.LE.2) ———
  {
    id: "lin-mc-0816-q04",
    mode: "mc",
    standard: "AI-F.LE.2",
    topic: "Match a linear function to its table",
    examCitation: "regents-algI-0816-q04",
    part: "I",
    credits: 2,
    prompt: String.raw`Which chart could represent the function $f(x) = -2x + 6$?`,
    choices: ["Chart (1)", "Chart (2)", "Chart (3)", "Chart (4)"],
    choiceFigures: [
      {
        kind: "table",
        headers: ["x", "f(x)"],
        rows: [
          [0, 6],
          [2, 10],
          [4, 14],
          [6, 18],
        ],
      },
      {
        kind: "table",
        headers: ["x", "f(x)"],
        rows: [
          [0, 4],
          [2, 6],
          [4, 8],
          [6, 10],
        ],
      },
      {
        kind: "table",
        headers: ["x", "f(x)"],
        rows: [
          [0, 8],
          [2, 10],
          [4, 12],
          [6, 14],
        ],
      },
      {
        kind: "table",
        headers: ["x", "f(x)"],
        rows: [
          [0, 6],
          [2, 2],
          [4, -2],
          [6, -6],
        ],
      },
    ],
    answer: 3,
    explanation: String.raw`For $f(x) = -2x + 6$, $f(0) = 6$ and each increase of $2$ in $x$ lowers $f(x)$ by $4$ (slope $-2$). Chart (4) starts at $6$ and goes $6, 2, -2, -6$ — matching. The other charts have positive slopes.`,
  },

  // ——— Constructed response: average rate of change (AI-F.IF.6) ———
  {
    id: "lin-cr-0117-q31",
    mode: "self-score",
    standard: "AI-F.IF.6",
    topic: "Average rate of change with units",
    examCitation: "regents-algI-0117-q31",
    part: "II",
    credits: 2,
    prompt: String.raw`A family is traveling from their home to a vacation resort hotel. The table below shows their distance from home as a function of time. Determine the average rate of change between hour 2 and hour 7, including units.`,
    figure: {
      kind: "table",
      headers: ["Time (hrs)", 0, 2, 5, 7],
      rows: [["Distance (mi)", 0, 140, 375, 480]],
    },
    answerSummary: String.raw`$68$ mph`,
    modelSolution: String.raw`The average rate of change is $\dfrac{480 - 140}{7 - 2} = \dfrac{340}{5} = 68$. Between hour 2 and hour 7 the family travels at an average rate of $68$ miles per hour.`,
    rubric: [
      { credits: 2, criteria: String.raw`68 mph, and correct work is shown.` },
      {
        credits: 1,
        criteria: String.raw`Appropriate work is shown, but one computational error is made; OR appropriate work is shown, but one conceptual error is made; OR appropriate work is shown to find 68, but the units are not labeled; OR 68 mph, but no work is shown.`,
      },
      {
        credits: 0,
        criteria:
          "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure.",
      },
    ],
  },
  {
    id: "lin-cr-0818-q27",
    mode: "self-score",
    standard: "AI-F.IF.6",
    topic: "Average rate of change from a table",
    examCitation: "regents-algI-0818-q27",
    part: "II",
    credits: 2,
    prompt: String.raw`The table below represents the height of a bird above the ground during flight, with $P(t)$ representing height in feet and $t$ representing time in seconds. Calculate the average rate of change from 3 to 9 seconds, in feet per second.`,
    figure: {
      kind: "table",
      headers: ["t", "P(t)"],
      rows: [
        [0, 6.71],
        [3, 6.26],
        [4, 6],
        [9, 3.41],
      ],
    },
    answerSummary: String.raw`$-0.475$ ft/s`,
    modelSolution: String.raw`$\dfrac{P(9) - P(3)}{9 - 3} = \dfrac{3.41 - 6.26}{9 - 3} = \dfrac{-2.85}{6} = -0.475$. The bird's height changes at an average rate of $-0.475$ foot per second (it is descending over this interval).`,
    rubric: [
      { credits: 2, criteria: String.raw`$-0.475$ is stated, and correct work is shown.` },
      {
        credits: 1,
        criteria: String.raw`Appropriate work is shown, but one computational error is made; OR appropriate work is shown, but one conceptual error is made; OR $\dfrac{3.41 - 6.26}{9 - 3}$ is written, but no further correct work is shown; OR $-0.475$ is stated, but no work is shown.`,
      },
      {
        credits: 0,
        criteria:
          "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure.",
      },
    ],
  },
  {
    id: "lin-cr-0124-q27",
    mode: "self-score",
    standard: "AI-F.IF.6",
    topic: "Average rate of change with units",
    examCitation: "regents-algI-0124-q27",
    part: "II",
    credits: 2,
    prompt: String.raw`The table below shows data from a recent car trip for the Burke family. State the average rate of change for the distance traveled between hours 2 and 4. Include appropriate units.`,
    figure: {
      kind: "table",
      headers: ["Hours After Leaving (x)", 1, 2, 3, 4, 5],
      rows: [["Miles from Home (y)", 45, 112, 178, 238, 305]],
    },
    answerSummary: String.raw`$63$ mph`,
    modelSolution: String.raw`$\dfrac{238 - 112}{4 - 2} = \dfrac{126}{2} = 63$. Between hours 2 and 4 the Burke family travels at an average rate of $63$ miles per hour.`,
    rubric: [
      { credits: 2, criteria: String.raw`63 mph is stated.` },
      {
        credits: 1,
        criteria: String.raw`Appropriate work is shown, but one computational error is made; OR appropriate work is shown, but one conceptual error is made; OR 63, but the units are missing or incorrect; OR miles per hour is stated, but no further correct work is shown.`,
      },
      {
        credits: 0,
        criteria:
          "A zero response does not contain enough relevant course-level work to receive any credit, does not satisfy the criteria for one or more credits, or is a correct response that was obtained by an obviously incorrect procedure.",
      },
    ],
  },
  {
    id: "lin-cr-0619-q29",
    mode: "self-score",
    standard: "AI-F.IF.6",
    topic: "Comparing average rates over two intervals",
    examCitation: "regents-algI-0619-q29",
    part: "II",
    credits: 2,
    prompt: String.raw`A blizzard occurred on the East Coast during January, 2016. Snowfall totals from the storm were recorded for Washington, D.C. and are shown in the table below. Which interval, 1 a.m. to 12 noon or 6 a.m. to 3 p.m., has the greater rate of snowfall, in inches per hour? Justify your answer.`,
    figure: {
      kind: "table",
      headers: ["Time", "Snow (inches)"],
      rows: [
        ["1 a.m.", 1],
        ["3 a.m.", 5],
        ["6 a.m.", 11],
        ["12 noon", 33],
        ["3 p.m.", 36],
      ],
      caption: "Washington, D.C.",
    },
    answerSummary: String.raw`1 a.m. to 12 noon (about $2.9$ in/hr, versus about $2.8$ in/hr for 6 a.m. to 3 p.m.).`,
    modelSolution: String.raw`From 1 a.m. to 12 noon is $11$ hours and the snow rises from $1$ to $33$ inches: $\dfrac{33 - 1}{12 - 1} = \dfrac{32}{11} \approx 2.9$ inches per hour. From 6 a.m. to 3 p.m. is $9$ hours and the snow rises from $11$ to $36$ inches: $\dfrac{36 - 11}{15 - 6} = \dfrac{25}{9} \approx 2.8$ inches per hour. Since $2.9 > 2.8$, the interval 1 a.m. to 12 noon has the greater rate of snowfall.`,
    rubric: [
      { credits: 2, criteria: String.raw`1 a.m. to 12 noon, and a correct justification is given.` },
      {
        credits: 1,
        criteria: String.raw`Appropriate work is shown, but one computational error is made; OR appropriate work is shown, but one conceptual error is made; OR correct rates for both intervals are found, but 1 a.m. to 12 noon is not stated.`,
      },
      {
        credits: 0,
        criteria:
          "1 a.m. to 12 noon, but no justification is given; OR a zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure.",
      },
    ],
  },
  {
    id: "lin-cr-0623-q34",
    mode: "self-score",
    standard: "AI-F.IF.6",
    topic: "Intervals of increase & average rate of change",
    examCitation: "regents-algI-0623-q34",
    part: "III",
    credits: 4,
    prompt: String.raw`Jean recorded temperatures over a 24-hour period one day in August in Syracuse, NY. Her results are shown in the table below. State the entire interval over which the temperature is increasing. State the three-hour interval that has the greatest rate of change in temperature. State the average rate of change from hour 12 to hour 24. Explain what this means in the context of the problem.`,
    figure: {
      kind: "table",
      headers: ["Time (hour)", 0, 3, 6, 9, 12, 15, 18, 21, 24],
      rows: [["Temperature (°F)", 80, 75, 70, 78, 92, 89, 85, 80, 74]],
    },
    answerSummary: String.raw`Increasing over hours $6$–$12$; greatest three-hour rate of change is $9$–$12$; average rate of change from hour 12 to 24 is $-\tfrac{3}{2}$ — the temperature drops $3°$ every $2$ hours.`,
    modelSolution: String.raw`The temperature rises from hour 6 ($70°$) to hour 12 ($92°$), so it is increasing over the interval from hour $6$ to hour $12$. The three-hour changes are $0$–$3$: $-5$; $3$–$6$: $-5$; $6$–$9$: $+8$; $9$–$12$: $+14$; $12$–$15$: $-3$; $15$–$18$: $-4$; $18$–$21$: $-5$; $21$–$24$: $-6$. The greatest is hour $9$ to hour $12$ ($+14°$). From hour 12 to hour 24: $\dfrac{74 - 92}{24 - 12} = \dfrac{-18}{12} = -\dfrac{3}{2}$, which means the temperature drops about $3°$ every $2$ hours (a decrease of $1.5°$ per hour).`,
    rubric: [
      {
        credits: 4,
        criteria: String.raw`6–12, 9–12, and $-\tfrac{3}{2}$ or equivalent are stated, and a correct explanation is written.`,
      },
      {
        credits: 3,
        criteria: String.raw`Appropriate work is shown, but one computational error is made; OR appropriate work is shown, but one interval is missing or incorrect; OR appropriate work is shown, but the explanation is missing or incorrect.`,
      },
      {
        credits: 2,
        criteria: String.raw`Both intervals are stated correctly, but no further correct work is shown; OR $-\tfrac{3}{2}$ is stated and a correct explanation is written, but no further correct work is shown.`,
      },
      {
        credits: 1,
        criteria: String.raw`One correct interval is stated, but no further correct work is shown; OR $-\tfrac{3}{2}$ is stated, but no further correct work is shown.`,
      },
      {
        credits: 0,
        criteria:
          "A zero response does not contain enough relevant course-level work to receive any credit, does not satisfy the criteria for one or more credits, or is a correct response that was obtained by an obviously incorrect procedure.",
      },
    ],
  },

  // ——— Constructed response: interpret slope & y-intercept (AI-S.ID.7) ———
  {
    id: "lin-cr-0116-q29",
    mode: "self-score",
    standard: "AI-S.ID.7",
    topic: "Meaning of slope & y-intercept in context",
    examCitation: "regents-algI-0116-q29",
    part: "II",
    credits: 2,
    prompt: String.raw`The cost of belonging to a gym can be modeled by $C(m) = 50m + 79.50$, where $C(m)$ is the total cost for $m$ months of membership. State the meaning of the slope and y-intercept of this function with respect to the costs associated with the gym membership.`,
    answerSummary: String.raw`The slope, $50$, is the cost per month (\$50 each month); the y-intercept, $79.50$, is the initial (one-time) cost of joining.`,
    modelSolution: String.raw`In $C(m) = 50m + 79.50$, the slope $50$ is the rate of change of cost per month — the gym charges \$50 for each month of membership. The y-intercept $79.50$ is the cost when $m = 0$ — the initial, one-time cost paid to join, before any monthly charges.`,
    rubric: [
      {
        credits: 2,
        criteria: String.raw`The slope is the cost per month and the y-intercept is the initial cost, or similar statements are made.`,
      },
      {
        credits: 1,
        criteria: String.raw`One conceptual error is made, such as reversing the descriptions; OR only one statement is correct.`,
      },
      {
        credits: 0,
        criteria:
          "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure.",
      },
    ],
  },
  {
    id: "lin-cr-0616-q30",
    mode: "self-score",
    standard: "AI-S.ID.7",
    topic: "Meaning of slope in context",
    examCitation: "regents-algI-0616-q30",
    part: "II",
    credits: 2,
    prompt: String.raw`During a recent snowstorm in Red Hook, NY, Jaime noted that there were 4 inches of snow on the ground at 3:00 p.m., and there were 6 inches of snow on the ground at 7:00 p.m. If she were to graph these data, what does the slope of the line connecting these two points represent in the context of this problem?`,
    answerSummary: String.raw`The slope represents the number of inches of snow falling per hour ($0.5$ inch per hour).`,
    modelSolution: String.raw`The slope is $\dfrac{6 - 4}{7 - 3} = \dfrac{2}{4} = \tfrac{1}{2}$. In context, that is the change in the depth of snow per hour, so the slope represents the number of inches of snow falling each hour — here, half an inch per hour.`,
    rubric: [
      {
        credits: 2,
        criteria: String.raw`The number of inches of snow falling per hour or an equivalent explanation is written.`,
      },
      {
        credits: 1,
        criteria: String.raw`Appropriate work is shown, but one computational error is made; OR appropriate work is shown, but one conceptual error is made; OR an incomplete explanation is written; OR appropriate work is shown to find $\tfrac{1}{2}$, but no explanation or an incorrect explanation is written; OR an explanation that doesn't refer to the context is written.`,
      },
      {
        credits: 0,
        criteria:
          "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure.",
      },
    ],
  },

  // ——— Constructed response: create / write a linear equation (AI-A.CED.2, AI-F.LE.2) ———
  {
    id: "lin-cr-0117-q30",
    mode: "self-score",
    standard: "AI-A.CED.2",
    topic: "Write a cost equation & verify a value",
    examCitation: "regents-algI-0117-q30",
    part: "II",
    credits: 2,
    prompt: String.raw`Sandy programmed a website's checkout process with an equation to calculate the amount customers will be charged when they download songs. The website offers a discount. If one song is bought at the full price of \$1.29, then each additional song is \$.99. State an equation that represents the cost, $C$, when $s$ songs are downloaded. Sandy figured she would be charged \$52.77 for 52 songs. Is this the correct amount? Justify your answer.`,
    answerSummary: String.raw`$C = 1.29 + 0.99(s - 1)$; No — 52 songs cost \$51.78, not \$52.77.`,
    modelSolution: String.raw`The first song costs \$1.29 and each of the remaining $s - 1$ songs costs \$0.99, so $C = 1.29 + 0.99(s - 1)$ (equivalently $C = 0.99s + 0.30$). For 52 songs: $C = 1.29 + 0.99(52 - 1) = 1.29 + 0.99(51) = 1.29 + 50.49 = 51.78$. The correct charge is \$51.78, not \$52.77, so Sandy is not correct.`,
    rubric: [
      {
        credits: 2,
        criteria: String.raw`$C = 1.29 + .99(s - 1)$ or $C = .99s + .30$, and a justification indicating she is not correct is given.`,
      },
      {
        credits: 1,
        criteria: String.raw`Appropriate work is shown, but one computational error is made; OR appropriate work is shown, but one conceptual error is made; OR a correct equation is written, but no further correct work is shown; OR appropriate work is shown, but the equation is not written in terms of $C$ and $s$; OR a justification indicating she is not correct is given, but no further correct work is shown.`,
      },
      {
        credits: 0,
        criteria:
          "No is stated, but no further correct work is shown; OR a zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure.",
      },
    ],
  },
  {
    id: "lin-cr-0616-q35",
    mode: "self-score",
    standard: "AI-A.CED.2",
    topic: "Write a linear equation from a rate & use it",
    examCitation: "regents-algI-0616-q35",
    part: "III",
    credits: 4,
    prompt: String.raw`An airplane leaves New York City and heads toward Los Angeles. As it climbs, the plane gradually increases its speed until it reaches cruising altitude, at which time it maintains a constant speed for several hours as long as it stays at cruising altitude. After flying for 32 minutes, the plane reaches cruising altitude and has flown 192 miles. After flying for a total of 92 minutes, the plane has flown a total of 762 miles. Determine the speed of the plane, at cruising altitude, in miles per minute. Write an equation to represent the number of miles the plane has flown, $y$, during $x$ minutes at cruising altitude, only. Assuming that the plane maintains its speed at cruising altitude, determine the total number of miles the plane has flown 2 hours into the flight.`,
    answerSummary: String.raw`Speed at cruising altitude: $9.5$ miles per minute; $y = 9.5x$; total flown 2 hours into the flight: $1028$ miles.`,
    modelSolution: String.raw`At cruising altitude the plane goes from $192$ miles (at $32$ min) to $762$ miles (at $92$ min): $\dfrac{762 - 192}{92 - 32} = \dfrac{570}{60} = 9.5$ miles per minute. For $x$ minutes at cruising altitude, the miles flown is $y = 9.5x$. Two hours into the flight is $120$ minutes, of which $120 - 32 = 88$ minutes are at cruising altitude, so the total is $192 + 9.5(120 - 32) = 192 + 9.5(88) = 192 + 836 = 1028$ miles.`,
    rubric: [
      { credits: 4, criteria: String.raw`9.5, $y = 9.5x$ and 1028, and correct work is shown.` },
      {
        credits: 3,
        criteria: String.raw`Appropriate work is shown, but one computational error is made; OR appropriate work is shown to find 9.5 and 1028, but no equation or an incorrect equation is written; OR appropriate work is shown to find 9.5, $y = 9.5x$ and 266, the number of miles flown after 92 minutes, but no further correct work is shown.`,
      },
      {
        credits: 2,
        criteria: String.raw`Appropriate work is shown, but two or more computational errors are made; OR appropriate work is shown, but one conceptual error is made; OR appropriate work is shown to find 9.5 and $y = 9.5x$, but no further correct work is shown.`,
      },
      {
        credits: 1,
        criteria: String.raw`Appropriate work is shown, but one conceptual error and one computational error are made; OR appropriate work is shown to find 9.5, but no further correct work is shown; OR 9.5, $y = 9.5x$ and 1028, but no work is shown.`,
      },
      {
        credits: 0,
        criteria:
          "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure.",
      },
    ],
  },
  {
    id: "lin-cr-0822-q29",
    mode: "self-score",
    standard: "AI-F.LE.2",
    topic: "Write a linear equation relating quantities",
    examCitation: "regents-algI-0822-q29",
    part: "II",
    credits: 2,
    prompt: String.raw`The cost of one pound of grapes, $g$, is 15 cents more than one pound of apples, $a$. The cost of one pound of bananas, $b$, is twice as much as one pound of grapes. Write an equation that represents the cost of one pound of bananas in terms of the cost of one pound of apples.`,
    answerSummary: String.raw`$b = 2(a + 15)$ (equivalently $b = 2a + 30$).`,
    modelSolution: String.raw`Grapes cost 15 cents more than apples, so $g = a + 15$. Bananas cost twice as much as grapes, so $b = 2g = 2(a + 15)$, which simplifies to $b = 2a + 30$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$b = 2(a + 15)$ or an equivalent equation, and correct work is shown.` },
      {
        credits: 1,
        criteria: String.raw`Appropriate work is shown, but one computational error is made; OR appropriate work is shown, but one conceptual error is made; OR appropriate work is shown, but the solution is written as an expression; OR $g = a + 15$ and $b = 2g$, but no further correct work is shown; OR $b = 2(a + 15)$, but no work is shown.`,
      },
      {
        credits: 0,
        criteria:
          "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure.",
      },
    ],
  },
];

export default bank;
