// Authored Regents problem-bank — Creating & Solving Equations (AI-A.REI.3 /
// AI-A.CED.1): writing a one-variable equation from a context and solving linear
// equations in one variable (variables on both sides, distributing, fractional
// and decimal coefficients), including equations that have no solution or
// infinitely many. Real released Algebra I Regents questions mined from the
// official NYSED administrations (via JMAP), cited to the exam + question number.
// Every answer independently re-derived; signs verified against the source PDFs.
// Every self-score rubric is transcribed verbatim from the official NYSED Rating
// Guide. SME-ratified.

import type { RegentsItem } from "@/lib/regents/bank";

const bank: RegentsItem[] = [
  // ——————————————————————— Part I multiple choice ———————————————————————

  // ---- Solving linear equations (AI-A.REI.3) ----
  {
    id: "ove-mc-0626-q02",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving linear equations — variables on both sides",
    examCitation: "regents-algI-0626-q02",
    part: "I",
    credits: 2,
    prompt: String.raw`What is the value of $x$ in the equation $0.5x - 4 = 8 - x$?`,
    choices: [
      String.raw`$6$`,
      String.raw`$8$`,
      String.raw`$18$`,
      String.raw`$24$`,
    ],
    answer: 1,
    explanation: String.raw`Gather the $x$-terms on one side and the constants on the other. Add $x$ to both sides: $0.5x + x - 4 = 8$, so $1.5x - 4 = 8$. Add $4$: $1.5x = 12$. Divide by $1.5$: $x = 8$.`,
  },
  {
    id: "ove-mc-0621-q06",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving linear equations — distributing, variables on both sides",
    examCitation: "regents-algI-0621-q06",
    part: "I",
    credits: 2,
    prompt: String.raw`The solution to $3(x - 8) + 4x = 8x + 4$ is`,
    choices: [
      String.raw`$12$`,
      String.raw`$28$`,
      String.raw`$-12$`,
      String.raw`$-28$`,
    ],
    answer: 3,
    explanation: String.raw`Distribute and combine on the left: $3x - 24 + 4x = 7x - 24$. The equation is $7x - 24 = 8x + 4$. Subtract $7x$ from both sides: $-24 = x + 4$, so $x = -28$.`,
  },
  {
    id: "ove-mc-0818-q04",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving linear equations — distributing",
    examCitation: "regents-algI-0818-q04",
    part: "I",
    credits: 2,
    prompt: String.raw`The solution to $-2(1 - 4x) = 3x + 8$ is`,
    choices: [
      String.raw`$\dfrac{6}{11}$`,
      String.raw`$2$`,
      String.raw`$-\dfrac{10}{7}$`,
      String.raw`$-2$`,
    ],
    answer: 1,
    explanation: String.raw`Distribute the $-2$: $-2 + 8x = 3x + 8$. Subtract $3x$ and add $2$ to both sides: $5x = 10$, so $x = 2$.`,
  },
  {
    id: "ove-mc-0123-q07",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving linear equations — distributing both sides",
    examCitation: "regents-algI-0123-q07",
    part: "I",
    credits: 2,
    prompt: String.raw`What is the solution to $2 + 3(2a + 1) = 3(a + 2)$?`,
    choices: [
      String.raw`$\dfrac{1}{7}$`,
      String.raw`$\dfrac{1}{3}$`,
      String.raw`$-\dfrac{3}{7}$`,
      String.raw`$-\dfrac{1}{3}$`,
    ],
    answer: 1,
    explanation: String.raw`Distribute on each side: $2 + 6a + 3 = 3a + 6$, so $6a + 5 = 3a + 6$. Subtract $3a$ and $5$: $3a = 1$, giving $a = \dfrac{1}{3}$.`,
  },
  {
    id: "ove-mc-0617-q19",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving linear equations — decimal coefficients",
    examCitation: "regents-algI-0617-q19",
    part: "I",
    credits: 2,
    prompt: String.raw`An equation is given below.

$$4(x - 7) = 0.3(x + 2) + 2.11$$

The solution to the equation is`,
    choices: [
      String.raw`$8.3$`,
      String.raw`$8.7$`,
      String.raw`$3$`,
      String.raw`$-3$`,
    ],
    answer: 0,
    explanation: String.raw`Distribute: $4x - 28 = 0.3x + 0.6 + 2.11$, so $4x - 28 = 0.3x + 2.71$. Subtract $0.3x$ and add $28$: $3.7x = 30.71$. Divide: $x = 8.3$.`,
  },
  {
    id: "ove-mc-0819-q04",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving linear equations — proportion / cross-multiply",
    examCitation: "regents-algI-0819-q04",
    part: "I",
    credits: 2,
    prompt: String.raw`The value of $x$ that satisfies the equation $\dfrac{4}{3} = \dfrac{x + 10}{15}$ is`,
    choices: [
      String.raw`$-6$`,
      String.raw`$5$`,
      String.raw`$10$`,
      String.raw`$30$`,
    ],
    answer: 2,
    explanation: String.raw`Cross-multiply: $4 \cdot 15 = 3(x + 10)$, so $60 = 3x + 30$. Subtract $30$: $30 = 3x$, giving $x = 10$.`,
  },
  {
    id: "ove-mc-0624-q06",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving linear equations — fractional coefficient",
    examCitation: "regents-algI-0624-q06",
    part: "I",
    credits: 2,
    prompt: String.raw`The solution to $\dfrac{4(x - 5)}{3} + 2 = 14$ is`,
    choices: [
      String.raw`$15$`,
      String.raw`$14$`,
      String.raw`$6$`,
      String.raw`$4$`,
    ],
    answer: 1,
    explanation: String.raw`Subtract $2$: $\dfrac{4(x - 5)}{3} = 12$. Multiply by $3$: $4(x - 5) = 36$, so $x - 5 = 9$ and $x = 14$.`,
  },
  {
    id: "ove-mc-0823-q04",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving linear equations — fractional coefficient",
    examCitation: "regents-algI-0823-q04",
    part: "I",
    credits: 2,
    prompt: String.raw`What is the value of $x$ in the equation $\dfrac{5(2x - 4)}{3} + 9 = 14$?`,
    choices: [
      String.raw`$1.9$`,
      String.raw`$3.5$`,
      String.raw`$5.3$`,
      String.raw`$8.9$`,
    ],
    answer: 1,
    explanation: String.raw`Subtract $9$: $\dfrac{5(2x - 4)}{3} = 5$. Multiply by $3$: $5(2x - 4) = 15$, so $2x - 4 = 3$, giving $2x = 7$ and $x = 3.5$.`,
  },
  {
    id: "ove-mc-0814-q20",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving linear equations — fractions, common denominator",
    examCitation: "regents-algI-0814-q20",
    part: "I",
    credits: 2,
    prompt: String.raw`What is the value of $x$ in the equation $\dfrac{x - 2}{3} + \dfrac{1}{6} = \dfrac{5}{6}$?`,
    choices: [
      String.raw`$4$`,
      String.raw`$6$`,
      String.raw`$8$`,
      String.raw`$11$`,
    ],
    answer: 0,
    explanation: String.raw`Subtract $\dfrac{1}{6}$: $\dfrac{x - 2}{3} = \dfrac{5}{6} - \dfrac{1}{6} = \dfrac{4}{6} = \dfrac{2}{3}$. Then $x - 2 = 3 \cdot \dfrac{2}{3} = 2$, so $x = 4$.`,
  },
  {
    id: "ove-mc-0120-q05",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving linear equations — fractions, common denominator",
    examCitation: "regents-algI-0120-q05",
    part: "I",
    credits: 2,
    prompt: String.raw`Which value of $x$ makes $\dfrac{x - 3}{4} + \dfrac{2}{3} = \dfrac{17}{12}$ true?`,
    choices: [
      String.raw`$8$`,
      String.raw`$6$`,
      String.raw`$0$`,
      String.raw`$-4$`,
    ],
    answer: 1,
    explanation: String.raw`Subtract $\dfrac{2}{3} = \dfrac{8}{12}$: $\dfrac{x - 3}{4} = \dfrac{17}{12} - \dfrac{8}{12} = \dfrac{9}{12} = \dfrac{3}{4}$. Then $x - 3 = 4 \cdot \dfrac{3}{4} = 3$, so $x = 6$.`,
  },
  {
    id: "ove-mc-0614-q05",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving linear equations — fractional coefficient",
    examCitation: "regents-algI-0614-q05",
    part: "I",
    credits: 2,
    prompt: String.raw`Which value of $x$ satisfies the equation $\dfrac{7}{3}\left(x + \dfrac{9}{28}\right) = 20$?`,
    choices: [
      String.raw`$8.25$`,
      String.raw`$8.89$`,
      String.raw`$19.25$`,
      String.raw`$44.92$`,
    ],
    answer: 0,
    explanation: String.raw`Divide both sides by $\dfrac{7}{3}$ (multiply by $\dfrac{3}{7}$): $x + \dfrac{9}{28} = \dfrac{60}{7} = \dfrac{240}{28}$. Then $x = \dfrac{240}{28} - \dfrac{9}{28} = \dfrac{231}{28} = 8.25$.`,
  },
  {
    id: "ove-mc-0817-q13",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving linear equations — fractional coefficient",
    examCitation: "regents-algI-0817-q13",
    part: "I",
    credits: 2,
    prompt: String.raw`Which value of $x$ satisfies the equation $\dfrac{5}{6}\left(\dfrac{3}{8} - x\right) = 16$?`,
    choices: [
      String.raw`$-19.575$`,
      String.raw`$-18.825$`,
      String.raw`$-16.3125$`,
      String.raw`$-15.6875$`,
    ],
    answer: 1,
    explanation: String.raw`Multiply both sides by $\dfrac{6}{5}$: $\dfrac{3}{8} - x = 16 \cdot \dfrac{6}{5} = \dfrac{96}{5} = 19.2$. Then $-x = 19.2 - 0.375 = 18.825$, so $x = -18.825$.`,
  },
  {
    id: "ove-mc-0124-q16",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving linear equations — fractional coefficient",
    examCitation: "regents-algI-0124-q16",
    part: "I",
    credits: 2,
    prompt: String.raw`The solution to $\dfrac{2}{3}(3 - 2x) = \dfrac{3}{4}$ is`,
    choices: [
      String.raw`$-\dfrac{11}{8}$`,
      String.raw`$\dfrac{5}{8}$`,
      String.raw`$-\dfrac{33}{16}$`,
      String.raw`$\dfrac{15}{16}$`,
    ],
    answer: 3,
    explanation: String.raw`Multiply both sides by $\dfrac{3}{2}$: $3 - 2x = \dfrac{3}{4} \cdot \dfrac{3}{2} = \dfrac{9}{8}$. Then $-2x = \dfrac{9}{8} - 3 = -\dfrac{15}{8}$, so $x = \dfrac{15}{16}$.`,
  },
  {
    id: "ove-mc-0125-q11",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving linear equations — distributing, fractional coefficient",
    examCitation: "regents-algI-0125-q11",
    part: "I",
    credits: 2,
    prompt: String.raw`When solving $-2(3x - 5) = \dfrac{9}{2}x - 2$ for $x$, the solution is`,
    choices: [
      String.raw`$\dfrac{8}{7}$`,
      String.raw`$\dfrac{10}{11}$`,
      String.raw`$-\dfrac{16}{21}$`,
      String.raw`$-\dfrac{16}{3}$`,
    ],
    answer: 0,
    explanation: String.raw`Distribute: $-6x + 10 = \dfrac{9}{2}x - 2$. Multiply every term by $2$: $-12x + 20 = 9x - 4$. Add $12x$ and $4$: $24 = 21x$, so $x = \dfrac{24}{21} = \dfrac{8}{7}$.`,
  },
  {
    id: "ove-mc-0625-q21",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving linear equations — fractional coefficient",
    examCitation: "regents-algI-0625-q21",
    part: "I",
    credits: 2,
    prompt: String.raw`The solution to the equation $\dfrac{2(3x - 1)}{3} = x + 2$ is`,
    choices: [
      String.raw`$\dfrac{1}{3}$`,
      String.raw`$\dfrac{2}{3}$`,
      String.raw`$\dfrac{4}{3}$`,
      String.raw`$\dfrac{8}{3}$`,
    ],
    answer: 3,
    explanation: String.raw`Multiply both sides by $3$: $2(3x - 1) = 3(x + 2)$, so $6x - 2 = 3x + 6$. Subtract $3x$ and add $2$: $3x = 8$, giving $x = \dfrac{8}{3}$.`,
  },
  {
    id: "ove-mc-0119-q05",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving linear equations — fractional coefficient, decimal",
    examCitation: "regents-algI-0119-q05",
    part: "I",
    credits: 2,
    prompt: String.raw`What is the solution to the equation $\dfrac{3}{5}\left(x + \dfrac{4}{3}\right) = 1.04$?`,
    choices: [
      String.raw`$3.06$`,
      String.raw`$0.4$`,
      String.raw`$-0.48$`,
      String.raw`$-0.7093$`,
    ],
    answer: 1,
    explanation: String.raw`Multiply both sides by $\dfrac{5}{3}$: $x + \dfrac{4}{3} = 1.04 \cdot \dfrac{5}{3} = \dfrac{5.2}{3} \approx 1.7333$. Then $x = 1.7333 - 1.3333 = 0.4$.`,
  },
  {
    id: "ove-mc-0822-q17",
    mode: "mc",
    standard: "AI-A.REI.3",
    topic: "Solving linear equations — equivalent solutions",
    examCitation: "regents-algI-0822-q17",
    part: "I",
    credits: 2,
    prompt: String.raw`Which of the equations below have the same solution?

$$\text{I. } 10(x - 5) = -15 \qquad \text{II. } 4 + 2(x - 2) = 9 \qquad \text{III. } \dfrac{1}{3}x = \dfrac{3}{2}$$`,
    choices: [
      String.raw`I and II, only`,
      String.raw`I and III, only`,
      String.raw`II and III, only`,
      String.raw`I, II, and III`,
    ],
    answer: 2,
    explanation: String.raw`Solve each. I: $10(x - 5) = -15 \Rightarrow x - 5 = -1.5 \Rightarrow x = 3.5$. II: $4 + 2(x - 2) = 9 \Rightarrow 2(x - 2) = 5 \Rightarrow x = 4.5$. III: $\dfrac{1}{3}x = \dfrac{3}{2} \Rightarrow x = 4.5$. Equations II and III share the solution $x = 4.5$, while I gives $3.5$.`,
  },

  // ---- Writing a one-variable equation from a context (AI-A.CED.1) ----
  {
    id: "ove-mc-0619-q14",
    mode: "mc",
    standard: "AI-A.CED.1",
    topic: "Creating equations — translating a verbal model",
    examCitation: "regents-algI-0619-q14",
    part: "I",
    credits: 2,
    prompt: String.raw`Nicci's sister is $7$ years less than twice Nicci's age, $a$. The sum of Nicci's age and her sister's age is $41$. Which equation represents this relationship?`,
    choices: [
      String.raw`$a + (7 - 2a) = 41$`,
      String.raw`$a + (2a - 7) = 41$`,
      String.raw`$2a - 7 = 41$`,
      String.raw`$a = 2a - 7$`,
    ],
    answer: 1,
    explanation: String.raw`"Seven less than twice Nicci's age" is $2a - 7$, the sister's age. Their ages sum to $41$, so $a + (2a - 7) = 41$.`,
  },
  {
    id: "ove-mc-0625-q17",
    mode: "mc",
    standard: "AI-A.CED.1",
    topic: "Creating equations — translating a verbal model",
    examCitation: "regents-algI-0625-q17",
    part: "I",
    credits: 2,
    prompt: String.raw`The sum of Tim's age and Jack's age is $44$. Tim's age is $4$ less than $7$ times Jack's age, $x$. An equation that could be used to model this scenario is`,
    choices: [
      String.raw`$(7x - 4) + x = 44$`,
      String.raw`$(4 - 7x) + x = 44$`,
      String.raw`$7x - 4 = 44$`,
      String.raw`$4 - 7x = 44$`,
    ],
    answer: 0,
    explanation: String.raw`Jack's age is $x$, and Tim's age — "$4$ less than $7$ times Jack's age" — is $7x - 4$. Their ages sum to $44$, so $(7x - 4) + x = 44$.`,
  },
  {
    id: "ove-mc-0816-q16",
    mode: "mc",
    standard: "AI-A.CED.1",
    topic: "Creating equations — modeling a context",
    examCitation: "regents-algI-0816-q16",
    part: "I",
    credits: 2,
    prompt: String.raw`Kendal bought $x$ boxes of cookies to bring to a party. Each box contains $12$ cookies. She decides to keep two boxes for herself. She brings $60$ cookies to the party. Which equation can be used to find the number of boxes, $x$, Kendal bought?`,
    choices: [
      String.raw`$2x - 12 = 60$`,
      String.raw`$12x - 2 = 60$`,
      String.raw`$12x - 24 = 60$`,
      String.raw`$24 - 12x = 60$`,
    ],
    answer: 2,
    explanation: String.raw`Kendal bought $12x$ cookies total. Keeping two boxes removes $12 \cdot 2 = 24$ cookies, leaving $12x - 24$ for the party, which equals $60$: $12x - 24 = 60$.`,
  },
  {
    id: "ove-mc-0626-q09",
    mode: "mc",
    standard: "AI-A.CED.1",
    topic: "Creating equations — modeling cost/quantity",
    examCitation: "regents-algI-0626-q09",
    part: "I",
    credits: 2,
    prompt: String.raw`A garden club plans to plant $40$ flowering plants this year. They will only purchase daffodils that cost \$4 per plant and tulips that cost \$5 per plant. All prices include tax. The club has \$170 to spend on plants. Which equation could be used to find the number of daffodil plants, $d$, the club purchases?`,
    choices: [
      String.raw`$4d + 5(170 - d) = 40$`,
      String.raw`$4d + 5(40 - d) = 170$`,
      String.raw`$5d + 4(170 - d) = 40$`,
      String.raw`$5d + 4(40 - d) = 170$`,
    ],
    answer: 1,
    explanation: String.raw`With $d$ daffodils, the remaining $40 - d$ plants are tulips. The cost is $4d$ for daffodils plus $5(40 - d)$ for tulips, totaling \$170: $4d + 5(40 - d) = 170$.`,
  },
  {
    id: "ove-mc-0614-q16",
    mode: "mc",
    standard: "AI-A.CED.1",
    topic: "Creating equations — coin / value problem",
    examCitation: "regents-algI-0614-q16",
    part: "I",
    credits: 2,
    prompt: String.raw`John has four more nickels than dimes in his pocket, for a total of \$1.25. Which equation could be used to determine the number of dimes, $x$, in his pocket?`,
    choices: [
      String.raw`$0.10(x + 4) + 0.05(x) = 1.25$`,
      String.raw`$0.05(x + 4) + 0.10(x) = 1.25$`,
      String.raw`$0.10(4x) + 0.05(x) = 1.25$`,
      String.raw`$0.05(4x) + 0.10(x) = 1.25$`,
    ],
    answer: 1,
    explanation: String.raw`With $x$ dimes, John has $x + 4$ nickels. Nickels are worth \$0.05 and dimes \$0.10, so $0.05(x + 4) + 0.10(x) = 1.25$.`,
  },

  // ——————————————————— Part II–IV constructed response ———————————————————

  // ---- Solving linear equations algebraically (AI-A.REI.3) ----
  {
    id: "ove-cr-0126-q25",
    mode: "self-score",
    standard: "AI-A.REI.3",
    topic: "Solving linear equations — distributing, variables on both sides",
    examCitation: "regents-algI-0126-q25",
    part: "II",
    credits: 2,
    prompt: String.raw`Solve the equation for $x$:  $14x = 3(1 + 2x) - 4x$`,
    answerSummary: String.raw`$x = \dfrac{3}{12} = \dfrac{1}{4}$`,
    modelSolution: String.raw`Distribute and combine on the right: $3(1 + 2x) - 4x = 3 + 6x - 4x = 3 + 2x$. The equation is $14x = 3 + 2x$. Subtract $2x$: $12x = 3$, so $x = \dfrac{3}{12} = \dfrac{1}{4}$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$\dfrac{3}{12}$ or equivalent, and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but one conceptual error is made. OR $\dfrac{3}{12}$, but no work is shown.` },
      { credits: 0, criteria: "A zero response does not contain enough relevant course-level work to receive any credit, does not satisfy the criteria for one or more credits, or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "ove-cr-0824-q28",
    mode: "self-score",
    standard: "AI-A.REI.3",
    topic: "Solving linear equations — decimal coefficients",
    examCitation: "regents-algI-0824-q28",
    part: "II",
    credits: 2,
    prompt: String.raw`Solve algebraically for $x$:  $0.05(x - 3) = 0.35x - 7.5$`,
    answerSummary: String.raw`$x = 24.5$`,
    modelSolution: String.raw`Multiply every term by $20$ to clear decimals: $(x - 3) = 7x - 150$. Subtract $x$ and add $150$: $147 = 6x$, so $x = 24.5$. (Equivalently, distribute: $0.05x - 0.15 = 0.35x - 7.5$, giving $7.35 = 0.3x$ and $x = 24.5$.)`,
    rubric: [
      { credits: 2, criteria: String.raw`$24.5$, and correct algebraic work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but one conceptual error is made. OR Appropriate work is shown, but a method other than algebraic is used. OR $24.5$, but no work is shown.` },
      { credits: 0, criteria: "A zero response does not contain enough relevant course-level work to receive any credit, does not satisfy the criteria for one or more credits, or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "ove-cr-0623-q25",
    mode: "self-score",
    standard: "AI-A.REI.3",
    topic: "Solving linear equations — decimal coefficients",
    examCitation: "regents-algI-0623-q25",
    part: "II",
    credits: 2,
    prompt: String.raw`Solve the equation algebraically for $x$:  $-2.4(x + 1.4) = 6.8x - 22.68$`,
    answerSummary: String.raw`$x = 2.1$`,
    modelSolution: String.raw`Distribute the $-2.4$: $-2.4x - 3.36 = 6.8x - 22.68$. Add $2.4x$ and $22.68$ to both sides: $19.32 = 9.2x$. Divide by $9.2$: $x = 2.1$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$2.1$, and correct algebraic work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but one conceptual error is made. OR $2.1$, but a method other than algebraic is used. OR $2.1$, but no work is shown.` },
      { credits: 0, criteria: "A zero response does not contain enough relevant course-level work to receive any credit, does not satisfy the criteria for one or more credits, or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "ove-cr-0618-q30",
    mode: "self-score",
    standard: "AI-A.REI.3",
    topic: "Solving linear equations — fractional coefficient, exact value",
    examCitation: "regents-algI-0618-q30",
    part: "II",
    credits: 2,
    prompt: String.raw`Solve the equation below algebraically for the exact value of $x$.

$$6 - \dfrac{2}{3}(x + 5) = 4x$$`,
    answerSummary: String.raw`$x = \dfrac{8}{14} = \dfrac{4}{7}$`,
    modelSolution: String.raw`Multiply every term by $3$ to clear the fraction: $18 - 2(x + 5) = 12x$. Distribute: $18 - 2x - 10 = 12x$, so $8 - 2x = 12x$. Add $2x$: $8 = 14x$, giving $x = \dfrac{8}{14} = \dfrac{4}{7}$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$\dfrac{8}{14}$ or $0.\overline{571428}$, or an equivalent fraction, and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational or rounding error is made. OR Appropriate work is shown, but one conceptual error is made. OR $\dfrac{8}{14}$, but no work is shown.` },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "ove-cr-0619-q25",
    mode: "self-score",
    standard: "AI-A.REI.3",
    topic: "Solving linear equations — fractional coefficients, variables on both sides",
    examCitation: "regents-algI-0619-q25",
    part: "II",
    credits: 2,
    prompt: String.raw`Solve algebraically for $x$:

$$-\dfrac{2}{3}(x + 12) + \dfrac{2}{3}x = -\dfrac{5}{4}x + 2$$`,
    answerSummary: String.raw`$x = 8$`,
    modelSolution: String.raw`On the left, $-\dfrac{2}{3}(x + 12) + \dfrac{2}{3}x = -\dfrac{2}{3}x - 8 + \dfrac{2}{3}x = -8$. So the equation is $-8 = -\dfrac{5}{4}x + 2$. Subtract $2$: $-10 = -\dfrac{5}{4}x$. Multiply by $-\dfrac{4}{5}$: $x = 8$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$8$, and correct algebraic work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but one conceptual error is made. OR $8$, but a method other than algebraic is used. OR $8$, but no work is shown.` },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },

  // ---- Writing and solving an equation from a context (AI-A.CED.1) ----
  {
    id: "ove-cr-0115-q31",
    mode: "self-score",
    standard: "AI-A.CED.1",
    topic: "Creating equations — set up and solve a 'when equal' model",
    examCitation: "regents-algI-0115-q31",
    part: "II",
    credits: 2,
    prompt: String.raw`A gardener is planting two types of trees:

Type $A$ is three feet tall and grows at a rate of $15$ inches per year.

Type $B$ is four feet tall and grows at a rate of $10$ inches per year.

Algebraically determine exactly how many years it will take for these trees to be the same height.`,
    answerSummary: String.raw`$x = \dfrac{12}{5} = 2.4$ years`,
    modelSolution: String.raw`Work in inches: Type $A$ starts at $3 \text{ ft} = 36$ in, so its height after $x$ years is $36 + 15x$; Type $B$ starts at $4 \text{ ft} = 48$ in, so its height is $48 + 10x$. Set them equal: $36 + 15x = 48 + 10x$. Subtract $10x$ and $36$: $5x = 12$, so $x = \dfrac{12}{5} = 2.4$ years.`,
    rubric: [
      { credits: 2, criteria: String.raw`$\dfrac{12}{5}$ or $2.4$, and correct algebraic work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but one conceptual error is made. OR $\dfrac{12}{5}$ or $2.4$, but a method other than algebraic is used. OR $\dfrac{12}{5}$ or $2.4$, but no work is shown.` },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "ove-cr-0621-q34",
    mode: "self-score",
    standard: "AI-A.CED.1",
    topic: "Creating equations — write an equation and solve (purchase model)",
    examCitation: "regents-algI-0621-q34",
    part: "III",
    credits: 4,
    prompt: String.raw`Hannah went to the school store to buy supplies and spent \$16. She bought four more pencils than pens and two fewer erasers than pens. Pens cost \$1.25 each, pencils cost \$0.55 each, and erasers cost \$0.75 each. If $x$ represents the number of pens Hannah bought, write an equation in terms of $x$ that can be used to find how many of each item she bought. Use your equation to determine algebraically how many pens Hannah bought.`,
    answerSummary: String.raw`$1.25x + 0.55(x + 4) + 0.75(x - 2) = 16$; Hannah bought $6$ pens.`,
    modelSolution: String.raw`Let $x$ be the number of pens. Then she bought $x + 4$ pencils and $x - 2$ erasers. The total cost is $$1.25x + 0.55(x + 4) + 0.75(x - 2) = 16.$$ Distribute: $1.25x + 0.55x + 2.2 + 0.75x - 1.5 = 16$, so $2.55x + 0.7 = 16$. Subtract $0.7$: $2.55x = 15.3$, giving $x = 6$. Hannah bought $6$ pens.`,
    rubric: [
      { credits: 4, criteria: String.raw`$1.25x + .55(x + 4) + .75(x - 2) = 16$, and $6$, and correct work is shown.` },
      { credits: 3, criteria: String.raw`Appropriate work is shown, but one computational error is made. OR A correct equation is written, but a method other than algebraic is used to find $6$.` },
      { credits: 2, criteria: String.raw`Appropriate work is shown, but two or more computational errors are made. OR $1.25x + .55(x + 4) + .75(x - 2) = 16$ is written, but no further correct work is shown.` },
      { credits: 1, criteria: String.raw`$6$ is found, but a method other than algebraic is used, and no further correct work is shown. OR $6$, but no work is shown.` },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "ove-cr-0117-q37",
    mode: "self-score",
    standard: "AI-A.CED.1",
    topic: "Creating equations — model, solve, and justify a claim",
    examCitation: "regents-algI-0117-q37",
    part: "IV",
    credits: 6,
    prompt: String.raw`Ian is borrowing \$1000 from his parents to buy a notebook computer. He plans to pay them back at the rate of \$60 per month. Ken is borrowing \$600 from his parents to purchase a snowboard. He plans to pay his parents back at the rate of \$20 per month.

Write an equation that can be used to determine after how many months the boys will owe the same amount. Determine algebraically and state in how many months the two boys will owe the same amount. State the amount they will owe at this time.

Ian claims that he will have his loan paid off $6$ months after he and Ken owe the same amount. Determine and state if Ian is correct. Explain your reasoning.`,
    answerSummary: String.raw`$1000 - 60x = 600 - 20x$; equal after $10$ months, when each owes \$400. Ian is incorrect.`,
    modelSolution: String.raw`After $x$ months, Ian owes $1000 - 60x$ and Ken owes $600 - 20x$. Setting them equal: $$1000 - 60x = 600 - 20x.$$ Add $60x$ and subtract $600$: $400 = 40x$, so $x = 10$ months. The amount owed then is $1000 - 60(10) = 400$ (and $600 - 20(10) = 400$), so each boy owes \$400 after $10$ months.

Ian's claim: $6$ months after they are equal is month $16$. At month $16$, Ian owes $1000 - 60(16) = 1000 - 960 = 40$. Since this is not \$0, his loan is not paid off, so Ian is incorrect. (Ian's loan is not fully repaid until $1000 - 60x = 0$, i.e., after $16\tfrac{2}{3}$ months.)`,
    rubric: [
      { credits: 6, criteria: String.raw`A correct equation is written and solved algebraically, $10$, $400$, and a correct explanation stating that Ian is not correct is given.` },
      { credits: 5, criteria: String.raw`Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but the explanation is incomplete.` },
      { credits: 4, criteria: String.raw`Appropriate work is shown, but two computational errors are made. OR Appropriate work is shown, but one conceptual error is made. OR Appropriate work is shown to find $10$ and $400$, but no further correct work is shown. OR Appropriate work is shown, but the explanation is missing or incorrect.` },
      { credits: 3, criteria: String.raw`Appropriate work is shown, but three or more computational errors are made. OR Appropriate work is shown to find either $10$ or $400$, but no further correct work is shown. OR Appropriate work is shown, but one conceptual error and one computational error are made.` },
      { credits: 2, criteria: String.raw`Appropriate work is shown, but one conceptual error and two or more computational errors are made. OR Appropriate work is shown, but two conceptual errors are made. OR A correct equation is written, but no further correct work is shown. OR Appropriate work is shown to determine that Ian is incorrect, and a correct explanation is given, but no further correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but two conceptual errors and one computational error are made. OR Two correct individual equations are written for Ian and Ken, but no further correct work is shown. OR $10$ and $400$, but no work is shown.` },
      { credits: 0, criteria: "Ian is incorrect, but no work is shown. OR A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
];

export default bank;
