// Authored Regents problem-bank — Polynomial Operations (AI-A.APR.1): adding and
// subtracting polynomials. Real released Next Generation Algebra I Regents
// questions, cited to the administration. Answers independently verified;
// SME-ratified. Math is inline LaTeX (String.raw so backslashes survive).

import type { RegentsItem } from "@/lib/regents/bank";

const bank: RegentsItem[] = [
  {
    id: "poly-mc-0624-q4",
    mode: "mc",
    standard: "AI-A.APR.1",
    topic: "Adding & subtracting polynomials",
    examCitation: "regents-algI-0624-q4",
    part: "I",
    credits: 2,
    prompt: String.raw`The expression $-2(x^2 - 2x + 1) + (3x^2 + 3x - 5)$ is equivalent to`,
    choices: [
      String.raw`$x^2 + x - 4$`,
      String.raw`$x^2 - x - 7$`,
      String.raw`$x^2 + 7x - 4$`,
      String.raw`$x^2 + 7x - 7$`,
    ],
    answer: 3,
    explanation: String.raw`Distribute the $-2$ to get $-2x^2 + 4x - 2$, then add $3x^2 + 3x - 5$: $(-2+3)x^2 + (4+3)x + (-2-5) = x^2 + 7x - 7$.`,
  },
  {
    id: "poly-mc-0824-q3",
    mode: "mc",
    standard: "AI-A.APR.1",
    topic: "Adding & subtracting polynomials",
    examCitation: "regents-algI-0824-q3",
    part: "I",
    credits: 2,
    prompt: String.raw`Which expression is equivalent to $3(x^2 - 2x + 3) - (4x^2 + 3x - 1)$?`,
    choices: [
      String.raw`$-x^2 + x + 2$`,
      String.raw`$-x^2 - 8x + 7$`,
      String.raw`$-x^2 - 3x + 8$`,
      String.raw`$-x^2 - 9x + 10$`,
    ],
    answer: 3,
    explanation: String.raw`Distribute to get $3x^2 - 6x + 9$ and $-4x^2 - 3x + 1$, then combine: $(3-4)x^2 + (-6-3)x + (9+1) = -x^2 - 9x + 10$.`,
  },
  {
    id: "poly-mc-0125-q6",
    mode: "mc",
    standard: "AI-A.APR.1",
    topic: "Adding & subtracting polynomials",
    examCitation: "regents-algI-0125-q6",
    part: "I",
    credits: 2,
    prompt: String.raw`Which expression is equivalent to $(5x^2 - 2x + 4) - (3x^2 + 3x - 1)$?`,
    choices: [
      String.raw`$2x^2 + x + 3$`,
      String.raw`$2x^2 - 5x + 5$`,
      String.raw`$2x^4 + x^2 + 3$`,
      String.raw`$2x^4 - 5x^2 + 5$`,
    ],
    answer: 1,
    explanation: String.raw`Subtract term by term: $(5-3)x^2 + (-2-3)x + (4+1) = 2x^2 - 5x + 5$. Subtracting does not change the exponents, so the $x^4$ options are traps.`,
  },
  {
    id: "poly-mc-0625-q6",
    mode: "mc",
    standard: "AI-A.APR.1",
    topic: "Adding & subtracting polynomials",
    examCitation: "regents-algI-0625-q6",
    part: "I",
    credits: 2,
    prompt: String.raw`The expression $(-3x^2 + 9) - (7x^2 - 5x + 4)$ is equivalent to`,
    choices: [
      String.raw`$-10x^2 + 5x + 5$`,
      String.raw`$-10x^2 + 5x + 13$`,
      String.raw`$-10x^2 - 5x + 5$`,
      String.raw`$-10x^2 - 5x + 13$`,
    ],
    answer: 0,
    explanation: String.raw`Distribute the subtraction: $-3x^2 + 9 - 7x^2 + 5x - 4 = -10x^2 + 5x + 5$.`,
  },
  {
    id: "poly-mc-0126-q22",
    mode: "mc",
    standard: "AI-A.APR.1",
    topic: "Adding & subtracting polynomials",
    examCitation: "regents-algI-0126-q22",
    part: "I",
    credits: 2,
    prompt: String.raw`When $2x^2 - 3x + 4$ is subtracted from $x^2 + 2x - 5$, the result is`,
    choices: [
      String.raw`$x^2 - 5x + 9$`,
      String.raw`$x^2 - x + 1$`,
      String.raw`$-x^2 + 5x - 9$`,
      String.raw`$-x^2 - x - 1$`,
    ],
    answer: 2,
    explanation: String.raw`"Subtracted from" means $(x^2 + 2x - 5) - (2x^2 - 3x + 4) = x^2 + 2x - 5 - 2x^2 + 3x - 4 = -x^2 + 5x - 9$.`,
  },
  {
    id: "poly-cr-0126-q27",
    mode: "self-score",
    standard: "AI-A.APR.1",
    topic: "Multiplying polynomials",
    examCitation: "regents-algI-0126-q27",
    part: "II",
    credits: 2,
    prompt: String.raw`Determine the product of $(2x + 3)$ and $(-6x^2 + 5x - 1)$. Express the product in standard form.`,
    answerSummary: String.raw`$-12x^3 - 8x^2 + 13x - 3$`,
    modelSolution: String.raw`Distribute each term of $(2x + 3)$: $2x(-6x^2 + 5x - 1) = -12x^3 + 10x^2 - 2x$ and $3(-6x^2 + 5x - 1) = -18x^2 + 15x - 3$. Combine like terms: $-12x^3 + (10 - 18)x^2 + (-2 + 15)x - 3 = -12x^3 - 8x^2 + 13x - 3$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$-12x^3 - 8x^2 + 13x - 3$, with correct work shown.` },
      { credits: 1, criteria: "Appropriate work, but one computational error; OR one conceptual error; OR the product is not expressed in standard form." },
      { credits: 0, criteria: "A response with no relevant course-level work." },
    ],
  },

  // ——— Multiplying polynomials (distribute / FOIL, then combine like terms) ———
  {
    id: "poly-mc-0823-q08",
    mode: "mc",
    standard: "AI-A.APR.1",
    topic: "Multiplying binomials",
    examCitation: "regents-algI-0823-q08",
    part: "I",
    credits: 2,
    prompt: String.raw`What is the product of $(2x + 7)$ and $(x - 3)$?`,
    choices: [
      String.raw`$2x^2 - 21$`,
      String.raw`$2x^2 + x - 21$`,
      String.raw`$2x^2 - x - 21$`,
      String.raw`$2x^2 + 13x - 21$`,
    ],
    answer: 1,
    explanation: String.raw`Use the distributive property (FOIL): $(2x)(x) + (2x)(-3) + (7)(x) + (7)(-3) = 2x^2 - 6x + 7x - 21 = 2x^2 + x - 21$.`,
  },
  {
    id: "poly-mc-0621-q08",
    mode: "mc",
    standard: "AI-A.APR.1",
    topic: "Multiplying binomials — standard form",
    examCitation: "regents-algI-0621-q08",
    part: "I",
    credits: 2,
    prompt: String.raw`When written in standard form, the product of $(3 + x)$ and $(2x - 5)$ is`,
    choices: [
      String.raw`$3x - 2$`,
      String.raw`$2x^2 + x - 15$`,
      String.raw`$2x^2 - 11x - 15$`,
      String.raw`$6x - 15 + 2x^2 - 5x$`,
    ],
    answer: 1,
    explanation: String.raw`$(3 + x)(2x - 5) = 6x - 15 + 2x^2 - 5x$. Combine like terms and order by descending power: $2x^2 + x - 15$. (Choice 4 is the right product but not in standard form.)`,
  },
  {
    id: "poly-mc-0624-q19",
    mode: "mc",
    standard: "AI-A.APR.1",
    topic: "Multiply, then subtract",
    examCitation: "regents-algI-0624-q19",
    part: "I",
    credits: 2,
    prompt: String.raw`Which expression is equivalent to $(x - 5)(2x + 7) - (x + 5)$?`,
    choices: [
      String.raw`$2x^2 - 2x - 30$`,
      String.raw`$2x^2 - 2x - 40$`,
      String.raw`$2x^2 - 4x - 30$`,
      String.raw`$2x^2 - 4x - 40$`,
    ],
    answer: 3,
    explanation: String.raw`First the product: $(x - 5)(2x + 7) = 2x^2 + 7x - 10x - 35 = 2x^2 - 3x - 35$. Then subtract $(x + 5)$: $2x^2 - 3x - 35 - x - 5 = 2x^2 - 4x - 40$.`,
  },
  {
    id: "poly-mc-0815-q24",
    mode: "mc",
    standard: "AI-A.APR.1",
    topic: "Square a binomial, then distribute",
    examCitation: "regents-algI-0815-q24",
    part: "I",
    credits: 2,
    prompt: String.raw`Which trinomial is equivalent to $3(x - 2)^2 - 2(x - 1)$?`,
    choices: [
      String.raw`$3x^2 - 2x - 10$`,
      String.raw`$3x^2 - 2x - 14$`,
      String.raw`$3x^2 - 14x + 10$`,
      String.raw`$3x^2 - 14x + 14$`,
    ],
    answer: 3,
    explanation: String.raw`Square first: $(x - 2)^2 = x^2 - 4x + 4$, so $3(x - 2)^2 = 3x^2 - 12x + 12$. Then $-2(x - 1) = -2x + 2$. Combine: $3x^2 - 12x + 12 - 2x + 2 = 3x^2 - 14x + 14$.`,
  },
  {
    id: "poly-mc-0124-q15",
    mode: "mc",
    standard: "AI-A.APR.1",
    topic: "Multiplying a trinomial by a binomial",
    examCitation: "regents-algI-0124-q15",
    part: "I",
    credits: 2,
    prompt: String.raw`The product of $(x^2 + 3x + 9)$ and $(x - 3)$ is`,
    choices: [
      String.raw`$x^3 - 27$`,
      String.raw`$x^2 + 4x + 6$`,
      String.raw`$x^3 - 6x^2 - 18x - 27$`,
      String.raw`$-6x^4 + x^3 - 18x^2 - 27$`,
    ],
    answer: 0,
    explanation: String.raw`Distribute: $x^2(x - 3) + 3x(x - 3) + 9(x - 3) = (x^3 - 3x^2) + (3x^2 - 9x) + (9x - 27)$. The middle terms cancel: $x^3 - 27$.`,
  },
  {
    id: "poly-mc-0816-q12",
    mode: "mc",
    standard: "AI-A.APR.1",
    topic: "Multiplying a binomial by a trinomial",
    examCitation: "regents-algI-0816-q12",
    part: "I",
    credits: 2,
    prompt: String.raw`What is the product of $2x + 3$ and $4x^2 - 5x + 6$?`,
    choices: [
      String.raw`$8x^3 - 2x^2 + 3x + 18$`,
      String.raw`$8x^3 - 2x^2 - 3x + 18$`,
      String.raw`$8x^3 + 2x^2 - 3x + 18$`,
      String.raw`$8x^3 + 2x^2 + 3x + 18$`,
    ],
    answer: 2,
    explanation: String.raw`$2x(4x^2 - 5x + 6) = 8x^3 - 10x^2 + 12x$ and $3(4x^2 - 5x + 6) = 12x^2 - 15x + 18$. Combine: $8x^3 + (-10 + 12)x^2 + (12 - 15)x + 18 = 8x^3 + 2x^2 - 3x + 18$.`,
  },
  {
    id: "poly-mc-0824-q17",
    mode: "mc",
    standard: "AI-A.APR.1",
    topic: "Multiplying polynomials — substitution",
    examCitation: "regents-algI-0824-q17",
    part: "I",
    credits: 2,
    prompt: String.raw`If $x = 4a^2 - a + 3$ and $y = a - 5$, then which polynomial is equivalent to the product of $x$ and $y$?`,
    choices: [
      String.raw`$-17a^2 - 2a - 15$`,
      String.raw`$-17a^2 + 8a - 15$`,
      String.raw`$4a^3 - 21a^2 - 2a - 15$`,
      String.raw`$4a^3 - 21a^2 + 8a - 15$`,
    ],
    answer: 3,
    explanation: String.raw`$(4a^2 - a + 3)(a - 5) = (4a^3 - 20a^2) + (-a^2 + 5a) + (3a - 15) = 4a^3 - 21a^2 + 8a - 15$.`,
  },

  // ——— More adding & subtracting (distribute, then combine like terms) ———
  {
    id: "poly-mc-0621-q02",
    mode: "mc",
    standard: "AI-A.APR.1",
    topic: "Adding & subtracting polynomials",
    examCitation: "regents-algI-0621-q02",
    part: "I",
    credits: 2,
    prompt: String.raw`The expression $3(x + 4) - (2x + 7)$ is equivalent to`,
    choices: [
      String.raw`$x + 5$`,
      String.raw`$x - 10$`,
      String.raw`$x - 3$`,
      String.raw`$x + 11$`,
    ],
    answer: 0,
    explanation: String.raw`Distribute the $3$ and the subtraction: $3x + 12 - 2x - 7$. Combine like terms: $(3 - 2)x + (12 - 7) = x + 5$.`,
  },
  {
    id: "poly-mc-0117-q07",
    mode: "mc",
    standard: "AI-A.APR.1",
    topic: "Adding & subtracting polynomials",
    examCitation: "regents-algI-0117-q07",
    part: "I",
    credits: 2,
    prompt: String.raw`Which expression is equivalent to $2(3g - 4) - (8g + 3)$?`,
    choices: [
      String.raw`$-2g - 1$`,
      String.raw`$-2g - 5$`,
      String.raw`$-2g - 7$`,
      String.raw`$-2g - 11$`,
    ],
    answer: 3,
    explanation: String.raw`Distribute: $6g - 8 - 8g - 3$. Combine like terms: $(6 - 8)g + (-8 - 3) = -2g - 11$.`,
  },
  {
    id: "poly-mc-0124-q06",
    mode: "mc",
    standard: "AI-A.APR.1",
    topic: "Adding & subtracting polynomials",
    examCitation: "regents-algI-0124-q06",
    part: "I",
    credits: 2,
    prompt: String.raw`The expression $(-x^2 + 3x - 7) - (4x^2 + 5x - 2)$ is equivalent to`,
    choices: [
      String.raw`$-5x^2 - 2x - 9$`,
      String.raw`$-5x^2 - 2x - 5$`,
      String.raw`$-5x^2 + 8x - 9$`,
      String.raw`$-5x^2 + 8x - 5$`,
    ],
    answer: 1,
    explanation: String.raw`Distribute the subtraction: $-x^2 + 3x - 7 - 4x^2 - 5x + 2 = (-1 - 4)x^2 + (3 - 5)x + (-7 + 2) = -5x^2 - 2x - 5$.`,
  },
  {
    id: "poly-mc-0618-q03",
    mode: "mc",
    standard: "AI-A.APR.1",
    topic: "Adding & subtracting polynomials",
    examCitation: "regents-algI-0618-q03",
    part: "I",
    credits: 2,
    prompt: String.raw`The expression $3(x^2 + 2x - 3) - 4(4x^2 - 7x + 5)$ is equivalent to`,
    choices: [
      String.raw`$-13x^2 - 22x + 11$`,
      String.raw`$-13x^2 + 34x - 29$`,
      String.raw`$19x^2 - 22x + 11$`,
      String.raw`$19x^2 + 34x - 29$`,
    ],
    answer: 1,
    explanation: String.raw`Distribute both: $3(x^2 + 2x - 3) = 3x^2 + 6x - 9$ and $-4(4x^2 - 7x + 5) = -16x^2 + 28x - 20$. Combine: $(3 - 16)x^2 + (6 + 28)x + (-9 - 20) = -13x^2 + 34x - 29$.`,
  },

  // ——— More multiplying (square a binomial, sum of squares, monomial × trinomial) ———
  {
    id: "poly-mc-0622-q17",
    mode: "mc",
    standard: "AI-A.APR.1",
    topic: "Squaring a binomial",
    examCitation: "regents-algI-0622-q17",
    part: "I",
    credits: 2,
    prompt: String.raw`The expression $(m - 3)^2$ is equivalent to`,
    choices: [
      String.raw`$m^2 + 9$`,
      String.raw`$m^2 - 9$`,
      String.raw`$m^2 - 6m + 9$`,
      String.raw`$m^2 - 6m - 9$`,
    ],
    answer: 2,
    explanation: String.raw`$(m - 3)^2 = (m - 3)(m - 3) = m^2 - 3m - 3m + 9 = m^2 - 6m + 9$. Squaring a binomial is not squaring each term — the middle term $-6m$ matters.`,
  },
  {
    id: "poly-mc-0825-q19",
    mode: "mc",
    standard: "AI-A.APR.1",
    topic: "Squaring binomials, then adding",
    examCitation: "regents-algI-0825-q19",
    part: "I",
    credits: 2,
    prompt: String.raw`The sum of $(x + 7)^2$ and $(x - 3)^2$ is`,
    choices: [
      String.raw`$2x^2 + 58$`,
      String.raw`$2x^4 + 58$`,
      String.raw`$2x^2 + 8x + 58$`,
      String.raw`$2x^4 + 8x^2 + 58$`,
    ],
    answer: 2,
    explanation: String.raw`Expand each square: $(x + 7)^2 = x^2 + 14x + 49$ and $(x - 3)^2 = x^2 - 6x + 9$. Add: $(x^2 + x^2) + (14x - 6x) + (49 + 9) = 2x^2 + 8x + 58$.`,
  },
  {
    id: "poly-mc-0822-q06",
    mode: "mc",
    standard: "AI-A.APR.1",
    topic: "Multiplying a monomial by a trinomial",
    examCitation: "regents-algI-0822-q06",
    part: "I",
    credits: 2,
    prompt: String.raw`The expression $\frac{1}{3}x(6x^2 - 3x + 9)$ is equivalent to`,
    choices: [
      String.raw`$2x^2 - x + 3$`,
      String.raw`$2x^2 + 3x + 3$`,
      String.raw`$2x^3 - x^2 + 3x$`,
      String.raw`$2x^3 + 3x^2 + 3x$`,
    ],
    answer: 2,
    explanation: String.raw`Distribute $\frac{1}{3}x$ to each term: $\frac{1}{3}x \cdot 6x^2 = 2x^3$, $\frac{1}{3}x \cdot (-3x) = -x^2$, and $\frac{1}{3}x \cdot 9 = 3x$, giving $2x^3 - x^2 + 3x$.`,
  },
  {
    id: "poly-mc-0115-q10",
    mode: "mc",
    standard: "AI-A.APR.1",
    topic: "Multiplying binomials — area model",
    examCitation: "regents-algI-0115-q10",
    part: "I",
    credits: 2,
    prompt: String.raw`Fred is given a rectangular piece of paper. If the length of Fred's piece of paper is represented by $2x - 6$ and the width is represented by $3x - 5$, then the paper has a total area represented by`,
    choices: [
      String.raw`$5x - 11$`,
      String.raw`$6x^2 - 28x + 30$`,
      String.raw`$10x - 22$`,
      String.raw`$6x^2 - 6x - 11$`,
    ],
    answer: 1,
    explanation: String.raw`Area $=$ length $\times$ width $= (2x - 6)(3x - 5) = 6x^2 - 10x - 18x + 30 = 6x^2 - 28x + 30$. (Choices 1 and 3 add the sides instead of multiplying.)`,
  },

  // ——— Constructed response: express the sum / difference / product in standard form ———
  {
    id: "poly-cr-0617-q25",
    mode: "self-score",
    standard: "AI-A.APR.1",
    topic: "Subtracting polynomials",
    examCitation: "regents-algI-0617-q25",
    part: "II",
    credits: 2,
    prompt: String.raw`Express in simplest form: $(3x^2 + 4x - 8) - (-2x^2 + 4x + 2)$`,
    answerSummary: String.raw`$5x^2 - 10$`,
    modelSolution: String.raw`Distribute the subtraction across the second polynomial: $3x^2 + 4x - 8 + 2x^2 - 4x - 2$. Combine like terms: $(3 + 2)x^2 + (4 - 4)x + (-8 - 2) = 5x^2 - 10$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$5x^2 - 10$ or $5(x^2 - 2)$, and appropriate work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but one conceptual error is made. OR $5x^2 - 10$, but no work is shown.` },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "poly-cr-0115-q28",
    mode: "self-score",
    standard: "AI-A.APR.1",
    topic: "Subtracting polynomials",
    examCitation: "regents-algI-0115-q28",
    part: "II",
    credits: 2,
    prompt: String.raw`Subtract $5x^2 + 2x - 11$ from $3x^2 + 8x - 7$. Express the result as a trinomial.`,
    answerSummary: String.raw`$-2x^2 + 6x + 4$`,
    modelSolution: String.raw`"Subtract … from …" means $(3x^2 + 8x - 7) - (5x^2 + 2x - 11)$. Distribute the subtraction: $3x^2 + 8x - 7 - 5x^2 - 2x + 11 = -2x^2 + 6x + 4$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$-2x^2 + 6x + 4$ or equivalent trinomial, and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but one conceptual error is made. OR $-2x^2 + 6x + 4$, but no work is shown.` },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "poly-cr-0619-q26",
    mode: "self-score",
    standard: "AI-A.APR.1",
    topic: "Combining polynomials with substitution",
    examCitation: "regents-algI-0619-q26",
    part: "II",
    credits: 2,
    prompt: String.raw`If $C = G - 3F$, find the trinomial that represents $C$ when $F = 2x^2 + 6x - 5$ and $G = 3x^2 + 4$.`,
    answerSummary: String.raw`$-3x^2 - 18x + 19$`,
    modelSolution: String.raw`Substitute: $C = (3x^2 + 4) - 3(2x^2 + 6x - 5)$. Distribute: $3x^2 + 4 - 6x^2 - 18x + 15$. Combine like terms: $-3x^2 - 18x + 19$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$-3x^2 - 18x + 19$ or an equivalent trinomial, and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but one conceptual error is made. OR Appropriate work is shown to find $3x^2 + 4 - 6x^2 - 18x + 15$, but no further correct work is shown. OR $-3x^2 - 18x + 19$, but no work is shown.` },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "poly-cr-0622-q28",
    mode: "self-score",
    standard: "AI-A.APR.1",
    topic: "Multiplying then subtracting polynomials",
    examCitation: "regents-algI-0622-q28",
    part: "II",
    credits: 2,
    prompt: String.raw`Subtract $3x(x - 2y)$ from $6(x^2 - xy)$ and express your answer as a monomial.`,
    answerSummary: String.raw`$3x^2$`,
    modelSolution: String.raw`Expand each: $6(x^2 - xy) = 6x^2 - 6xy$ and $3x(x - 2y) = 3x^2 - 6xy$. Subtract: $(6x^2 - 6xy) - (3x^2 - 6xy) = 6x^2 - 6xy - 3x^2 + 6xy = 3x^2$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$3x^2$, and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational or simplification error is made. OR Appropriate work is shown, but one conceptual error is made. OR Appropriate work is shown, but the answer is not written as a monomial. OR $3x^2$, but no work is shown.` },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "poly-cr-0817-q31",
    mode: "self-score",
    standard: "AI-A.APR.1",
    topic: "Multiplying then combining like terms",
    examCitation: "regents-algI-0817-q31",
    part: "II",
    credits: 2,
    prompt: String.raw`Write the expression $5x + 4x^2(2x + 7) - 6x^2 - 9x$ as a polynomial in standard form.`,
    answerSummary: String.raw`$8x^3 + 22x^2 - 4x$`,
    modelSolution: String.raw`Distribute $4x^2(2x + 7) = 8x^3 + 28x^2$. Substitute back: $5x + 8x^3 + 28x^2 - 6x^2 - 9x$. Combine like terms: $8x^3 + (28 - 6)x^2 + (5 - 9)x = 8x^3 + 22x^2 - 4x$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$8x^3 + 22x^2 - 4x$, and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational or simplification error is made. OR Appropriate work is shown, but one conceptual error is made. OR Appropriate work is shown, but the trinomial is not written in standard form. OR $8x^3 + 22x^2 - 4x$, but no work is shown.` },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "poly-cr-0615-q28",
    mode: "self-score",
    standard: "AI-A.APR.1",
    topic: "Difference of polynomials, times a monomial",
    examCitation: "regents-algI-0615-q28",
    part: "II",
    credits: 2,
    prompt: String.raw`If the difference $(3x^2 - 2x + 5) - (x^2 + 3x - 2)$ is multiplied by $\frac{1}{2}x^2$, what is the result, written in standard form?`,
    answerSummary: String.raw`$x^4 - \frac{5}{2}x^3 + \frac{7}{2}x^2$`,
    modelSolution: String.raw`First the difference: $(3x^2 - 2x + 5) - (x^2 + 3x - 2) = 2x^2 - 5x + 7$. Multiply by $\frac{1}{2}x^2$: $\frac{1}{2}x^2(2x^2 - 5x + 7) = x^4 - \frac{5}{2}x^3 + \frac{7}{2}x^2$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$x^4 - \frac{5}{2}x^3 + \frac{7}{2}x^2$, and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but one conceptual error is made. OR Appropriate work is shown to find a correct expression, but the expression is not in standard form. OR $x^4 - \frac{5}{2}x^3 + \frac{7}{2}x^2$, but no work is shown.` },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "poly-cr-0623-q29",
    mode: "self-score",
    standard: "AI-A.APR.1",
    topic: "Squaring a binomial, then adding",
    examCitation: "regents-algI-0623-q29",
    part: "II",
    credits: 2,
    prompt: String.raw`Given: $A = x + 5$ and $B = x^2 - 18$. Express $A^2 + B$ in standard form.`,
    answerSummary: String.raw`$2x^2 + 10x + 7$`,
    modelSolution: String.raw`$A^2 = (x + 5)^2 = x^2 + 10x + 25$. Add $B$: $(x^2 + 10x + 25) + (x^2 - 18) = 2x^2 + 10x + 7$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$2x^2 + 10x + 7$, and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but one conceptual error is made. OR Appropriate work is shown, but the expression is not written in standard form. OR Appropriate work is shown to find $x^2 + 10x + 25$, but no further correct work is shown. OR $2x^2 + 10x + 7$, but no work is shown.` },
      { credits: 0, criteria: "A zero response does not contain enough relevant course-level work to receive any credit, does not satisfy the criteria for one or more credits, or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "poly-cr-0814-q28",
    mode: "self-score",
    standard: "AI-A.APR.1",
    topic: "Multiplying a trinomial by a binomial",
    examCitation: "regents-algI-0814-q28",
    part: "II",
    credits: 2,
    prompt: String.raw`Express the product of $2x^2 + 7x - 10$ and $x + 5$ in standard form.`,
    answerSummary: String.raw`$2x^3 + 17x^2 + 25x - 50$`,
    modelSolution: String.raw`Distribute each term of $(x + 5)$: $(2x^2 + 7x - 10)(x + 5) = 2x^3 + 10x^2 + 7x^2 + 35x - 10x - 50 = 2x^3 + 17x^2 + 25x - 50$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$2x^3 + 17x^2 + 25x - 50$ and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but one conceptual error is made. OR Appropriate work is shown, but the product is not written in standard form. OR $2x^3 + 17x^2 + 25x - 50$, but no work is shown.` },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "poly-cr-0120-q28",
    mode: "self-score",
    standard: "AI-A.APR.1",
    topic: "Multiplying binomials, then subtracting",
    examCitation: "regents-algI-0120-q28",
    part: "II",
    credits: 2,
    prompt: String.raw`Express $(3x - 4)(x + 7) - \frac{1}{4}x^2$ as a trinomial in standard form.`,
    answerSummary: String.raw`$\frac{11}{4}x^2 + 17x - 28$`,
    modelSolution: String.raw`Multiply the binomials: $(3x - 4)(x + 7) = 3x^2 + 21x - 4x - 28 = 3x^2 + 17x - 28$. Subtract $\frac{1}{4}x^2$: $\left(3 - \frac{1}{4}\right)x^2 + 17x - 28 = \frac{11}{4}x^2 + 17x - 28$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$\frac{11}{4}x^2 + 17x - 28$ or an equivalent expression in standard form is written, and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but one conceptual error is made. OR Appropriate work is shown, but the answer is not in standard form. OR $\frac{11}{4}x^2 + 17x - 28$, but no work is shown.` },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
];

export default bank;
