// Authored Regents problem-bank — Quadratic Functions & Graphs: the *features* of
// a parabola (as opposed to merely solving the equation). Three threads:
//   - Zeros / x-intercepts from factored or factorable form (AI-A.APR.3)
//   - Vertex form & max/min — completing the square to reveal the vertex (AI-F.IF.8)
//   - Interpreting a quadratic model's features in context (AI-F.IF.4)
// Real released Algebra I Regents questions mined from the official NYSED
// administrations (via JMAP), cited to the exam + question number. Every answer
// independently re-derived; signs verified against the source PDFs. SME-ratified.

import type { RegentsItem } from "@/lib/regents/bank";

const bank: RegentsItem[] = [
  // ——— Zeros / x-intercepts (AI-A.APR.3) ———
  {
    id: "qfn-mc-0622-q12",
    mode: "mc",
    standard: "AI-A.APR.3",
    topic: "Zeros of a quadratic — factored form",
    examCitation: "regents-algI-0622-q12",
    part: "I",
    credits: 2,
    prompt: String.raw`What are the zeros of $f(x) = (2x - 4)(3x + 4)$?`,
    choices: [
      String.raw`$\left\{-\frac{4}{3}, 2\right\}$`,
      String.raw`$\{-4, 4\}$`,
      String.raw`$\left\{-2, \frac{4}{3}\right\}$`,
      String.raw`$\{-4, 2\}$`,
    ],
    answer: 0,
    explanation: String.raw`A product is $0$ when either factor is $0$: $2x - 4 = 0 \Rightarrow x = 2$, and $3x + 4 = 0 \Rightarrow x = -\frac{4}{3}$.`,
  },
  {
    id: "qfn-mc-0618-q04",
    mode: "mc",
    standard: "AI-A.APR.3",
    topic: "Zeros of a quadratic — factor first",
    examCitation: "regents-algI-0618-q04",
    part: "I",
    credits: 2,
    prompt: String.raw`The zeros of the function $p(x) = x^2 - 2x - 24$ are`,
    choices: [
      String.raw`$-8$ and $3$`,
      String.raw`$-6$ and $4$`,
      String.raw`$-4$ and $6$`,
      String.raw`$-3$ and $8$`,
    ],
    answer: 2,
    explanation: String.raw`Factor: $x^2 - 2x - 24 = (x - 6)(x + 4)$ (two numbers that multiply to $-24$ and add to $-2$: $-6$ and $4$). The zeros are $x = 6$ and $x = -4$.`,
  },
  {
    id: "qfn-mc-0815-q13",
    mode: "mc",
    standard: "AI-A.APR.3",
    topic: "Zeros of a quadratic — factor out the GCF first",
    examCitation: "regents-algI-0815-q13",
    part: "I",
    credits: 2,
    prompt: String.raw`The zeros of the function $f(x) = 3x^2 - 3x - 6$ are`,
    choices: [
      String.raw`$-1$ and $-2$`,
      String.raw`$1$ and $-2$`,
      String.raw`$1$ and $2$`,
      String.raw`$-1$ and $2$`,
    ],
    answer: 3,
    explanation: String.raw`Factor out $3$ first: $3(x^2 - x - 2) = 3(x - 2)(x + 1)$. The zeros are $x = 2$ and $x = -1$ (the leading $3$ does not change where the function equals $0$).`,
  },
  {
    id: "qfn-mc-0814-q18",
    mode: "mc",
    standard: "AI-A.APR.3",
    topic: "Zeros of a quadratic — from vertex form",
    examCitation: "regents-algI-0814-q18",
    part: "I",
    credits: 2,
    prompt: String.raw`What are the zeros of $f(x) = (x + 2)^2 - 25$?`,
    choices: [
      String.raw`$-2$ and $5$`,
      String.raw`$-3$ and $7$`,
      String.raw`$-5$ and $2$`,
      String.raw`$-7$ and $3$`,
    ],
    answer: 3,
    explanation: String.raw`Set $f(x) = 0$: $(x + 2)^2 - 25 = 0$, so $(x + 2)^2 = 25$ and $x + 2 = \pm 5$. Then $x = 3$ or $x = -7$.`,
  },

  // ——— Vertex form & max/min — completing the square (AI-F.IF.8) ———
  {
    id: "qfn-mc-0116-q01",
    mode: "mc",
    standard: "AI-F.IF.8",
    topic: "Quadratic functions — minimum from vertex form",
    examCitation: "regents-algI-0116-q01",
    part: "I",
    credits: 2,
    prompt: String.raw`In the function $f(x) = (x - 2)^2 + 4$, the minimum value occurs when $x$ is`,
    choices: [String.raw`$-2$`, String.raw`$2$`, String.raw`$-4$`, String.raw`$4$`],
    answer: 1,
    explanation: String.raw`In vertex form $f(x) = (x - h)^2 + k$, the vertex is $(h, k)$. Here $h = 2$, so the minimum occurs at $x = 2$ (the squared term is smallest, $0$, when $x = 2$).`,
  },
  {
    id: "qfn-mc-0815-q20",
    mode: "mc",
    standard: "AI-F.IF.8",
    topic: "Quadratic functions — completing the square",
    examCitation: "regents-algI-0815-q20",
    part: "I",
    credits: 2,
    prompt: String.raw`To find the minimum of $f(x) = x^2 - 12x + 7$, Lylah writes it in the form $f(x) = (x - a)^2 + b$. What is the value of $a$?`,
    choices: [String.raw`$6$`, String.raw`$-6$`, String.raw`$12$`, String.raw`$-12$`],
    answer: 0,
    explanation: String.raw`Completing the square, $a$ is half the coefficient of $x$: $a = \frac{-12}{2} = -6$, and $(x - a)^2 = (x - 6)^2$ means $a = 6$. (Check: $(x-6)^2 + b = x^2 - 12x + 36 + b$, matching $-12x$.)`,
  },
  {
    id: "qfn-mc-0816-q21",
    mode: "mc",
    standard: "AI-F.IF.8",
    topic: "Quadratic functions — vertex form with a leading coefficient",
    examCitation: "regents-algI-0816-q21",
    part: "I",
    credits: 2,
    prompt: String.raw`The function $f(x) = 3x^2 + 12x + 11$ can be written in vertex form as`,
    choices: [
      String.raw`$f(x) = (3x + 6)^2 - 25$`,
      String.raw`$f(x) = 3(x + 6)^2 - 25$`,
      String.raw`$f(x) = 3(x + 2)^2 - 1$`,
      String.raw`$f(x) = 3(x + 2)^2 + 7$`,
    ],
    answer: 2,
    explanation: String.raw`Factor $3$ from the first two terms: $3(x^2 + 4x) + 11$. Complete the square inside: $3(x^2 + 4x + 4) - 3(4) + 11 = 3(x + 2)^2 - 12 + 11 = 3(x + 2)^2 - 1$.`,
  },
  {
    id: "qfn-mc-0616-q16",
    mode: "mc",
    standard: "AI-F.IF.8",
    topic: "Quadratic functions — vertex form and the vertex",
    examCitation: "regents-algI-0616-q16",
    part: "I",
    credits: 2,
    prompt: String.raw`Which equation and ordered pair represent the correct vertex form and vertex for $j(x) = x^2 - 12x + 7$?`,
    choices: [
      String.raw`$j(x) = (x - 6)^2 + 43,\ (6, 43)$`,
      String.raw`$j(x) = (x - 6)^2 + 43,\ (-6, 43)$`,
      String.raw`$j(x) = (x - 6)^2 - 29,\ (6, -29)$`,
      String.raw`$j(x) = (x - 6)^2 - 29,\ (-6, -29)$`,
    ],
    answer: 2,
    explanation: String.raw`Complete the square: $x^2 - 12x + 36 - 36 + 7 = (x - 6)^2 - 29$. In $(x - h)^2 + k$ the vertex is $(h, k) = (6, -29)$.`,
  },

  // ——— Interpreting a quadratic model's features (AI-F.IF.4) ———
  {
    id: "qfn-mc-0118-q11",
    mode: "mc",
    standard: "AI-F.IF.4",
    topic: "Interpreting a quadratic model — initial value",
    examCitation: "regents-algI-0118-q11",
    part: "I",
    credits: 2,
    prompt: String.raw`The expression $-4.9t^2 + 50t + 2$ represents the height, in meters, of a toy rocket $t$ seconds after launch. The initial height of the rocket, in meters, is`,
    choices: [String.raw`$0$`, String.raw`$2$`, String.raw`$4.9$`, String.raw`$50$`],
    answer: 1,
    explanation: String.raw`The initial height is the value at $t = 0$: $-4.9(0)^2 + 50(0) + 2 = 2$. The constant term is the starting height.`,
  },
  {
    id: "qfn-mc-0119-q13",
    mode: "mc",
    standard: "AI-F.IF.4",
    topic: "Interpreting a quadratic model — meaning of a term",
    examCitation: "regents-algI-0119-q13",
    part: "I",
    credits: 2,
    prompt: String.raw`The height of a ball Doreen tossed into the air is modeled by $h(x) = -4.9x^2 + 6x + 5$, where $x$ is the time in seconds and $h(x)$ is the height in meters. The number $5$ in the function represents`,
    choices: [
      "the initial height of the ball",
      "the time at which the ball reaches the ground",
      "the time at which the ball was at its highest point",
      "the maximum height the ball attained when thrown in the air",
    ],
    answer: 0,
    explanation: String.raw`At $x = 0$ (the moment of the toss), $h(0) = 5$. The constant term is the height when time is $0$ — the initial height.`,
  },
  {
    id: "qfn-mc-0819-q10",
    mode: "mc",
    standard: "AI-F.IF.4",
    topic: "Interpreting a quadratic model — when it hits the ground",
    examCitation: "regents-algI-0819-q10",
    part: "I",
    credits: 2,
    prompt: String.raw`A ball is thrown from the top of a building. Its height, $h(t)$, above the ground $t$ seconds after being thrown is modeled by $h(t) = -16t^2 + 64t + 80$. How many seconds after being thrown will the ball hit the ground?`,
    choices: [String.raw`$5$`, String.raw`$2$`, String.raw`$80$`, String.raw`$144$`],
    answer: 0,
    explanation: String.raw`The ball hits the ground when $h(t) = 0$: $-16t^2 + 64t + 80 = 0$, i.e. $t^2 - 4t - 5 = 0$, so $(t - 5)(t + 1) = 0$. Time can't be negative, so $t = 5$ seconds.`,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // Additional items (deepening pass) — all real released NYSED Regents
  // questions mined via JMAP; choices/signs transcribed from rendered source
  // PDFs and every answer independently re-derived. CR rubrics are VERBATIM
  // from the official NYSED rating guides.
  // ═══════════════════════════════════════════════════════════════════════

  // ——— More: Zeros / x-intercepts (AI-A.APR.3) ———
  {
    id: "qfn-mc-0616-q12",
    mode: "mc",
    standard: "AI-A.APR.3",
    topic: "Zeros of a quadratic — factor first",
    examCitation: "regents-algI-0616-q12",
    part: "I",
    credits: 2,
    prompt: String.raw`The zeros of the function $f(x) = x^2 - 5x - 6$ are`,
    choices: [
      String.raw`$-1$ and $6$`,
      String.raw`$1$ and $-6$`,
      String.raw`$2$ and $-3$`,
      String.raw`$-2$ and $3$`,
    ],
    answer: 0,
    explanation: String.raw`Factor: $x^2 - 5x - 6 = (x + 1)(x - 6)$ (two numbers multiplying to $-6$ and adding to $-5$: $+1$ and $-6$). The zeros are $x = -1$ and $x = 6$.`,
  },
  {
    id: "qfn-mc-0825-q04",
    mode: "mc",
    standard: "AI-A.APR.3",
    topic: "Zeros of a quadratic — factor first",
    examCitation: "regents-algI-0825-q04",
    part: "I",
    credits: 2,
    prompt: String.raw`What are the zeros of $f(x) = x^2 - 8x - 20$?`,
    choices: [
      String.raw`$10$ and $2$`,
      String.raw`$10$ and $-2$`,
      String.raw`$-10$ and $2$`,
      String.raw`$-10$ and $-2$`,
    ],
    answer: 1,
    explanation: String.raw`Factor: $x^2 - 8x - 20 = (x - 10)(x + 2)$ (multiply to $-20$, add to $-8$: $-10$ and $+2$). The zeros are $x = 10$ and $x = -2$.`,
  },
  {
    id: "qfn-mc-0116-q09",
    mode: "mc",
    standard: "AI-A.APR.3",
    topic: "Zeros of a quadratic — factor out the GCF first",
    examCitation: "regents-algI-0116-q09",
    part: "I",
    credits: 2,
    prompt: String.raw`The zeros of the function $f(x) = 2x^2 - 4x - 6$ are`,
    choices: [
      String.raw`$3$ and $-1$`,
      String.raw`$3$ and $1$`,
      String.raw`$-3$ and $1$`,
      String.raw`$-3$ and $-1$`,
    ],
    answer: 0,
    explanation: String.raw`Factor out $2$: $2(x^2 - 2x - 3) = 2(x - 3)(x + 1)$. The zeros are $x = 3$ and $x = -1$ (the leading $2$ does not move where the function equals $0$).`,
  },
  {
    id: "qfn-mc-0614-q12",
    mode: "mc",
    standard: "AI-A.APR.3",
    topic: "Zeros of a quadratic — building a function from its zeros",
    examCitation: "regents-algI-0614-q12",
    part: "I",
    credits: 2,
    prompt: String.raw`Keith determines the zeros of the function $f(x)$ to be $-6$ and $5$. What could be Keith's function?`,
    choices: [
      String.raw`$f(x) = (x + 5)(x + 6)$`,
      String.raw`$f(x) = (x + 5)(x - 6)$`,
      String.raw`$f(x) = (x - 5)(x + 6)$`,
      String.raw`$f(x) = (x - 5)(x - 6)$`,
    ],
    answer: 2,
    explanation: String.raw`A zero at $x = -6$ comes from the factor $(x + 6)$, and a zero at $x = 5$ from the factor $(x - 5)$. So $f(x) = (x - 5)(x + 6)$.`,
  },
  {
    id: "qfn-mc-0818-q16",
    mode: "mc",
    standard: "AI-A.APR.3",
    topic: "Zeros of a quadratic — which factored equation",
    examCitation: "regents-algI-0818-q16",
    part: "I",
    credits: 2,
    prompt: String.raw`If $f(x) = 2x^2 + x - 3$, which equation can be used to determine the zeros of the function?`,
    choices: [
      String.raw`$0 = (2x - 3)(x + 1)$`,
      String.raw`$0 = (2x + 3)(x - 1)$`,
      String.raw`$0 = 2x(x + 1) - 3$`,
      String.raw`$0 = 2x(x - 1) - 3(x + 1)$`,
    ],
    answer: 1,
    explanation: String.raw`Set $f(x) = 0$ and factor: $2x^2 + x - 3 = (2x + 3)(x - 1)$ (check: $2x^2 - 2x + 3x - 3 = 2x^2 + x - 3$). So $0 = (2x + 3)(x - 1)$.`,
  },

  // ——— More: Vertex form & max/min — completing the square (AI-F.IF.8) ———
  {
    id: "qfn-mc-0819-q11",
    mode: "mc",
    standard: "AI-F.IF.8",
    topic: "Quadratic functions — completing the square to vertex form",
    examCitation: "regents-algI-0819-q11",
    part: "I",
    credits: 2,
    prompt: String.raw`Which equation is equivalent to $y = x^2 + 24x - 18$?`,
    choices: [
      String.raw`$y = (x + 12)^2 - 162$`,
      String.raw`$y = (x + 12)^2 + 126$`,
      String.raw`$y = (x - 12)^2 - 162$`,
      String.raw`$y = (x - 12)^2 + 126$`,
    ],
    answer: 0,
    explanation: String.raw`Complete the square: half of $24$ is $12$, and $12^2 = 144$. So $y = (x^2 + 24x + 144) - 144 - 18 = (x + 12)^2 - 162$.`,
  },
  {
    id: "qfn-mc-0116-q07",
    mode: "mc",
    standard: "AI-F.IF.8",
    topic: "Quadratic functions — rewriting into vertex form",
    examCitation: "regents-algI-0116-q07",
    part: "I",
    credits: 2,
    prompt: String.raw`Which equation is equivalent to $y - 34 = x(x - 12)$?`,
    choices: [
      String.raw`$y = (x - 17)(x + 2)$`,
      String.raw`$y = (x - 17)(x - 2)$`,
      String.raw`$y = (x - 6)^2 + 2$`,
      String.raw`$y = (x - 6)^2 - 2$`,
    ],
    answer: 3,
    explanation: String.raw`Expand and solve for $y$: $y - 34 = x^2 - 12x$, so $y = x^2 - 12x + 34$. Complete the square: $y = (x^2 - 12x + 36) - 36 + 34 = (x - 6)^2 - 2$.`,
  },

  // ——— More: Interpreting a quadratic model's features (AI-F.IF.4) ———
  {
    id: "qfn-mc-0617-q24",
    mode: "mc",
    standard: "AI-F.IF.4",
    topic: "Interpreting a quadratic model — domain in context",
    examCitation: "regents-algI-0617-q24",
    part: "I",
    credits: 2,
    prompt: String.raw`Morgan throws a ball up into the air. The height of the ball above the ground, in feet, is modeled by the function $h(t) = -16t^2 + 24t$, where $t$ represents the time, in seconds, since the ball was thrown. What is the appropriate domain for this situation?`,
    choices: [
      String.raw`$0 \le t \le 1.5$`,
      String.raw`$0 \le t \le 9$`,
      String.raw`$0 \le h(t) \le 1.5$`,
      String.raw`$0 \le h(t) \le 9$`,
    ],
    answer: 0,
    explanation: String.raw`The ball is in the air from launch until it lands. It lands when $h(t) = 0$: $-16t^2 + 24t = 0 \Rightarrow -8t(2t - 3) = 0 \Rightarrow t = 0$ or $t = 1.5$. The domain (time) is $0 \le t \le 1.5$.`,
  },
  {
    id: "qfn-mc-0123-q15",
    mode: "mc",
    standard: "AI-F.IF.4",
    topic: "Interpreting a quadratic model — meaning of the constant term",
    examCitation: "regents-algI-0123-q15",
    part: "I",
    credits: 2,
    prompt: String.raw`Ian throws a ball up in the air and lets it fall to the ground. The height of the ball, $h(t)$, is modeled by the equation $h(t) = -16t^2 + 6t + 3$, with $h(t)$ measured in feet, and time, $t$, measured in seconds. The number $3$ in $h(t)$ represents`,
    choices: [
      "the maximum height of the ball",
      "the height from which the ball is thrown",
      "the number of seconds it takes for the ball to reach the ground",
      "the number of seconds it takes for the ball to reach its maximum height",
    ],
    answer: 1,
    explanation: String.raw`At $t = 0$ (the instant of the throw), $h(0) = 3$. The constant term is the height when time is $0$ — the height from which the ball is thrown.`,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // Constructed-response (self-score) — rubrics VERBATIM from official
  // NYSED Algebra I rating guides (nysedregents.org). Part II = 2 credits,
  // Part III = 4 credits.
  // ═══════════════════════════════════════════════════════════════════════

  // ——— Zeros / x-intercepts (AI-A.APR.3) ———
  {
    id: "qfn-cr-0617-q33",
    mode: "self-score",
    standard: "AI-A.APR.3",
    topic: "Zeros of a quadratic — factor and interpret",
    examCitation: "regents-algI-0617-q33",
    part: "III",
    credits: 4,
    prompt: String.raw`The function $r(x)$ is defined by the expression $x^2 + 3x - 18$. Use factoring to determine the zeros of $r(x)$. Explain what the zeros represent on the graph of $r(x)$.`,
    answerSummary: String.raw`Zeros: $\{-6, 3\}$ — they are the $x$-intercepts of the graph of $r(x)$.`,
    modelSolution: String.raw`Set $r(x) = 0$: $x^2 + 3x - 18 = 0$. Factor into $(x + 6)(x - 3) = 0$, so $x = -6$ or $x = 3$. The zeros are the $x$-intercepts of $r(x)$ — the points where its graph crosses the $x$-axis.`,
    rubric: [
      { credits: 4, criteria: String.raw`$-6$ and $3$, and correct work is shown, and a correct explanation is written.` },
      { credits: 3, criteria: String.raw`Appropriate work is shown, but one computational or factoring error is made. OR Appropriate work is shown, but an incomplete explanation is written.` },
      { credits: 2, criteria: String.raw`Appropriate work is shown, but two or more computational or factoring errors are made. OR Correct work is shown to find $-6$ and $3$, but no explanation is written. OR A correct explanation is written, but no further correct work is shown.` },
      { credits: 1, criteria: String.raw`$-6$ and $3$, but a method other than factoring is used and no further correct work is shown. OR $-6$ and $3$, but no work is shown.` },
      { credits: 0, criteria: String.raw`A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure.` },
    ],
  },
  {
    id: "qfn-cr-0816-q31",
    mode: "self-score",
    standard: "AI-A.APR.3",
    topic: "Zeros of a quadratic — from vertex form, algebraically",
    examCitation: "regents-algI-0816-q31",
    part: "II",
    credits: 2,
    prompt: String.raw`Find the zeros of $f(x) = (x - 3)^2 - 49$, algebraically.`,
    answerSummary: String.raw`$\{-4, 10\}$`,
    modelSolution: String.raw`Set $f(x) = 0$: $(x - 3)^2 - 49 = 0$, so $(x - 3)^2 = 49$ and $x - 3 = \pm 7$. Then $x = 10$ or $x = -4$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$-4$ and $10$, and correct algebraic work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational or factoring error is made. OR Appropriate work is shown, but one conceptual error is made. OR $-4$ and $10$, but a method other than algebraic is used. OR Appropriate work is shown to find $-4$ or $10$. OR $-4$ and $10$, but no work is shown.` },
      { credits: 0, criteria: String.raw`A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure.` },
    ],
  },
  {
    id: "qfn-cr-0119-q30",
    mode: "self-score",
    standard: "AI-A.APR.3",
    topic: "Zeros of a polynomial — factor out the GCF, then factor",
    examCitation: "regents-algI-0119-q30",
    part: "II",
    credits: 2,
    prompt: String.raw`Determine algebraically the zeros of $f(x) = 3x^3 + 21x^2 + 36x$.`,
    answerSummary: String.raw`$\{0, -3, -4\}$`,
    modelSolution: String.raw`Set $f(x) = 0$ and factor out the GCF $3x$: $3x(x^2 + 7x + 12) = 0$, then $3x(x + 3)(x + 4) = 0$. So $x = 0$, $x = -3$, or $x = -4$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$0$, $-3$, and $-4$ are stated, and correct algebraic work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational or factoring error is made. OR Appropriate work is shown, but one conceptual error is made. OR Appropriate work is shown, but the zeros are stated as ordered pairs. OR Appropriate work is shown to find $3x(x + 3)(x + 4)$, but no further correct work is shown. OR $0$, $-3$, and $-4$, but a method other than algebraic is used. OR $0$, $-3$, and $-4$, but no work is shown.` },
      { credits: 0, criteria: String.raw`A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure.` },
    ],
  },

  // ——— Vertex form & max/min — completing the square (AI-F.IF.8) ———
  {
    id: "qfn-cr-0619-q32",
    mode: "self-score",
    standard: "AI-F.IF.8",
    topic: "Quadratic functions — vertex by completing the square",
    examCitation: "regents-algI-0619-q32",
    part: "II",
    credits: 2,
    prompt: String.raw`Determine and state the vertex of $f(x) = x^2 - 2x - 8$ using the method of completing the square.`,
    answerSummary: String.raw`$(1, -9)$`,
    modelSolution: String.raw`$f(x) = x^2 - 2x - 8 = (x^2 - 2x + 1) - 1 - 8 = (x - 1)^2 - 9$. In vertex form $(x - h)^2 + k$, the vertex is $(h, k) = (1, -9)$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$(1, -9)$, and correct work using the method of completing the square is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but one conceptual error is made. OR Appropriate work is shown to find $f(x) = (x - 1)^2 - 9$, but the vertex is not stated or is stated incorrectly. OR $(1, -9)$, but a method other than completing the square is used. OR $(1, -9)$ is stated, but no work is shown.` },
      { credits: 0, criteria: String.raw`A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure.` },
    ],
  },
  {
    id: "qfn-cr-0115-q36",
    mode: "self-score",
    standard: "AI-F.IF.8",
    topic: "Quadratic functions — max/min and vertex form",
    examCitation: "regents-algI-0115-q36",
    part: "III",
    credits: 4,
    prompt: String.raw`Given the function $f(x) = -x^2 + 8x + 9$, state whether the vertex represents a maximum or minimum point for the function. Explain your answer. Rewrite $f(x)$ in vertex form by completing the square.`,
    answerSummary: String.raw`Maximum (since $a = -1 < 0$); $f(x) = -(x - 4)^2 + 25$.`,
    modelSolution: String.raw`The vertex is a maximum because the leading coefficient $a = -1$ is negative, so the parabola opens downward. Completing the square: $f(x) = -(x^2 - 8x) + 9 = -(x^2 - 8x + 16) + 16 + 9 = -(x - 4)^2 + 25$.`,
    rubric: [
      { credits: 4, criteria: String.raw`Maximum is stated, a correct explanation is written, and $f(x) = -(x - 4)^2 + 25$, and correct work is shown using completing the square.` },
      { credits: 3, criteria: String.raw`Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but the explanation is missing or incorrect.` },
      { credits: 2, criteria: String.raw`Appropriate work is shown, but two or more computational errors are made. OR Appropriate work is shown, but one conceptual error is made. OR Appropriate work is shown to find $f(x) = -(x - 4)^2 + 25$, but no further correct work is shown. OR Maximum and a correct explanation is given, but no further correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one conceptual and one computational error are made. OR $f(x) = -(x - 4)^2 + 25$, but no work is shown.` },
      { credits: 0, criteria: String.raw`Maximum is stated, but no further correct work is shown. OR A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure.` },
    ],
  },

  // ——— Interpreting a quadratic model's features (AI-F.IF.4) ———
  {
    id: "qfn-cr-0618-q29",
    mode: "self-score",
    standard: "AI-F.IF.4",
    topic: "Interpreting a quadratic model — when it hits the ground",
    examCitation: "regents-algI-0618-q29",
    part: "II",
    credits: 2,
    prompt: String.raw`When an apple is dropped from a tower 256 feet high, the function $h(t) = -16t^2 + 256$ models the height of the apple, in feet, after $t$ seconds. Determine, algebraically, the number of seconds it takes the apple to hit the ground.`,
    answerSummary: String.raw`$4$ seconds`,
    modelSolution: String.raw`The apple hits the ground when $h(t) = 0$: $-16t^2 + 256 = 0 \Rightarrow 16t^2 = 256 \Rightarrow t^2 = 16 \Rightarrow t = 4$ (reject $t = -4$, since time cannot be negative).`,
    rubric: [
      { credits: 2, criteria: String.raw`$4$, and correct algebraic work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational or factoring error is made. OR Appropriate work is shown, but one conceptual error is made. OR $4$, but a method other than algebraic is used. OR $4$, but no work is shown.` },
      { credits: 0, criteria: String.raw`A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure.` },
    ],
  },
  {
    id: "qfn-cr-0616-q33",
    mode: "self-score",
    standard: "AI-F.IF.4",
    topic: "Interpreting a quadratic model — change over an interval and landing time",
    examCitation: "regents-algI-0616-q33",
    part: "III",
    credits: 4,
    prompt: String.raw`The height, $H$, in feet, of an object dropped from the top of a building after $t$ seconds is given by $H(t) = -16t^2 + 144$. How many feet did the object fall between one and two seconds after it was dropped? Determine, algebraically, how many seconds it will take for the object to reach the ground.`,
    answerSummary: String.raw`$48$ feet; $3$ seconds`,
    modelSolution: String.raw`$H(1) = -16(1)^2 + 144 = 128$ and $H(2) = -16(2)^2 + 144 = 80$, so the object fell $128 - 80 = 48$ feet. It reaches the ground when $H(t) = 0$: $-16t^2 + 144 = 0 \Rightarrow t^2 = 9 \Rightarrow t = 3$ seconds.`,
    rubric: [
      { credits: 4, criteria: String.raw`$48$, $3$, and correct work is shown.` },
      { credits: 3, criteria: String.raw`Appropriate work is shown, but one computational error is made.` },
      { credits: 2, criteria: String.raw`Appropriate work is shown, but two or more computational errors are made. OR Appropriate work is shown, but one conceptual error is made. OR Appropriate work is shown to find $48$ or $3$, but no further correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one conceptual error and one computational error are made. OR Appropriate work is shown to find $128$ and $80$, but no further correct work is shown. OR $48$ and $3$, but no work is shown.` },
      { credits: 0, criteria: String.raw`$128$ and $80$, but no work is shown. OR A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure.` },
    ],
  },
  {
    id: "qfn-cr-0824-q33",
    mode: "self-score",
    standard: "AI-F.IF.4",
    topic: "Interpreting a quadratic model — vertex meaning and landing time",
    examCitation: "regents-algI-0824-q33",
    part: "III",
    credits: 4,
    prompt: String.raw`An object is launched upward at 64 feet per second from a platform 80 feet above the ground. The function $s(t)$ models the height of the object $t$ seconds after launch. If $s(t) = -16t^2 + 64t + 80$, state the vertex of $s(t)$, and explain in detail what each coordinate means in the context of the problem. After the object is launched, how many seconds does it take for the object to hit the ground? Justify your answer.`,
    answerSummary: String.raw`Vertex $(2, 144)$; the object hits the ground after $5$ seconds.`,
    modelSolution: String.raw`Axis of symmetry: $t = \dfrac{-b}{2a} = \dfrac{-64}{2(-16)} = 2$, and $s(2) = -16(2)^2 + 64(2) + 80 = 144$, so the vertex is $(2, 144)$: at $t = 2$ seconds the object reaches its maximum height of $144$ feet. It hits the ground when $s(t) = 0$: $-16t^2 + 64t + 80 = 0 \Rightarrow t^2 - 4t - 5 = 0 \Rightarrow (t - 5)(t + 1) = 0$, so $t = 5$ seconds.`,
    rubric: [
      { credits: 4, criteria: String.raw`$(2, 144)$, and a correct explanation in context for each coordinate is written, and $5$, and a correct justification is given.` },
      { credits: 3, criteria: String.raw`Appropriate work is shown, but the explanation is missing, incorrect, or not in context. OR Appropriate work is shown, but the justification is missing or incorrect.` },
      { credits: 2, criteria: String.raw`$(2, 144)$, and a correct explanation in context is written, but no further correct work is shown. OR $5$, and a correct justification is given, but no further correct work is shown. OR $(2, 144)$, and $5$, but no further correct work is shown.` },
      { credits: 1, criteria: String.raw`Only a correct explanation in context is written. OR $(2, 144)$, or $5$, but no further correct work is shown.` },
      { credits: 0, criteria: String.raw`A zero response does not contain enough relevant course-level work to receive any credit, does not satisfy the criteria for one or more credits, or is a correct response that was obtained by an obviously incorrect procedure.` },
    ],
  },
  {
    id: "qfn-cr-0815-q31",
    mode: "self-score",
    standard: "AI-F.IF.4",
    topic: "Interpreting a quadratic model — domain in context",
    examCitation: "regents-algI-0815-q31",
    part: "II",
    credits: 2,
    prompt: String.raw`A toy rocket is launched from the ground straight upward. The height of the rocket above the ground, in feet, is given by the equation $h(t) = -16t^2 + 64t$, where $t$ is the time in seconds. Determine the domain for this function in the given context. Explain your reasoning.`,
    answerSummary: String.raw`$0 \le t \le 4$`,
    modelSolution: String.raw`The rocket is in the air from launch until it lands. It is on the ground when $h(t) = 0$: $-16t^2 + 64t = 0 \Rightarrow -16t(t - 4) = 0$, so $t = 0$ or $t = 4$. The rocket launches at $t = 0$ and lands at $t = 4$, so the domain is $0 \le t \le 4$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$0 \le t \le 4$ or equivalent, and a correct explanation is written.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but one conceptual error is made. OR $0 \le t \le 4$, but the explanation is incomplete, incorrect, or missing.` },
      { credits: 0, criteria: String.raw`A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure.` },
    ],
  },
  {
    id: "qfn-cr-0817-q36",
    mode: "self-score",
    standard: "AI-F.IF.4",
    topic: "Interpreting a quadratic model — vertex and relative height",
    examCitation: "regents-algI-0817-q36",
    part: "III",
    credits: 4,
    prompt: String.raw`An Air Force pilot is flying at a cruising altitude of 9000 feet and is forced to eject from her aircraft. The function $h(t) = -16t^2 + 128t + 9000$ models the height, in feet, of the pilot above the ground, where $t$ is the time, in seconds, after she is ejected from the aircraft. Determine and state the vertex of $h(t)$. Explain what the second coordinate of the vertex represents in the context of the problem. After the pilot was ejected, what is the maximum number of feet she was above the aircraft's cruising altitude? Justify your answer.`,
    answerSummary: String.raw`Vertex $(4, 9256)$; she was at most $256$ feet above the cruising altitude.`,
    modelSolution: String.raw`Axis of symmetry: $t = \dfrac{-128}{2(-16)} = 4$, and $h(4) = -16(4)^2 + 128(4) + 9000 = 9256$, so the vertex is $(4, 9256)$. The second coordinate, $9256$, is the pilot's maximum height above the ground (reached $4$ seconds after ejection). Above the cruising altitude: $9256 - 9000 = 256$ feet.`,
    rubric: [
      { credits: 4, criteria: String.raw`$(4, 9256)$, and a correct explanation is written, and $256$, and a correct justification is given.` },
      { credits: 3, criteria: String.raw`Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but either the explanation or justification is missing or incorrect.` },
      { credits: 2, criteria: String.raw`Appropriate work is shown, but two or more computational errors are made. OR $(4, 9256)$, and a correct explanation is written, but no further correct work is shown. OR $(4, 9256)$ and $256$, but no further correct work is shown.` },
      { credits: 1, criteria: String.raw`$(4, 9256)$ or $256$, but no work is shown.` },
      { credits: 0, criteria: String.raw`A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure.` },
    ],
  },
];

export default bank;
