// Authored Regents problem-bank — Rational & Irrational Numbers (AI-N.RN.3):
// classifying numbers as rational or irrational and reasoning about closure —
// the sum/product of two rationals is rational, the sum of a rational and an
// irrational is irrational, and the product of a nonzero rational and an
// irrational is irrational, while sums/products INVOLVING two irrationals are
// not guaranteed either way. Real released Algebra I Regents questions mined from
// the official NYSED administrations (via JMAP), cited to the exam + question
// number. Every answer independently re-derived; values verified against the
// source PDFs (radicals/fractions read from rendered pages, not raw text). Every
// self-score rubric is transcribed from the official NYSED Rating Guide. SME-ratified.

import type { RegentsItem, RubricLevel } from "@/lib/regents/bank";

// ——— Shared, verbatim-faithful NYSED rubrics for the 2-credit "explain" family ———
// (Confirmed against the Rating Guides for 0618 Q31, 0123 Q29, 0819 Q30, 0115 Q25;
//  the wording is standardized across this item family.)

const EXPLAIN_RATIONAL_RUBRIC: RubricLevel[] = [
  { credits: 2, criteria: "Rational is stated, and a correct explanation is written." },
  { credits: 1, criteria: "Appropriate work is shown, but one conceptual error is made." },
  { credits: 0, criteria: "Rational is stated, but no explanation or an incorrect explanation is written; OR a zero response that is completely incorrect, irrelevant, or incoherent, or is a correct response arrived at using an obviously incorrect procedure." },
];

const EXPLAIN_IRRATIONAL_RUBRIC: RubricLevel[] = [
  { credits: 2, criteria: "Irrational is stated, and a correct explanation is written." },
  { credits: 1, criteria: "Appropriate work is shown, but one conceptual error is made." },
  { credits: 0, criteria: "Irrational is stated, but no explanation or an incorrect explanation is written; OR a zero response that is completely incorrect, irrelevant, or incoherent, or is a correct response arrived at using an obviously incorrect procedure." },
];

const bank: RegentsItem[] = [
  // ——————————————————————— Part I multiple choice ———————————————————————

  {
    id: "rir-mc-0814-q01",
    mode: "mc",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — closure rules",
    examCitation: "regents-algI-0814-q01",
    part: "I",
    credits: 2,
    prompt: String.raw`Which statement is not always true?`,
    choices: [
      String.raw`The product of two irrational numbers is irrational.`,
      String.raw`The product of two rational numbers is rational.`,
      String.raw`The sum of two rational numbers is rational.`,
      String.raw`The sum of a rational number and an irrational number is irrational.`,
    ],
    answer: 0,
    explanation: String.raw`The product of two irrationals is not always irrational — for example $\sqrt{2} \cdot \sqrt{2} = 2$, which is rational. The other three statements are always true: rationals are closed under both addition and multiplication, and adding an irrational to a rational can never produce a ratio of integers.`,
  },
  {
    id: "rir-mc-0615-q08",
    mode: "mc",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — closure rules",
    examCitation: "regents-algI-0615-q08",
    part: "I",
    credits: 2,
    prompt: String.raw`Which statement is not always true?`,
    choices: [
      String.raw`The sum of two rational numbers is rational.`,
      String.raw`The product of two irrational numbers is rational.`,
      String.raw`The sum of a rational number and an irrational number is irrational.`,
      String.raw`The product of a nonzero rational number and an irrational number is irrational.`,
    ],
    answer: 1,
    explanation: String.raw`The product of two irrationals is not always rational — e.g. $\sqrt{2} \cdot \sqrt{3} = \sqrt{6}$ is irrational (whereas $\sqrt{2} \cdot \sqrt{2} = 2$ is rational). The other three statements are always true.`,
  },
  {
    id: "rir-mc-0623-q02",
    mode: "mc",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — classifying expressions",
    examCitation: "regents-algI-0623-q02",
    part: "I",
    credits: 2,
    prompt: String.raw`Which expression represents an irrational number?`,
    choices: [
      String.raw`$\sqrt{16} + \sqrt{1}$`,
      String.raw`$\sqrt{25} + \sqrt{4}$`,
      String.raw`$\sqrt{36} + \sqrt{7}$`,
      String.raw`$\sqrt{49} + \sqrt{9}$`,
    ],
    answer: 2,
    explanation: String.raw`$\sqrt{16}+\sqrt{1}=4+1=5$, $\sqrt{25}+\sqrt{4}=5+2=7$, and $\sqrt{49}+\sqrt{9}=7+3=10$ are all rational. Only $\sqrt{36}+\sqrt{7}=6+\sqrt{7}$ is irrational, since $\sqrt{7}$ is irrational and a rational ($6$) plus an irrational is irrational.`,
  },
  {
    id: "rir-mc-0624-q05",
    mode: "mc",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — sums",
    examCitation: "regents-algI-0624-q05",
    part: "I",
    credits: 2,
    prompt: String.raw`Which sum is irrational?`,
    choices: [
      String.raw`$-2\sqrt{12} + \sqrt{100}$`,
      String.raw`$-\sqrt{4} + \dfrac{1}{3}\sqrt{900}$`,
      String.raw`$\dfrac{1}{2}\sqrt{25} + \sqrt{64}$`,
      String.raw`$\sqrt{49} + 3\sqrt{121}$`,
    ],
    answer: 0,
    explanation: String.raw`$-2\sqrt{12}+\sqrt{100} = -4\sqrt{3}+10$ is irrational because $\sqrt{12}=2\sqrt{3}$ is irrational. The others are rational: $-2+\tfrac{1}{3}(30)=8$; $\tfrac{1}{2}(5)+8=10.5$; $7+3(11)=40$.`,
  },
  {
    id: "rir-mc-0815-q22",
    mode: "mc",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — sums",
    examCitation: "regents-algI-0815-q22",
    part: "I",
    credits: 2,
    prompt: String.raw`For which value of $P$ and $W$ is $P + W$ a rational number?`,
    choices: [
      String.raw`$P=\dfrac{1}{\sqrt{3}}$ and $W=\dfrac{1}{\sqrt{6}}$`,
      String.raw`$P=\dfrac{1}{\sqrt{4}}$ and $W=\dfrac{1}{\sqrt{9}}$`,
      String.raw`$P=\dfrac{1}{\sqrt{6}}$ and $W=\dfrac{1}{\sqrt{10}}$`,
      String.raw`$P=\dfrac{1}{\sqrt{25}}$ and $W=\dfrac{1}{\sqrt{2}}$`,
    ],
    answer: 1,
    explanation: String.raw`Only choice (2) has both radicals equal to integers: $P=\dfrac{1}{\sqrt{4}}=\dfrac{1}{2}$ and $W=\dfrac{1}{\sqrt{9}}=\dfrac{1}{3}$, so $P+W=\dfrac{1}{2}+\dfrac{1}{3}=\dfrac{5}{6}$, a ratio of two integers. Every other choice contains at least one irrational $\dfrac{1}{\sqrt{n}}$ (with $n$ not a perfect square), and a rational plus an irrational is irrational.`,
  },
  {
    id: "rir-mc-0614-q13",
    mode: "mc",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — classifying expressions",
    examCitation: "regents-algI-0614-q13",
    part: "I",
    credits: 2,
    prompt: String.raw`Given: $L=\sqrt{2}$, $M=3\sqrt{3}$, $N=\sqrt{16}$, and $P=\sqrt{9}$. Which expression results in a rational number?`,
    choices: [
      String.raw`$L+M$`,
      String.raw`$M+N$`,
      String.raw`$N+P$`,
      String.raw`$P+L$`,
    ],
    answer: 2,
    explanation: String.raw`$N=\sqrt{16}=4$ and $P=\sqrt{9}=3$ are both rational, so $N+P=7$ is rational. The other sums each include $L=\sqrt{2}$ or $M=3\sqrt{3}$, which are irrational, and a rational plus an irrational is irrational.`,
  },
  {
    id: "rir-mc-0619-q07",
    mode: "mc",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — products",
    examCitation: "regents-algI-0619-q07",
    part: "I",
    credits: 2,
    prompt: String.raw`Which expression results in a rational number?`,
    choices: [
      String.raw`$\sqrt{2}\cdot\sqrt{18}$`,
      String.raw`$5\cdot\sqrt{5}$`,
      String.raw`$\sqrt{2}+\sqrt{2}$`,
      String.raw`$3\sqrt{2}+2\sqrt{3}$`,
    ],
    answer: 0,
    explanation: String.raw`$\sqrt{2}\cdot\sqrt{18}=\sqrt{36}=6$, which is rational. The others are irrational: $5\sqrt{5}$, $\sqrt{2}+\sqrt{2}=2\sqrt{2}$, and $3\sqrt{2}+2\sqrt{3}$.`,
  },
  {
    id: "rir-mc-0119-q03",
    mode: "mc",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — classifying expressions",
    examCitation: "regents-algI-0119-q03",
    part: "I",
    credits: 2,
    prompt: String.raw`Which expression results in a rational number?`,
    choices: [
      String.raw`$\sqrt{121}-\sqrt{21}$`,
      String.raw`$\sqrt{25}\cdot\sqrt{50}$`,
      String.raw`$\sqrt{36}\div\sqrt{225}$`,
      String.raw`$3\sqrt{5}+2\sqrt{5}$`,
    ],
    answer: 2,
    explanation: String.raw`$\sqrt{36}\div\sqrt{225}=\dfrac{6}{15}=\dfrac{2}{5}$, a ratio of two integers. The others are irrational: $11-\sqrt{21}$, $5\cdot 5\sqrt{2}=25\sqrt{2}$, and $3\sqrt{5}+2\sqrt{5}=5\sqrt{5}$.`,
  },
  {
    id: "rir-mc-0824-q07",
    mode: "mc",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — classifying expressions",
    examCitation: "regents-algI-0824-q07",
    part: "I",
    credits: 2,
    prompt: String.raw`Which expression results in an irrational number?`,
    choices: [
      String.raw`$\sqrt{3}\cdot\sqrt{3}$`,
      String.raw`$-\dfrac{2}{3}+\dfrac{1}{4}$`,
      String.raw`$5\cdot\sqrt{81}$`,
      String.raw`$\dfrac{1}{3}+\sqrt{3}$`,
    ],
    answer: 3,
    explanation: String.raw`$\dfrac{1}{3}+\sqrt{3}$ is irrational (rational $+$ irrational). The others are rational: $\sqrt{3}\cdot\sqrt{3}=3$, $-\dfrac{2}{3}+\dfrac{1}{4}=-\dfrac{5}{12}$, and $5\cdot 9=45$.`,
  },
  {
    id: "rir-mc-0116-q04",
    mode: "mc",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — classifying expressions",
    examCitation: "regents-algI-0116-q04",
    part: "I",
    credits: 2,
    prompt: String.raw`Given the following expressions:

I. $-\dfrac{5}{8}+\dfrac{3}{5}$

II. $\dfrac{1}{2}+\sqrt{2}$

III. $\left(\sqrt{5}\right)\left(\sqrt{5}\right)$

IV. $3\left(\sqrt{49}\right)$

Which expression(s) result in an irrational number?`,
    choices: [
      String.raw`II, only`,
      String.raw`III, only`,
      String.raw`I, III, IV`,
      String.raw`II, III, IV`,
    ],
    answer: 0,
    explanation: String.raw`Only II is irrational: $\dfrac{1}{2}+\sqrt{2}$ (rational $+$ irrational). The others are rational: I $=-\dfrac{5}{8}+\dfrac{3}{5}=-\dfrac{1}{40}$, III $=\sqrt{5}\cdot\sqrt{5}=5$, and IV $=3\cdot 7=21$.`,
  },
  {
    id: "rir-mc-0621-q09",
    mode: "mc",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — operations on radicals",
    examCitation: "regents-algI-0621-q09",
    part: "I",
    credits: 2,
    prompt: String.raw`If $x=2$, $y=3\sqrt{2}$, and $w=2\sqrt{8}$, which expression results in a rational number?`,
    choices: [
      String.raw`$x+y$`,
      String.raw`$y-w$`,
      String.raw`$(w)(y)$`,
      String.raw`$y\div x$`,
    ],
    answer: 2,
    explanation: String.raw`$(w)(y)=2\sqrt{8}\cdot 3\sqrt{2}=6\sqrt{16}=6\cdot 4=24$, which is rational. The others keep a $\sqrt{2}$ factor: $x+y=2+3\sqrt{2}$; $y-w=3\sqrt{2}-4\sqrt{2}=-\sqrt{2}$ (since $2\sqrt{8}=4\sqrt{2}$); $y\div x=\dfrac{3\sqrt{2}}{2}$.`,
  },
  {
    id: "rir-mc-0126-q02",
    mode: "mc",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — products",
    examCitation: "regents-algI-0126-q02",
    part: "I",
    credits: 2,
    prompt: String.raw`The product of $\sqrt{25}$ and $\sqrt{2}$ will result in`,
    choices: [
      String.raw`an irrational number`,
      String.raw`a rational number`,
      String.raw`a natural number`,
      String.raw`an integer`,
    ],
    answer: 0,
    explanation: String.raw`$\sqrt{25}\cdot\sqrt{2}=5\sqrt{2}$. Since $\sqrt{2}$ is irrational and $5$ is a nonzero rational, the product $5\sqrt{2}$ is irrational.`,
  },
  {
    id: "rir-mc-0118-q08",
    mode: "mc",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — products",
    examCitation: "regents-algI-0118-q08",
    part: "I",
    credits: 2,
    prompt: String.raw`The product of $\sqrt{576}$ and $\sqrt{684}$ is`,
    choices: [
      String.raw`irrational because both factors are irrational`,
      String.raw`rational because both factors are rational`,
      String.raw`irrational because one factor is irrational`,
      String.raw`rational because one factor is rational`,
    ],
    answer: 2,
    explanation: String.raw`$\sqrt{576}=24$ is rational, but $\sqrt{684}=6\sqrt{19}$ is irrational. The product $24\cdot 6\sqrt{19}=144\sqrt{19}$ is irrational because one factor ($\sqrt{684}$) is irrational.`,
  },
  {
    id: "rir-mc-0625-q14",
    mode: "mc",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — sums",
    examCitation: "regents-algI-0625-q14",
    part: "I",
    credits: 2,
    prompt: String.raw`The sum of $3$ and $\sqrt{5}$ is`,
    choices: [
      String.raw`rational, since the sum can be expressed as an integer`,
      String.raw`rational, since the sum can be expressed as a nonterminating decimal`,
      String.raw`irrational, since the sum can be expressed as a terminating decimal`,
      String.raw`irrational, since the sum cannot be expressed as a terminating or repeating decimal`,
    ],
    answer: 3,
    explanation: String.raw`$3+\sqrt{5}$ is irrational. $\sqrt{5}$ is a nonterminating, nonrepeating decimal, so the sum cannot be written as a terminating or repeating decimal — i.e., it is not a ratio of two integers.`,
  },

  // ——————————————————— Part II constructed response (self-score) ———————————————————

  {
    id: "rir-cr-0819-q30",
    mode: "self-score",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — closure (counterexample)",
    examCitation: "regents-algI-0819-q30",
    part: "II",
    credits: 2,
    prompt: String.raw`Is the product of two irrational numbers always irrational? Justify your answer.`,
    answerSummary: String.raw`No.`,
    modelSolution: String.raw`No. As a counterexample, $\sqrt{8}$ and $\sqrt{2}$ are both irrational, but their product is $\sqrt{8}\cdot\sqrt{2}=\sqrt{16}=4$, which is rational. So the product of two irrationals is not always irrational.`,
    rubric: [
      { credits: 2, criteria: "A negative response is indicated, and a correct justification is given." },
      { credits: 1, criteria: "Appropriate work is shown, but one conceptual error is made; OR an incomplete justification is given, but an appropriate response is indicated." },
      { credits: 0, criteria: "No is indicated, but the justification is missing or incorrect; OR a zero response that is completely incorrect, irrelevant, or incoherent, or is a correct response arrived at using an obviously incorrect procedure." },
    ],
  },
  {
    id: "rir-cr-0618-q31",
    mode: "self-score",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — products",
    examCitation: "regents-algI-0618-q31",
    part: "II",
    credits: 2,
    prompt: String.raw`Is the product of $\sqrt{16}$ and $\dfrac{4}{7}$ rational or irrational? Explain your reasoning.`,
    answerSummary: String.raw`Rational.`,
    modelSolution: String.raw`$\sqrt{16}=4$, so the product is $4\cdot\dfrac{4}{7}=\dfrac{16}{7}$. Since $\dfrac{16}{7}$ is a ratio of two integers, the product is rational.`,
    rubric: EXPLAIN_RATIONAL_RUBRIC,
  },
  {
    id: "rir-cr-0120-q30",
    mode: "self-score",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — products",
    examCitation: "regents-algI-0120-q30",
    part: "II",
    credits: 2,
    prompt: String.raw`State whether the product of $\sqrt{3}$ and $\sqrt{9}$ is rational or irrational. Explain your answer.`,
    answerSummary: String.raw`Irrational.`,
    modelSolution: String.raw`$\sqrt{9}=3$, so the product is $3\sqrt{3}=\sqrt{27}$. Because $\sqrt{27}$ cannot be written as the ratio of two integers, the product is irrational.`,
    rubric: EXPLAIN_IRRATIONAL_RUBRIC,
  },
  {
    id: "rir-cr-0622-q25",
    mode: "self-score",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — products",
    examCitation: "regents-algI-0622-q25",
    part: "II",
    credits: 2,
    prompt: String.raw`Is the product of $\sqrt{1024}$ and $3.4$ rational or irrational? Explain your reasoning.`,
    answerSummary: String.raw`Rational.`,
    modelSolution: String.raw`$\sqrt{1024}=32$, so the product is $32\cdot 3.4=108.8$. Since $108.8=\dfrac{1088}{10}$ is a ratio of two integers, the product is rational.`,
    rubric: EXPLAIN_RATIONAL_RUBRIC,
  },
  {
    id: "rir-cr-0616-q26",
    mode: "self-score",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — products",
    examCitation: "regents-algI-0616-q26",
    part: "II",
    credits: 2,
    prompt: String.raw`Determine if the product of $3\sqrt{2}$ and $8\sqrt{18}$ is rational or irrational. Explain your answer.`,
    answerSummary: String.raw`Rational.`,
    modelSolution: String.raw`$3\sqrt{2}\cdot 8\sqrt{18}=24\sqrt{36}=24\cdot 6=144$. Since $144$ is an integer (a ratio of two integers), the product is rational.`,
    rubric: EXPLAIN_RATIONAL_RUBRIC,
  },
  {
    id: "rir-cr-0822-q27",
    mode: "self-score",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — products",
    examCitation: "regents-algI-0822-q27",
    part: "II",
    credits: 2,
    prompt: String.raw`Is the product of $\sqrt{8}$ and $\sqrt{98}$ rational or irrational? Justify your answer.`,
    answerSummary: String.raw`Rational.`,
    modelSolution: String.raw`$\sqrt{8}=2\sqrt{2}$ and $\sqrt{98}=7\sqrt{2}$, so the product is $2\sqrt{2}\cdot 7\sqrt{2}=14\cdot 2=28$. Since $28$ is a ratio of two integers, the product is rational. (Equivalently, $\sqrt{8}\cdot\sqrt{98}=\sqrt{784}=28$.)`,
    rubric: EXPLAIN_RATIONAL_RUBRIC,
  },
  {
    id: "rir-cr-0115-q25",
    mode: "self-score",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — sums",
    examCitation: "regents-algI-0115-q25",
    part: "II",
    credits: 2,
    prompt: String.raw`Ms. Fox asked her class "Is the sum of $4.2$ and $\sqrt{2}$ rational or irrational?" Patrick answered that the sum would be irrational. State whether Patrick is correct or incorrect. Justify your reasoning.`,
    answerSummary: String.raw`Patrick is correct.`,
    modelSolution: String.raw`Patrick is correct. $4.2$ is rational and $\sqrt{2}$ is irrational, and the sum of a rational number and an irrational number is always irrational. So $4.2+\sqrt{2}$ is irrational.`,
    rubric: [
      { credits: 2, criteria: "Correct is stated, and a correct justification is given." },
      { credits: 1, criteria: "Appropriate work is shown, but one computational error is made; OR one conceptual error is made." },
      { credits: 0, criteria: "Correct is stated, but no work or justification is given; OR a zero response that is completely incorrect, irrelevant, or incoherent, or is a correct response arrived at using an obviously incorrect procedure." },
    ],
  },
  {
    id: "rir-cr-0825-q26",
    mode: "self-score",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — sums",
    examCitation: "regents-algI-0825-q26",
    part: "II",
    credits: 2,
    prompt: String.raw`Is the sum of $3\sqrt{2}$ and $5$ rational or irrational? Explain your answer.`,
    answerSummary: String.raw`Irrational.`,
    modelSolution: String.raw`$3\sqrt{2}$ is irrational and $5$ is rational, and a rational plus an irrational is irrational. So $3\sqrt{2}+5$ is irrational — it cannot be written as the ratio of two integers.`,
    rubric: EXPLAIN_IRRATIONAL_RUBRIC,
  },
  {
    id: "rir-cr-0816-q29",
    mode: "self-score",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — sums",
    examCitation: "regents-algI-0816-q29",
    part: "II",
    credits: 2,
    prompt: String.raw`Is the sum of $3\sqrt{2}$ and $4\sqrt{2}$ rational or irrational? Explain your answer.`,
    answerSummary: String.raw`Irrational.`,
    modelSolution: String.raw`$3\sqrt{2}+4\sqrt{2}=7\sqrt{2}$. Since $7\sqrt{2}$ cannot be written as the ratio of two integers, the sum is irrational.`,
    rubric: EXPLAIN_IRRATIONAL_RUBRIC,
  },
  {
    id: "rir-cr-0617-q27",
    mode: "self-score",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — sums",
    examCitation: "regents-algI-0617-q27",
    part: "II",
    credits: 2,
    prompt: String.raw`State whether $7-\sqrt{2}$ is rational or irrational. Explain your answer.`,
    answerSummary: String.raw`Irrational.`,
    modelSolution: String.raw`$7$ is rational and $\sqrt{2}$ is irrational; subtracting an irrational from a rational gives an irrational. So $7-\sqrt{2}$ is irrational — it cannot be written as the ratio of two integers.`,
    rubric: EXPLAIN_IRRATIONAL_RUBRIC,
  },
  {
    id: "rir-cr-0124-q26",
    mode: "self-score",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — sums",
    examCitation: "regents-algI-0124-q26",
    part: "II",
    credits: 2,
    prompt: String.raw`State whether $2\sqrt{3}+6$ is rational or irrational. Explain your answer.`,
    answerSummary: String.raw`Irrational.`,
    modelSolution: String.raw`$2\sqrt{3}$ is irrational and $6$ is rational, and a rational plus an irrational is irrational. So $2\sqrt{3}+6$ is irrational — it cannot be written as the ratio of two integers.`,
    rubric: EXPLAIN_IRRATIONAL_RUBRIC,
  },
  {
    id: "rir-cr-0117-q28",
    mode: "self-score",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — sums",
    examCitation: "regents-algI-0117-q28",
    part: "II",
    credits: 2,
    prompt: String.raw`Jakob is working on his math homework. He decides that the sum of the expression $\dfrac{1}{3}+\dfrac{6\sqrt{5}}{7}$ must be rational because it is a fraction. Is Jakob correct? Explain your reasoning.`,
    answerSummary: String.raw`No, Jakob is incorrect.`,
    modelSolution: String.raw`No. $\dfrac{1}{3}$ is rational, but $\dfrac{6\sqrt{5}}{7}$ is irrational because $\sqrt{5}$ is irrational. The sum of a rational number and an irrational number is irrational, so the expression is irrational, not rational. Being written in fraction form does not make a number rational.`,
    rubric: [
      { credits: 2, criteria: "No is stated, and a correct explanation is written." },
      { credits: 1, criteria: "Appropriate work is shown, but one conceptual error is made." },
      { credits: 0, criteria: "No is stated, but no explanation or an incorrect explanation is written; OR a zero response that is completely incorrect, irrelevant, or incoherent, or is a correct response arrived at using an obviously incorrect procedure." },
    ],
  },
  {
    id: "rir-cr-0823-q25",
    mode: "self-score",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — classifying expressions",
    examCitation: "regents-algI-0823-q25",
    part: "II",
    credits: 2,
    prompt: String.raw`Classify the expression $\dfrac{2}{\sqrt{144}}+\dfrac{\sqrt{169}}{3}$ as rational or irrational. Explain your reasoning.`,
    answerSummary: String.raw`Rational.`,
    modelSolution: String.raw`$\sqrt{144}=12$ and $\sqrt{169}=13$, so the expression equals $\dfrac{2}{12}+\dfrac{13}{3}=\dfrac{1}{6}+\dfrac{13}{3}$. This is the sum of two rational numbers, which is rational. (Numerically, $\dfrac{1}{6}+\dfrac{26}{6}=\dfrac{27}{6}=\dfrac{9}{2}$.)`,
    rubric: EXPLAIN_RATIONAL_RUBRIC,
  },
  {
    id: "rir-cr-0123-q29",
    mode: "self-score",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — sums & products",
    examCitation: "regents-algI-0123-q29",
    part: "II",
    credits: 2,
    prompt: String.raw`Given: $A=\sqrt{363}$ and $B=\sqrt{27}$. Explain why $A+B$ is irrational. Explain why $A\cdot B$ is rational.`,
    answerSummary: String.raw`$A+B=14\sqrt{3}$ (irrational); $A\cdot B=99$ (rational).`,
    modelSolution: String.raw`$A=\sqrt{363}=11\sqrt{3}$ and $B=\sqrt{27}=3\sqrt{3}$. Then $A+B=11\sqrt{3}+3\sqrt{3}=14\sqrt{3}$, which is irrational because it cannot be written as the ratio of two integers. And $A\cdot B=\sqrt{363}\cdot\sqrt{27}=\sqrt{9801}=99$, which is rational because $99$ is a ratio of two integers.`,
    rubric: [
      { credits: 2, criteria: "Two correct explanations are written." },
      { credits: 1, criteria: String.raw`One conceptual error is made; OR one correct explanation is written; OR correct work is shown to find $14\sqrt{3}$ and $99$, but the explanation is missing or incorrect.` },
      { credits: 0, criteria: "A zero response that is completely incorrect, irrelevant, or incoherent, or is a correct response arrived at using an obviously incorrect procedure." },
    ],
  },
  {
    id: "rir-cr-0817-q25",
    mode: "self-score",
    standard: "AI-N.RN.3",
    topic: "Rational & irrational numbers — sums & products",
    examCitation: "regents-algI-0817-q25",
    part: "II",
    credits: 2,
    prompt: String.raw`A teacher wrote the following set of numbers on the board: $a=\sqrt{20}$, $b=2.5$, and $c=\sqrt{225}$. Explain why $a+b$ is irrational, but $b\cdot c$ is rational.`,
    answerSummary: String.raw`$a+b=2\sqrt{5}+2.5$ (irrational); $b\cdot c=37.5$ (rational).`,
    modelSolution: String.raw`$a=\sqrt{20}=2\sqrt{5}$ is irrational, so $a+b=2\sqrt{5}+2.5$ is irrational — a rational plus an irrational cannot be written as the ratio of two integers. But $c=\sqrt{225}=15$ is rational, so $b\cdot c=2.5\cdot 15=37.5=\dfrac{75}{2}$, which is a ratio of two integers and therefore rational.`,
    rubric: [
      { credits: 2, criteria: "Two correct explanations are written." },
      { credits: 1, criteria: "One correct explanation is written; OR one conceptual error is made." },
      { credits: 0, criteria: "A zero response that is completely incorrect, irrelevant, or incoherent, or is a correct response arrived at using an obviously incorrect procedure." },
    ],
  },
];

export default bank;
