// Authored Regents problem-bank — Solving Quadratic Equations (AI-A.REI.4),
// plus the sibling "justify a solving step" items (AI-A.REI.1).
//
// Every item is a REAL released Next Generation Algebra I Regents question, cited
// to its NYSED administration. Answers were independently solved & verified;
// model solutions are authored (clean, typeset) rather than scanned student work;
// rubrics are transcribed from the official NYSED Rating Guides. SME-ratified.
//
// Math is written as inline LaTeX ($…$), rendered by <MathText> (KaTeX) — the
// same authoring convention as the .mdx content. Use String.raw so backslashes
// survive the TypeScript string. Do not edit prompts/answers without re-checking
// the source PDF in /tmp/regents/exams (decoded text in /tmp/regents/decoded-*.txt).

import type { RegentsItem, RubricLevel } from "@/lib/regents/bank";

// The shared 4-credit rubric for "solve with the quadratic formula" items.
const QUADRATIC_FORMULA_RUBRIC: RubricLevel[] = [
  { credits: 4, criteria: "Correct answer in simplest radical form, with correct work using the quadratic formula." },
  { credits: 3, criteria: "Appropriate work, but ONE computational or simplification error; OR only one solution is stated." },
  { credits: 2, criteria: String.raw`Two or more errors; OR work reaches $\dfrac{-b \pm \sqrt{b^2 - 4ac}}{2a}$ with no further work; OR the correct answer by a method OTHER than the quadratic formula.` },
  { credits: 1, criteria: "A correct substitution into the quadratic formula, but no further correct work; OR the final answer with no work shown." },
  { credits: 0, criteria: "A response with no relevant course-level work." },
];

const bank: RegentsItem[] = [
  // ---- Constructed-response (self-score) ----
  {
    id: "sq-cr-0624-q33",
    mode: "self-score",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — quadratic formula",
    examCitation: "regents-algI-0624-q33",
    part: "III",
    credits: 4,
    prompt: String.raw`Use the quadratic formula to solve the equation $3x^2 - 10x + 5 = 0$. Express the answer in simplest radical form.`,
    answerSummary: String.raw`$x = \dfrac{5 \pm \sqrt{10}}{3}$`,
    modelSolution: String.raw`With $a = 3$, $b = -10$, $c = 5$, the discriminant is $b^2 - 4ac = 100 - 60 = 40$. So $x = \dfrac{10 \pm \sqrt{40}}{6} = \dfrac{10 \pm 2\sqrt{10}}{6} = \dfrac{5 \pm \sqrt{10}}{3}$.`,
    rubric: QUADRATIC_FORMULA_RUBRIC,
  },
  {
    id: "sq-cr-0624-q29",
    mode: "self-score",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — completing the square",
    examCitation: "regents-algI-0624-q29",
    part: "II",
    credits: 2,
    prompt: String.raw`Use the method of completing the square to determine the exact values of $x$ for the equation $x^2 + 10x - 30 = 0$.`,
    answerSummary: String.raw`$x = -5 \pm \sqrt{55}$`,
    modelSolution: String.raw`$x^2 + 10x = 30$. Add $\left(\tfrac{10}{2}\right)^2 = 25$ to both sides: $x^2 + 10x + 25 = 55$, so $(x + 5)^2 = 55$. Then $x + 5 = \pm\sqrt{55}$, giving $x = -5 \pm \sqrt{55}$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$x = -5 \pm \sqrt{55}$, with correct work (completing the square).` },
      { credits: 1, criteria: "One computational error; OR one conceptual error; OR only one solution stated; OR the correct answer by a method OTHER than completing the square; OR the correct answer with no work." },
      { credits: 0, criteria: "A response with no relevant course-level work." },
    ],
  },
  {
    id: "sq-cr-0125-q33",
    mode: "self-score",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — quadratic formula",
    examCitation: "regents-algI-0125-q33",
    part: "III",
    credits: 4,
    prompt: String.raw`Using the quadratic formula, solve $x^2 + 4x - 3 = 0$.`,
    answerSummary: String.raw`$x = -2 \pm \sqrt{7}$`,
    modelSolution: String.raw`With $a = 1$, $b = 4$, $c = -3$, the discriminant is $16 + 12 = 28$. So $x = \dfrac{-4 \pm \sqrt{28}}{2} = \dfrac{-4 \pm 2\sqrt{7}}{2} = -2 \pm \sqrt{7}$.`,
    rubric: QUADRATIC_FORMULA_RUBRIC,
  },
  {
    id: "sq-cr-0625-q32",
    mode: "self-score",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — quadratic formula",
    examCitation: "regents-algI-0625-q32",
    part: "III",
    credits: 4,
    prompt: String.raw`Using the quadratic formula, solve $6x^2 + 2x - 1 = 0$. Express the answer in simplest radical form.`,
    answerSummary: String.raw`$x = \dfrac{-1 \pm \sqrt{7}}{6}$`,
    modelSolution: String.raw`With $a = 6$, $b = 2$, $c = -1$, the discriminant is $4 + 24 = 28$. So $x = \dfrac{-2 \pm \sqrt{28}}{12} = \dfrac{-2 \pm 2\sqrt{7}}{12} = \dfrac{-1 \pm \sqrt{7}}{6}$.`,
    rubric: QUADRATIC_FORMULA_RUBRIC,
  },
  {
    id: "sq-cr-0126-q32",
    mode: "self-score",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — quadratic formula",
    examCitation: "regents-algI-0126-q32",
    part: "III",
    credits: 4,
    prompt: String.raw`Use the quadratic formula to solve $2x^2 - 4x - 3 = 0$, and express the answer in simplest radical form.`,
    answerSummary: String.raw`$x = \dfrac{2 \pm \sqrt{10}}{2}$`,
    modelSolution: String.raw`With $a = 2$, $b = -4$, $c = -3$, the discriminant is $16 + 24 = 40$. So $x = \dfrac{4 \pm \sqrt{40}}{4} = \dfrac{4 \pm 2\sqrt{10}}{4} = \dfrac{2 \pm \sqrt{10}}{2}$.`,
    rubric: QUADRATIC_FORMULA_RUBRIC,
  },

  // ---- Multiple choice (auto-graded) — AI-A.REI.4 ----
  {
    id: "sq-mc-0824-q8",
    mode: "mc",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — completing the square",
    examCitation: "regents-algI-0824-q8",
    part: "I",
    credits: 2,
    prompt: String.raw`Which equation has the same solutions as $x^2 + 6x - 18 = 0$?`,
    choices: [
      String.raw`$(x + 3)^2 = 24$`,
      String.raw`$(x + 3)^2 = 27$`,
      String.raw`$(x + 6)^2 = 24$`,
      String.raw`$(x + 6)^2 = 27$`,
    ],
    answer: 1,
    explanation: String.raw`$x^2 + 6x = 18$; add $\left(\tfrac{6}{2}\right)^2 = 9$ to both sides to get $(x + 3)^2 = 27$.`,
  },
  {
    id: "sq-mc-0625-q11",
    mode: "mc",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — completing the square",
    examCitation: "regents-algI-0625-q11",
    part: "I",
    credits: 2,
    prompt: String.raw`Which equation is equivalent to $x^2 - 6x = 27$?`,
    choices: [
      String.raw`$(x - 3)^2 = 27 - 9$`,
      String.raw`$(x - 3)^2 = 27 + 9$`,
      String.raw`$(x - 3)^2 = 27 + 36$`,
      String.raw`$(x - 3)^2 = 27 - 36$`,
    ],
    answer: 1,
    explanation: String.raw`Add $\left(\tfrac{6}{2}\right)^2 = 9$ to BOTH sides to complete the square, giving $(x - 3)^2 = 27 + 9$.`,
  },
  {
    id: "sq-mc-0126-q23",
    mode: "mc",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — completing the square",
    examCitation: "regents-algI-0126-q23",
    part: "I",
    credits: 2,
    prompt: String.raw`Which equation has the same solution as $x^2 - 6x = 24$?`,
    choices: [
      String.raw`$(x - 3)^2 = 24$`,
      String.raw`$(x - 6)^2 = 24$`,
      String.raw`$(x - 3)^2 = 33$`,
      String.raw`$(x - 6)^2 = 60$`,
    ],
    answer: 2,
    explanation: String.raw`Add $\left(\tfrac{6}{2}\right)^2 = 9$ to both sides: $(x - 3)^2 = 24 + 9 = 33$.`,
  },
  {
    id: "sq-mc-0126-q17",
    mode: "mc",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — in context",
    examCitation: "regents-algI-0126-q17",
    part: "I",
    credits: 2,
    prompt: String.raw`The point $(x, -6)$ lies on the graph of a parabola whose equation is $y = -x^2 - x + 6$. The value of $x$ can be`,
    choices: [
      String.raw`$-3$ or $2$`,
      String.raw`$-4$ or $3$`,
      String.raw`$3$, only`,
      String.raw`$-4$, only`,
    ],
    answer: 1,
    explanation: String.raw`Set $-6 = -x^2 - x + 6$, which gives $x^2 + x - 12 = 0$, then $(x + 4)(x - 3) = 0$, so $x = -4$ or $3$.`,
  },

  // ---- Multiple choice — sibling skill: justify a solving step (AI-A.REI.1) ----
  {
    id: "sq-mc-0824-q6",
    mode: "mc",
    standard: "AI-A.REI.1",
    topic: "Justifying a solving step",
    examCitation: "regents-algI-0824-q6",
    part: "I",
    credits: 2,
    prompt: String.raw`When solving the equation $4x^2 - 16 = 0$, Laura wrote $4x^2 = 16$ as her first step. Which property justifies Laura's first step?`,
    choices: [
      "distributive property of multiplication over addition",
      "multiplication property of equality",
      "commutative property of addition",
      "addition property of equality",
    ],
    answer: 3,
    explanation: String.raw`She added $16$ to both sides — the addition property of equality.`,
  },
  {
    id: "sq-mc-0625-q8",
    mode: "mc",
    standard: "AI-A.REI.1",
    topic: "Justifying a solving step",
    examCitation: "regents-algI-0625-q8",
    part: "I",
    credits: 2,
    prompt: String.raw`Chloe is solving the equation $x^2 + 5x = 3x + 3$. Her first step gives $x^2 + 2x - 3 = 0$. Which property justifies this step?`,
    choices: [
      "the zero product property",
      "the commutative property",
      "the distributive property",
      "the subtraction property of equality",
    ],
    answer: 3,
    explanation: String.raw`She subtracted $3x + 3$ from both sides — the subtraction property of equality.`,
  },
  {
    id: "sq-mc-0125-q14",
    mode: "mc",
    standard: "AI-A.REI.1",
    topic: "Justifying a solving step",
    examCitation: "regents-algI-0125-q14",
    part: "I",
    credits: 2,
    prompt: String.raw`Stephanie is solving the equation $x^2 - 12 = 7x - 8$. Her first step gives $x^2 - 4 = 7x$. Which property justifies her first step?`,
    choices: [
      "associative property",
      "commutative property",
      "distributive property",
      "addition property of equality",
    ],
    answer: 3,
    explanation: String.raw`She added $8$ to both sides — the addition property of equality.`,
  },

  // ——— Part I: the square-root method (x² = k) ———
  {
    id: "sq-mc-0623-q18",
    mode: "mc",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — square roots",
    examCitation: "regents-algI-0623-q18",
    part: "I",
    credits: 2,
    prompt: String.raw`The solution to $2x^2 = 72$ is`,
    choices: [String.raw`$\{9, 4\}$`, String.raw`$\{-4, 9\}$`, String.raw`$\{6\}$`, String.raw`$\{\pm 6\}$`],
    answer: 3,
    explanation: String.raw`Divide both sides by $2$: $x^2 = 36$. Take the square root of both sides — keeping both signs: $x = \pm 6$.`,
  },
  {
    id: "sq-mc-0814-q03",
    mode: "mc",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — square roots",
    examCitation: "regents-algI-0814-q03",
    part: "I",
    credits: 2,
    prompt: String.raw`If $4x^2 - 100 = 0$, the roots of the equation are`,
    choices: [
      String.raw`$-25$ and $25$`,
      String.raw`$-25$, only`,
      String.raw`$-5$ and $5$`,
      String.raw`$-5$, only`,
    ],
    answer: 2,
    explanation: String.raw`Add $100$ and divide by $4$: $x^2 = 25$. Take the square root of both sides: $x = \pm 5$, so $-5$ and $5$.`,
  },
  {
    id: "sq-mc-0117-q15",
    mode: "mc",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — square roots",
    examCitation: "regents-algI-0117-q15",
    part: "I",
    credits: 2,
    prompt: String.raw`Which value of $x$ is a solution to the equation $13 - 36x^2 = -12$?`,
    choices: [
      String.raw`$\frac{36}{25}$`,
      String.raw`$\frac{25}{36}$`,
      String.raw`$-\frac{6}{5}$`,
      String.raw`$-\frac{5}{6}$`,
    ],
    answer: 3,
    explanation: String.raw`$13 - 36x^2 = -12$ gives $-36x^2 = -25$, so $x^2 = \frac{25}{36}$ and $x = \pm\frac{5}{6}$. Of the choices, $-\frac{5}{6}$ is a solution.`,
  },

  // ——— Part I: roots that need the quadratic formula (won't factor over integers) ———
  {
    id: "sq-mc-0619-q21",
    mode: "mc",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — quadratic formula",
    examCitation: "regents-algI-0619-q21",
    part: "I",
    credits: 2,
    prompt: String.raw`The roots of $x^2 - 5x - 4 = 0$ are`,
    choices: [
      String.raw`$1$ and $4$`,
      String.raw`$\dfrac{5 \pm \sqrt{41}}{2}$`,
      String.raw`$-1$ and $-4$`,
      String.raw`$\dfrac{-5 \pm \sqrt{41}}{2}$`,
    ],
    answer: 1,
    explanation: String.raw`No integer factors of $-4$ add to $-5$, so factoring fails — use the quadratic formula with $a = 1$, $b = -5$, $c = -4$. The discriminant is $(-5)^2 - 4(1)(-4) = 25 + 16 = 41$, giving $x = \dfrac{5 \pm \sqrt{41}}{2}$.`,
  },
  {
    id: "sq-mc-0626-q22",
    mode: "mc",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — quadratic formula",
    examCitation: "regents-algI-0626-q22",
    part: "I",
    credits: 2,
    prompt: String.raw`When solving the equation $2x^2 - 3x - 6 = 0$ using the quadratic formula, the solutions are`,
    choices: [
      String.raw`$\dfrac{3 \pm \sqrt{57}}{4}$`,
      String.raw`$\dfrac{3 \pm \sqrt{39}}{4}$`,
      String.raw`$\dfrac{-3 \pm \sqrt{57}}{4}$`,
      String.raw`$\dfrac{-3 \pm \sqrt{39}}{4}$`,
    ],
    answer: 0,
    explanation: String.raw`With $a = 2$, $b = -3$, $c = -6$: the discriminant is $(-3)^2 - 4(2)(-6) = 9 + 48 = 57$, and $-b = 3$, $2a = 4$, so $x = \dfrac{3 \pm \sqrt{57}}{4}$.`,
  },

  // ——— Part II: solve for exact values by the square-root method (self-score) ———
  {
    id: "sq-cr-0819-q31",
    mode: "self-score",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — exact values",
    examCitation: "regents-algI-0819-q31",
    part: "II",
    credits: 2,
    prompt: String.raw`Solve $6x^2 - 42 = 0$ for the exact values of $x$.`,
    answerSummary: String.raw`$x = \pm\sqrt{7}$`,
    modelSolution: String.raw`Add $42$ to both sides: $6x^2 = 42$. Divide by $6$: $x^2 = 7$. Take the square root of both sides, keeping both signs: $x = \pm\sqrt{7}$. (Leave it as a radical — that is the *exact* value.)`,
    rubric: [
      { credits: 2, criteria: String.raw`$\pm\sqrt{7}$, and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made; OR one conceptual error is made; OR only one root is stated; OR the answers are expressed as decimals; OR $\pm\sqrt{7}$ with no work shown.` },
      { credits: 0, criteria: "A response that is completely incorrect, irrelevant, or incoherent, or a correct answer obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "sq-cr-0119-q32",
    mode: "self-score",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — exact values",
    examCitation: "regents-algI-0119-q32",
    part: "II",
    credits: 2,
    prompt: String.raw`Solve the quadratic equation $4x^2 - 5 = 75$ for the exact values of $x$.`,
    answerSummary: String.raw`$x = \pm\sqrt{20}$ (equivalently $\pm 2\sqrt{5}$)`,
    modelSolution: String.raw`Add $5$: $4x^2 = 80$. Divide by $4$: $x^2 = 20$. Take the square root of both sides: $x = \pm\sqrt{20}$, which simplifies to $\pm 2\sqrt{5}$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$\pm\sqrt{20}$ (or $\pm 2\sqrt{5}$), and correct work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made; OR one conceptual error is made; OR the answer is expressed as a decimal; OR only one solution is stated; OR $\pm\sqrt{20}$ with no work shown.` },
      { credits: 0, criteria: "A response that is completely incorrect, irrelevant, or incoherent, or a correct answer obtained by an obviously incorrect procedure." },
    ],
  },

  // ——— Part II: solve by factoring (self-score) ———
  {
    id: "sq-cr-0119-q27",
    mode: "self-score",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — factoring",
    examCitation: "regents-algI-0119-q27",
    part: "II",
    credits: 2,
    prompt: String.raw`Solve $x^2 - 8x - 9 = 0$ algebraically. Explain the first step you used to solve the equation.`,
    answerSummary: String.raw`$x = 9$ and $x = -1$`,
    modelSolution: String.raw`**First step:** factor the trinomial into two binomials — find two numbers that multiply to $-9$ and add to $-8$ (namely $-9$ and $+1$): $x^2 - 8x - 9 = (x - 9)(x + 1)$. By the zero-product property, set each factor equal to $0$: $x - 9 = 0$ or $x + 1 = 0$, giving $x = 9$ or $x = -1$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$-1$ and $9$, and a correct explanation is written.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational or factoring error is made; OR one conceptual error is made; OR appropriate algebraic work is shown to find $-1$ and $9$, but no explanation is written.` },
      { credits: 0, criteria: String.raw`$-1$ and $9$, but no work is shown; OR a response with no relevant course-level work.` },
    ],
  },
  {
    id: "sq-cr-0622-q30",
    mode: "self-score",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — factoring",
    examCitation: "regents-algI-0622-q30",
    part: "II",
    credits: 2,
    prompt: String.raw`Solve $6x^2 - 5x - 6 = 0$ algebraically for the exact values of $x$.`,
    answerSummary: String.raw`$x = \frac{3}{2}$ and $x = -\frac{2}{3}$`,
    modelSolution: String.raw`Factor (looking for factors of $6 \cdot (-6) = -36$ that add to $-5$: $-9$ and $4$): $6x^2 - 5x - 6 = (2x - 3)(3x + 2)$. Set each factor equal to $0$: $2x - 3 = 0 \Rightarrow x = \frac{3}{2}$, and $3x + 2 = 0 \Rightarrow x = -\frac{2}{3}$.`,
    rubric: [
      { credits: 2, criteria: String.raw`$\frac{3}{2}$ and $-\frac{2}{3}$ (or equivalent), and correct algebraic work is shown.` },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one computational error is made; OR one conceptual error is made; OR the correct values are found by a method other than algebraic; OR $\frac{3}{2}$ and $-\frac{2}{3}$ with no work shown.` },
      { credits: 0, criteria: "A response that is completely incorrect, irrelevant, or incoherent, or a correct answer obtained by an obviously incorrect procedure." },
    ],
  },

  // ——— Part I: the square-root method on a binomial square — (x ± h)² = k ———
  {
    id: "sq-mc-0120-q15",
    mode: "mc",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — square roots",
    examCitation: "regents-algI-0120-q15",
    part: "I",
    credits: 2,
    prompt: String.raw`The solutions to $(x + 4)^2 - 2 = 7$ are`,
    choices: [
      String.raw`$-4 \pm \sqrt{5}$`,
      String.raw`$4 \pm \sqrt{5}$`,
      String.raw`$-1$ and $-7$`,
      String.raw`$1$ and $7$`,
    ],
    answer: 2,
    explanation: String.raw`Add $2$ to both sides: $(x + 4)^2 = 9$. Take the square root of both sides, keeping both signs: $x + 4 = \pm 3$, so $x = -1$ or $x = -7$.`,
  },
  {
    id: "sq-mc-0815-q23",
    mode: "mc",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — square roots",
    examCitation: "regents-algI-0815-q23",
    part: "I",
    credits: 2,
    prompt: String.raw`The solution of the equation $(x + 3)^2 = 7$ is`,
    choices: [
      String.raw`$3 \pm \sqrt{7}$`,
      String.raw`$7 \pm \sqrt{3}$`,
      String.raw`$-3 \pm \sqrt{7}$`,
      String.raw`$-7 \pm \sqrt{3}$`,
    ],
    answer: 2,
    explanation: String.raw`Take the square root of both sides: $x + 3 = \pm\sqrt{7}$, so $x = -3 \pm \sqrt{7}$.`,
  },
  {
    id: "sq-mc-0615-q21",
    mode: "mc",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — square roots",
    examCitation: "regents-algI-0615-q21",
    part: "I",
    credits: 2,
    prompt: String.raw`A student is asked to solve the equation $4(3x - 1)^2 - 17 = 83$. The student's solution begins $4(3x - 1)^2 = 100$, then $(3x - 1)^2 = 25$. A correct next step in the solution is`,
    choices: [
      String.raw`$3x - 1 = \pm 5$`,
      String.raw`$3x - 1 = \pm 25$`,
      String.raw`$9x^2 - 1 = 25$`,
      String.raw`$9x^2 - 6x + 1 = 5$`,
    ],
    answer: 0,
    explanation: String.raw`Take the square root of both sides of $(3x - 1)^2 = 25$, keeping both signs: $3x - 1 = \pm 5$.`,
  },
  {
    id: "sq-mc-0118-q14",
    mode: "mc",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — square roots",
    examCitation: "regents-algI-0118-q14",
    part: "I",
    credits: 2,
    prompt: String.raw`What are the solutions to the equation $3(x - 4)^2 = 27$?`,
    choices: [
      String.raw`$1$ and $7$`,
      String.raw`$-1$ and $-7$`,
      String.raw`$4 \pm \sqrt{24}$`,
      String.raw`$-4 \pm \sqrt{24}$`,
    ],
    answer: 0,
    explanation: String.raw`Divide both sides by $3$: $(x - 4)^2 = 9$. Take the square root of both sides: $x - 4 = \pm 3$, so $x = 7$ or $x = 1$.`,
  },

  // ——— Part I: more factoring — GCF, "equivalent factored form," leading coefficient ———
  {
    id: "sq-mc-0825-q10",
    mode: "mc",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — factoring",
    examCitation: "regents-algI-0825-q10",
    part: "I",
    credits: 2,
    prompt: String.raw`What is the solution set of the equation $3x^2 = 24x$?`,
    choices: [
      String.raw`$\{8\}$`,
      String.raw`$\{0, 8\}$`,
      String.raw`$\{0, -8\}$`,
      String.raw`$\{0, 8, -8\}$`,
    ],
    answer: 1,
    explanation: String.raw`Move everything to one side: $3x^2 - 24x = 0$, then factor out the GCF: $3x(x - 8) = 0$, so $x = 0$ or $x = 8$. (Do not divide both sides by $x$ — that discards the root $x = 0$.)`,
  },
  {
    id: "sq-mc-0115-q03",
    mode: "mc",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — factoring",
    examCitation: "regents-algI-0115-q03",
    part: "I",
    credits: 2,
    prompt: String.raw`Which equation has the same solutions as $2x^2 + x - 3 = 0$?`,
    choices: [
      String.raw`$(2x - 1)(x + 3) = 0$`,
      String.raw`$(2x + 1)(x - 3) = 0$`,
      String.raw`$(2x - 3)(x + 1) = 0$`,
      String.raw`$(2x + 3)(x - 1) = 0$`,
    ],
    answer: 3,
    explanation: String.raw`Factor: find factors of $2 \cdot (-3) = -6$ that add to $1$ — namely $+3$ and $-2$. So $2x^2 + 3x - 2x - 3 = (2x + 3)(x - 1)$.`,
  },
  {
    id: "sq-mc-0816-q19",
    mode: "mc",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — factoring",
    examCitation: "regents-algI-0816-q19",
    part: "I",
    credits: 2,
    prompt: String.raw`What are the solutions to the equation $3x^2 + 10x = 8$?`,
    choices: [
      String.raw`$\frac{2}{3}$ and $-4$`,
      String.raw`$-\frac{2}{3}$ and $4$`,
      String.raw`$\frac{4}{3}$ and $-2$`,
      String.raw`$-\frac{4}{3}$ and $2$`,
    ],
    answer: 0,
    explanation: String.raw`Set equal to zero: $3x^2 + 10x - 8 = 0$, then factor: $(3x - 2)(x + 4) = 0$, so $x = \frac{2}{3}$ or $x = -4$.`,
  },

  // ——— Part I: the discriminant — number/nature of the roots ———
  {
    id: "sq-mc-0618-q22",
    mode: "mc",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — the discriminant",
    examCitation: "regents-algI-0618-q22",
    part: "I",
    credits: 2,
    prompt: String.raw`How many real-number solutions does $4x^2 + 2x + 5 = 0$ have?`,
    choices: ["one", "two", "zero", "infinitely many"],
    answer: 2,
    explanation: String.raw`The discriminant is $b^2 - 4ac = 2^2 - 4(4)(5) = 4 - 80 = -76$. A negative discriminant means the equation has no real solutions.`,
  },

  // ——— Part II: justify rational vs. irrational roots from the discriminant (self-score) ———
  {
    id: "sq-cr-0818-q28",
    mode: "self-score",
    standard: "AI-A.REI.4",
    topic: "Solving quadratics — the discriminant",
    examCitation: "regents-algI-0818-q28",
    part: "II",
    credits: 2,
    prompt: String.raw`Is the solution to the quadratic equation written below rational or irrational? Justify your answer.
$$0 = 2x^2 + 3x - 10$$`,
    answerSummary: String.raw`Irrational`,
    modelSolution: String.raw`The nature of the roots is settled by the discriminant $b^2 - 4ac$. With $a = 2$, $b = 3$, $c = -10$: $b^2 - 4ac = 3^2 - 4(2)(-10) = 9 + 80 = 89$. Because $89$ is positive but not a perfect square, $\sqrt{89}$ is irrational, so the solutions are irrational.`,
    rubric: [
      { credits: 2, criteria: "Irrational, and a correct justification is given." },
      { credits: 1, criteria: "Appropriate work is shown, but one computational error is made; OR appropriate work is shown, but one conceptual error is made." },
      { credits: 0, criteria: "Irrational, but no justification is given; OR a response that is completely incorrect, irrelevant, or incoherent, or a correct answer obtained by an obviously incorrect procedure." },
    ],
  },
];

export default bank;
