// Authored Regents problem-bank — Systems of Equations. Covers linear-quadratic
// systems (AI-A.REI.7) and linear systems (AI-A.REI.6), the way the exam groups
// them. Every item is a REAL released Next Generation Algebra I Regents question,
// cited to its NYSED administration; answers independently solved & verified;
// model solutions authored; rubrics transcribed from the official Rating Guides.
//
// Items here are the algebraically-solved ones (no graph required) — figure-based
// "graph the system" items are deferred until the bank supports figures.
//
// Math is inline LaTeX ($…$); a literal dollar sign (currency) is written `\$`.
// Use String.raw so backslashes survive the TypeScript string.

import type { RegentsItem, RubricLevel } from "@/lib/regents/bank";

// Shared 4-credit rubric for "solve the linear-quadratic system algebraically".
const LINEAR_QUADRATIC_RUBRIC: RubricLevel[] = [
  { credits: 4, criteria: "Both solution pairs, with correct algebraic work (the two expressions for y set equal and the resulting quadratic solved)." },
  { credits: 3, criteria: "One computational or factoring error; OR both x-values are found but no further correct work; OR one complete (x, y) pair is found but no further work." },
  { credits: 2, criteria: "Two or more errors; OR one conceptual error; OR the resulting quadratic is factored correctly but no further correct work is shown." },
  { credits: 1, criteria: "A correct first step (the two expressions for y set equal to each other) is shown, but no further correct work." },
  { credits: 0, criteria: "A response with no relevant course-level work." },
];

const bank: RegentsItem[] = [
  // ---- Linear-quadratic systems (AI-A.REI.7) ----
  {
    id: "sys-cr-0824-q34",
    mode: "self-score",
    standard: "AI-A.REI.7",
    topic: "Systems — linear-quadratic (solve algebraically)",
    examCitation: "regents-algI-0824-q34",
    part: "III",
    credits: 4,
    prompt: String.raw`Solve the system of equations algebraically for all values of $x$ and $y$: $y = x^2 + 4x - 1$ and $y = 2x + 7$.`,
    answerSummary: String.raw`$(-4, -1)$ and $(2, 11)$`,
    modelSolution: String.raw`Set the expressions for $y$ equal: $x^2 + 4x - 1 = 2x + 7$, so $x^2 + 2x - 8 = 0$ and $(x + 4)(x - 2) = 0$, giving $x = -4$ or $x = 2$. Then $y = 2x + 7$ gives $y = -1$ at $x = -4$ and $y = 11$ at $x = 2$: the solutions are $(-4, -1)$ and $(2, 11)$.`,
    rubric: LINEAR_QUADRATIC_RUBRIC,
  },
  {
    id: "sys-cr-0125-q34",
    mode: "self-score",
    standard: "AI-A.REI.7",
    topic: "Systems — linear-quadratic (solve algebraically)",
    examCitation: "regents-algI-0125-q34",
    part: "III",
    credits: 4,
    prompt: String.raw`Solve the system of equations algebraically for all values of $x$ and $y$: $y = x^2 - 7x + 12$ and $y = 2x - 6$.`,
    answerSummary: String.raw`$(3, 0)$ and $(6, 6)$`,
    modelSolution: String.raw`Set them equal: $x^2 - 7x + 12 = 2x - 6$, so $x^2 - 9x + 18 = 0$ and $(x - 3)(x - 6) = 0$, giving $x = 3$ or $x = 6$. Then $y = 2x - 6$ gives $y = 0$ at $x = 3$ and $y = 6$ at $x = 6$: the solutions are $(3, 0)$ and $(6, 6)$.`,
    rubric: LINEAR_QUADRATIC_RUBRIC,
  },
  {
    id: "sys-cr-0625-q34",
    mode: "self-score",
    standard: "AI-A.REI.7",
    topic: "Systems — linear-quadratic (solve algebraically)",
    examCitation: "regents-algI-0625-q34",
    part: "III",
    credits: 4,
    prompt: String.raw`Solve the system of equations algebraically for all values of $x$ and $y$: $y = x^2 + 9x + 4$ and $y - 2x = -6$.`,
    answerSummary: String.raw`$(-2, -10)$ and $(-5, -16)$`,
    modelSolution: String.raw`Rewrite the line as $y = 2x - 6$, then set equal: $x^2 + 9x + 4 = 2x - 6$, so $x^2 + 7x + 10 = 0$ and $(x + 2)(x + 5) = 0$, giving $x = -2$ or $x = -5$. Then $y = 2x - 6$ gives $y = -10$ at $x = -2$ and $y = -16$ at $x = -5$: the solutions are $(-2, -10)$ and $(-5, -16)$.`,
    rubric: LINEAR_QUADRATIC_RUBRIC,
  },

  {
    id: "sys-cr-0624-q31",
    mode: "self-score",
    standard: "AI-A.REI.7",
    topic: "Systems — graph a linear-quadratic system",
    examCitation: "regents-algI-0624-q31",
    part: "III",
    credits: 4,
    prompt: String.raw`Graph the system $y = x^2 - 3x - 6$ and $y = x - 1$ on a set of axes, and state the coordinates of all solutions.`,
    answerSummary: String.raw`$(-1, -2)$ and $(5, 4)$`,
    modelSolution: String.raw`The parabola and line meet where $x^2 - 3x - 6 = x - 1$, i.e. $x^2 - 4x - 5 = 0$, so $(x - 5)(x + 1) = 0$ and $x = 5$ or $x = -1$. Using $y = x - 1$, the intersection points are $(5, 4)$ and $(-1, -2)$ — the solutions, shown below.`,
    solutionFigure: {
      kind: "plot",
      range: 10,
      curves: [
        { kind: "parabola", a: 1, b: -3, c: -6 },
        { kind: "line", m: 1, b: -1 },
      ],
      points: [
        { x: -1, y: -2, label: "(-1, -2)" },
        { x: 5, y: 4, label: "(5, 4)" },
      ],
      caption: "y = x² − 3x − 6 (blue) meets y = x − 1 (orange) at (−1, −2) and (5, 4).",
    },
    rubric: [
      { credits: 4, criteria: String.raw`Correct graphs are drawn, and $(-1, -2)$ and $(5, 4)$ are stated.` },
      { credits: 3, criteria: "One graphing error; OR only one point's coordinates are stated correctly; OR the solutions are indicated on the graph but the coordinates are not stated." },
      { credits: 2, criteria: String.raw`Both equations are graphed correctly but no further work; OR $(-1, -2)$ and $(5, 4)$ are stated, but a method other than graphing is used.` },
      { credits: 1, criteria: String.raw`One equation is graphed correctly but no further work; OR $(-1, -2)$ and $(5, 4)$ are stated with no work shown.` },
      { credits: 0, criteria: "A response with no relevant course-level work." },
    ],
  },

  // ---- Linear systems (AI-A.REI.6) ----
  {
    id: "sys-mc-0126-q10",
    mode: "mc",
    standard: "AI-A.REI.6",
    topic: "Systems — the substitution method",
    examCitation: "regents-algI-0126-q10",
    part: "I",
    credits: 2,
    prompt: String.raw`When solving the system $3x - y = 10$ and $2x + 5y = 1$ algebraically, Mason used the substitution method. Which equation could he have used?`,
    choices: [
      String.raw`$2(3x - 10) + 5x = 1$`,
      String.raw`$2(-3x + 10) + 5x = 1$`,
      String.raw`$2x + 5(3x - 10) = 1$`,
      String.raw`$2x + 5(-3x + 10) = 1$`,
    ],
    answer: 2,
    explanation: String.raw`Solve $3x - y = 10$ for $y$: $y = 3x - 10$. Substitute into $2x + 5y = 1$: $2x + 5(3x - 10) = 1$.`,
  },
  {
    id: "sys-cr-0125-q31",
    mode: "self-score",
    standard: "AI-A.REI.6",
    topic: "Systems — linear word problem",
    examCitation: "regents-algI-0125-q31",
    part: "III",
    credits: 4,
    prompt: String.raw`Alex had \$1.70 in nickels and dimes on his desk; there were 25 coins in all. Write a system of equations to determine the number of nickels, $n$, and dimes, $d$, then solve it algebraically to find how many of each he had.`,
    answerSummary: String.raw`$16$ nickels and $9$ dimes`,
    modelSolution: String.raw`System: $n + d = 25$ and $0.05n + 0.10d = 1.70$. Substitute $d = 25 - n$: $0.05n + 0.10(25 - n) = 1.70$, so $0.05n + 2.5 - 0.10n = 1.70$ and $-0.05n = -0.80$, giving $n = 16$ and $d = 9$.`,
    rubric: [
      { credits: 4, criteria: String.raw`$n + d = 25$ and $0.05n + 0.10d = 1.70$, with $n = 16$ and $d = 9$, and correct algebraic work.` },
      { credits: 3, criteria: "One computational error; OR only one of n = 16 or d = 9 is found; OR one equation is written incorrectly but the system is solved appropriately." },
      { credits: 2, criteria: "Two or more computational errors; OR a correct system is written but no further correct work is shown." },
      { credits: 1, criteria: "One equation is written correctly but no further correct work; OR n = 16 and d = 9 are found by a method other than algebraic; OR the answer is given with no work." },
      { credits: 0, criteria: "A response with no relevant course-level work." },
    ],
  },
  {
    id: "sys-cr-0824-q35",
    mode: "self-score",
    standard: "AI-A.REI.6",
    topic: "Systems — linear word problem",
    examCitation: "regents-algI-0824-q35",
    part: "IV",
    credits: 6,
    prompt: String.raw`At a movie theater, admission prices stay the same in May and June. In May, Jen saw 2 matinees and 3 regular shows and spent \$38.50. In June, she saw 6 matinees and 1 regular show and spent \$47.50. Write a system of equations for the cost $m$ of a matinee ticket and $r$ of a regular ticket. Jen said she spent \$5.75 on each matinee and \$9 on each regular show — is she correct? Justify your answer. Then use your system to algebraically determine the actual cost of each ticket.`,
    answerSummary: String.raw`Matinee \$6.50, regular \$8.50 — Jen is not correct.`,
    modelSolution: String.raw`Let $m$ and $r$ be the matinee and regular costs. System: $2m + 3r = 38.50$ and $6m + r = 47.50$. Jen's guess (\$5.75, \$9) satisfies May ($2(5.75) + 3(9) = 38.50$) but not June ($6(5.75) + 9 = 43.50 \ne 47.50$), so she is not correct. From the second equation $r = 47.50 - 6m$; substituting, $2m + 3(47.50 - 6m) = 38.50$, so $-16m = -104$ and $m = 6.50$, giving $r = 8.50$.`,
    rubric: [
      { credits: 6, criteria: "A correct system is written, a correct justification that Jen is incorrect is given, and correct algebraic work finds m = 6.50 and r = 8.50." },
      { credits: 5, criteria: "One computational error; OR only one of m = 6.50 or r = 8.50 is found; OR one equation is written incorrectly but used appropriately; OR a non-algebraic method is used to find the costs." },
      { credits: 4, criteria: "Two or more computational errors; OR a correct system is written and solved but no justification; OR a correct system and justification but the system is not solved." },
      { credits: 3, criteria: "A correct system is written but the justification is incomplete and no further correct work is shown." },
      { credits: 2, criteria: "A correct system is written but no further correct work; OR a correct justification is given but no further correct work." },
      { credits: 1, criteria: "One correct equation is written, but no further correct work." },
      { credits: 0, criteria: "A response with no relevant course-level work." },
    ],
  },

  // ——— Setting up the method: elimination & substitution (AI-A.REI.6) ———
  {
    id: "sys-mc-0118-q15",
    mode: "mc",
    standard: "AI-A.REI.6",
    topic: "Systems — the elimination method",
    examCitation: "regents-algI-0118-q15",
    part: "I",
    credits: 2,
    prompt: String.raw`A system of equations is shown: Equation A is $5x + 9y = 12$ and Equation B is $4x - 3y = 8$. Which method eliminates one of the variables?`,
    choices: [
      String.raw`Multiply equation A by $-\frac{1}{3}$ and add the result to equation B.`,
      "Multiply equation B by 3 and add the result to equation A.",
      String.raw`Multiply equation A by 2 and equation B by $-6$ and add the results together.`,
      "Multiply equation B by 5 and equation A by 4 and add the results together.",
    ],
    answer: 1,
    explanation: String.raw`Multiplying equation B by $3$ gives $12x - 9y = 24$. Adding that to equation A ($5x + 9y = 12$) cancels the $y$ terms ($9y - 9y = 0$), leaving $17x = 36$ — one variable eliminated.`,
  },
  {
    id: "sys-mc-0825-q23",
    mode: "mc",
    standard: "AI-A.REI.6",
    topic: "Systems — substitution (first step)",
    examCitation: "regents-algI-0825-q23",
    part: "I",
    credits: 2,
    prompt: String.raw`The substitution method is used to solve the system $4x - 7y = 7$ and $x - y = -1$. Which equation is a correct first step?`,
    choices: [
      String.raw`$x = y - 1$`,
      String.raw`$y = x - 1$`,
      String.raw`$3x - 6y = 8$`,
      String.raw`$5x - 8y = 6$`,
    ],
    answer: 0,
    explanation: String.raw`Solve the simpler equation $x - y = -1$ for a variable. Adding $y$ to both sides gives $x = y - 1$. (Choice 2 has the sign wrong: $x - y = -1$ rearranges to $y = x + 1$, not $x - 1$.)`,
  },
  {
    id: "sys-mc-0119-q22",
    mode: "mc",
    standard: "AI-A.REI.6",
    topic: "Systems — substitution (isolate, then replace)",
    examCitation: "regents-algI-0119-q22",
    part: "I",
    credits: 2,
    prompt: String.raw`Using the substitution method, Vito is solving $y + 3x = -4$ and $2x - 3y = -21$. Which equivalent equation could Vito use?`,
    choices: [
      String.raw`$2(-3x - 4) + 3x = -21$`,
      String.raw`$2(3x - 4) + 3x = -21$`,
      String.raw`$2x - 3(-3x - 4) = -21$`,
      String.raw`$2x - 3(3x - 4) = -21$`,
    ],
    answer: 2,
    explanation: String.raw`Isolate $y$ in the first equation: $y + 3x = -4$ gives $y = -3x - 4$ (watch the sign). Substitute that for $y$ in the *other* equation, $2x - 3y = -21$: $2x - 3(-3x - 4) = -21$.`,
  },
  {
    id: "sys-mc-0625-q10",
    mode: "mc",
    standard: "AI-A.REI.6",
    topic: "Systems — substitution (a correct step)",
    examCitation: "regents-algI-0625-q10",
    part: "I",
    credits: 2,
    prompt: String.raw`Given the system $y + 4x = 5$ and $2x - 3y = 10$, a step in solving by substitution would be`,
    choices: [
      String.raw`$2(5 - 4x) + 4x = 5$`,
      String.raw`$2(5 + 4x) + 4x = 5$`,
      String.raw`$2x - 3(5 - 4x) = 10$`,
      String.raw`$2x - 3(5 + 4x) = 10$`,
    ],
    answer: 2,
    explanation: String.raw`Isolate $y$: $y + 4x = 5$ gives $y = 5 - 4x$. Substitute into the other equation, $2x - 3y = 10$: $2x - 3(5 - 4x) = 10$.`,
  },

  // ——— Producing an equivalent system (A.REI.5/6) ———
  {
    id: "sys-mc-0818-q22",
    mode: "mc",
    standard: "AI-A.REI.6",
    topic: "Systems — an equivalent system",
    examCitation: "regents-algI-0818-q22",
    part: "I",
    credits: 2,
    prompt: String.raw`Which system of equations will yield the same solution as the system below? $x - y = 3$ and $2x - 3y = -1$.`,
    choices: [
      String.raw`$-2x - 2y = -6$ and $2x - 3y = -1$`,
      String.raw`$-2x + 2y = 3$ and $2x - 3y = -1$`,
      String.raw`$-2x + 2y = -6$ and $2x - 3y = -1$`,
      String.raw`$3x + 3y = 9$ and $2x - 3y = -1$`,
    ],
    answer: 2,
    explanation: String.raw`Multiplying $x - y = 3$ by $-2$ gives $-2x + 2y = -6$. Pairing that with the unchanged second equation produces a system with the same solution.`,
  },
  {
    id: "sys-mc-0819-q22",
    mode: "mc",
    standard: "AI-A.REI.6",
    topic: "Systems — an equivalent system",
    examCitation: "regents-algI-0819-q22",
    part: "I",
    credits: 2,
    prompt: String.raw`Which system of linear equations has the same solution as the system below? $x - 4y = -10$ and $x + y = 5$.`,
    choices: [
      String.raw`$5x = 10$ and $x + y = 5$`,
      String.raw`$-5y = -5$ and $x + y = 5$`,
      String.raw`$-3x = -30$ and $-5y = -5$`,
      String.raw`$-5y = -5$ and $x - 4y = -10$`,
    ],
    answer: 0,
    explanation: String.raw`Multiply $x + y = 5$ by $4$ to get $4x + 4y = 20$, then add it to $x - 4y = -10$: the $y$ terms cancel and you get $5x = 10$. Pairing $5x = 10$ with $x + y = 5$ keeps the same solution.`,
  },
  {
    id: "sys-mc-0614-q14",
    mode: "mc",
    standard: "AI-A.REI.6",
    topic: "Systems — an equivalent system",
    examCitation: "regents-algI-0614-q14",
    part: "I",
    credits: 2,
    prompt: String.raw`Which system of equations has the same solution as the system below? $2x + 2y = 16$ and $3x - y = 4$.`,
    choices: [
      String.raw`$2x + 2y = 16$ and $6x - 2y = 4$`,
      String.raw`$2x + 2y = 16$ and $6x - 2y = 8$`,
      String.raw`$x + y = 16$ and $3x - y = 4$`,
      String.raw`$6x + 6y = 48$ and $6x + 2y = 8$`,
    ],
    answer: 1,
    explanation: String.raw`Multiplying $3x - y = 4$ by $2$ gives $6x - 2y = 8$. Keeping $2x + 2y = 16$ unchanged, this is an equivalent system. (Choice 1 has the wrong constant — $2 \times 4 = 8$, not $4$ — and choice 4 changes a sign, giving $6x + 2y = 8$.)`,
  },
  {
    id: "sys-mc-0120-q20",
    mode: "mc",
    standard: "AI-A.REI.6",
    topic: "Systems — an equivalent system",
    examCitation: "regents-algI-0120-q20",
    part: "I",
    credits: 2,
    prompt: String.raw`Which system of equations has the same solutions as the system below? $3x - y = 7$ and $2x + 3y = 12$.`,
    choices: [
      String.raw`$6x - 2y = 14$ and $-6x + 9y = 36$`,
      String.raw`$18x - 6y = 42$ and $4x + 6y = 24$`,
      String.raw`$-9x - 3y = -21$ and $2x + 3y = 12$`,
      String.raw`$3x - y = 7$ and $x + y = 2$`,
    ],
    answer: 1,
    explanation: String.raw`Multiplying $3x - y = 7$ by $6$ gives $18x - 6y = 42$, and multiplying $2x + 3y = 12$ by $2$ gives $4x + 6y = 24$. Both equations are scaled by a nonzero constant, so the solution is unchanged.`,
  },
  {
    id: "sys-mc-0621-q20",
    mode: "mc",
    standard: "AI-A.REI.6",
    topic: "Systems — an equivalent system",
    examCitation: "regents-algI-0621-q20",
    part: "I",
    credits: 2,
    prompt: String.raw`Which system has the same solution as the system below? $x + 3y = 10$ and $-2x - 2y = 4$.`,
    choices: [
      String.raw`$-x + y = 6$ and $2x + 6y = 20$`,
      String.raw`$-x + y = 14$ and $2x + 6y = 20$`,
      String.raw`$x + y = 6$ and $2x + 6y = 20$`,
      String.raw`$x + y = 14$ and $2x + 6y = 20$`,
    ],
    answer: 1,
    explanation: String.raw`The system solves to $(-8, 6)$. In choice 2, $2x + 6y = 20$ is $2(x + 3y = 10)$, and $(-8, 6)$ satisfies $-x + y = 14$ since $8 + 6 = 14$; both equations hold, so it is an equivalent system. The other choices change the constant on the first equation and no longer pass through $(-8, 6)$.`,
  },
  {
    id: "sys-mc-0816-q22",
    mode: "mc",
    standard: "AI-A.REI.6",
    topic: "Systems — an equivalent system",
    examCitation: "regents-algI-0816-q22",
    part: "I",
    credits: 2,
    prompt: String.raw`A system of equations is given: $x + 2y = 5$ and $2x + y = 4$. Which system of equations does *not* have the same solution?`,
    choices: [
      String.raw`$3x + 6y = 15$ and $2x + y = 4$`,
      String.raw`$4x + 8y = 20$ and $2x + y = 4$`,
      String.raw`$x + 2y = 5$ and $6x + 3y = 12$`,
      String.raw`$x + 2y = 5$ and $4x + 2y = 12$`,
    ],
    answer: 3,
    explanation: String.raw`Choices 1–3 each multiply one equation by a nonzero constant ($3$, $4$, and $3$ respectively), so they keep the same solution. In choice 4, $2(2x + y = 4)$ should give $4x + 2y = 8$, but it reads $4x + 2y = 12$ — a different line — so its solution differs.`,
  },
  {
    id: "sys-mc-0116-q21",
    mode: "mc",
    standard: "AI-A.REI.6",
    topic: "Systems — an equivalent system",
    examCitation: "regents-algI-0116-q21",
    part: "I",
    credits: 2,
    prompt: String.raw`Which pair of equations could *not* be used to solve the following equations for $x$ and $y$? $4x + 2y = 22$ and $-2x + 2y = -8$.`,
    choices: [
      String.raw`$4x + 2y = 22$ and $2x - 2y = 8$`,
      String.raw`$4x + 2y = 22$ and $4x - 4y = 16$`,
      String.raw`$12x + 6y = 66$ and $6x - 6y = 24$`,
      String.raw`$8x + 4y = 44$ and $-8x + 8y = -8$`,
    ],
    answer: 3,
    explanation: String.raw`Choices 1–3 each rescale $-2x + 2y = -8$ (by $-1$, $-2$, and $-3$), giving an equivalent system. In choice 4, $-8x + 8y = -8$ simplifies to $-x + y = -1$, but the original $-2x + 2y = -8$ simplifies to $-x + y = -4$ — a different line — so it could not be used.`,
  },
  {
    id: "sys-mc-0617-q08",
    mode: "mc",
    standard: "AI-A.REI.6",
    topic: "Systems — number of solutions",
    examCitation: "regents-algI-0617-q08",
    part: "I",
    credits: 2,
    prompt: String.raw`What is the solution to the system of equations below? $y = 2x + 8$ and $3(-2x + y) = 12$.`,
    choices: [
      "no solution",
      "infinite solutions",
      String.raw`$(-1, 6)$`,
      String.raw`$\left(\frac{1}{2}, 9\right)$`,
    ],
    answer: 0,
    explanation: String.raw`Simplify the second equation: $3(-2x + y) = 12$ gives $-2x + y = 4$, i.e. $y = 2x + 4$. The first line is $y = 2x + 8$. Both have slope $2$ but different $y$-intercepts, so they are parallel and never meet — no solution.`,
  },
  {
    id: "sys-mc-0621-q11",
    mode: "mc",
    standard: "AI-A.REI.6",
    topic: "Systems — intersection of two lines",
    examCitation: "regents-algI-0621-q11",
    part: "I",
    credits: 2,
    prompt: String.raw`Given $f(x) = \frac{2}{3}x - 4$ and $g(x) = \frac{1}{4}x + 1$. Four statements about this system are written below.

I. $f(4) = g(4)$
II. When $x = 12$, $f(x) = g(x)$.
III. The graphs of $f(x)$ and $g(x)$ intersect at $(12, 4)$.
IV. The graphs of $f(x)$ and $g(x)$ intersect at $(4, 12)$.

Which statement(s) are true?`,
    choices: [
      "II, only",
      "IV, only",
      "I and IV",
      "II and III",
    ],
    answer: 3,
    explanation: String.raw`Setting $\frac{2}{3}x - 4 = \frac{1}{4}x + 1$ gives $\frac{5}{12}x = 5$, so $x = 12$ — statement II is true. At $x = 12$, $f(12) = \frac{2}{3}(12) - 4 = 4$, so the graphs meet at $(12, 4)$ — statement III is true. Statement I fails ($f(4) = -\frac{4}{3} \ne 2 = g(4)$), and IV swaps the coordinates.`,
  },

  // ---- Linear-quadratic systems: where the line meets the parabola (AI-A.REI.7) ----
  {
    id: "sys-mc-0622-q16",
    mode: "mc",
    standard: "AI-A.REI.7",
    topic: "Systems — linear-quadratic (number of intersections)",
    examCitation: "regents-algI-0622-q16",
    part: "I",
    credits: 2,
    prompt: String.raw`A quadratic function and a linear function are graphed on the same set of axes. Which situation is *not* possible?`,
    choices: [
      "The graphs do not intersect.",
      "The graphs intersect in one point.",
      "The graphs intersect in two points.",
      "The graphs intersect in three points.",
    ],
    answer: 3,
    explanation: String.raw`Setting the line equal to the parabola gives a quadratic equation, which has at most two real solutions. So a line and a parabola can meet in $0$, $1$, or $2$ points — never $3$.`,
  },
  {
    id: "sys-mc-0118-q10",
    mode: "mc",
    standard: "AI-A.REI.7",
    topic: "Systems — linear-quadratic (intersection points)",
    examCitation: "regents-algI-0118-q10",
    part: "I",
    credits: 2,
    prompt: String.raw`The graphs of $y = x^2 - 3$ and $y = 3x - 4$ intersect at approximately`,
    choices: [
      String.raw`$(0.38, -2.85)$, only`,
      String.raw`$(2.62, 3.85)$, only`,
      String.raw`$(0.38, -2.85)$ and $(2.62, 3.85)$`,
      String.raw`$(0.38, -2.85)$ and $(3.85, 2.62)$`,
    ],
    answer: 2,
    explanation: String.raw`Set them equal: $x^2 - 3 = 3x - 4$, so $x^2 - 3x + 1 = 0$ and $x = \frac{3 \pm \sqrt{5}}{2} \approx 0.38$ or $2.62$. Using $y = 3x - 4$ gives $y \approx -2.85$ and $3.85$, so the graphs meet at both $(0.38, -2.85)$ and $(2.62, 3.85)$.`,
  },
  {
    id: "sys-mc-0123-q12",
    mode: "mc",
    standard: "AI-A.REI.7",
    topic: "Systems — linear-quadratic (where f(x) = g(x))",
    examCitation: "regents-algI-0123-q12",
    part: "I",
    credits: 2,
    prompt: String.raw`If $f(x) = x^2 + 2x + 1$ and $g(x) = 7x - 5$, for which values of $x$ is $f(x) = g(x)$?`,
    choices: [
      String.raw`$1$ and $6$`,
      String.raw`$-6$ and $-1$`,
      String.raw`$-3$ and $-2$`,
      String.raw`$2$ and $3$`,
    ],
    answer: 3,
    explanation: String.raw`Set $x^2 + 2x + 1 = 7x - 5$, so $x^2 - 5x + 6 = 0$ and $(x - 2)(x - 3) = 0$, giving $x = 2$ or $x = 3$.`,
  },
  {
    id: "sys-mc-0824-q16",
    mode: "mc",
    standard: "AI-A.REI.7",
    topic: "Systems — linear-quadratic (where f(x) = g(x))",
    examCitation: "regents-algI-0824-q16",
    part: "I",
    credits: 2,
    prompt: String.raw`The functions $f(x) = x^2 - 5x - 14$ and $g(x) = x + 2$ are graphed on the same set of axes. What are the solutions to the equation $f(x) = g(x)$?`,
    choices: [
      String.raw`$-14$ and $0$`,
      String.raw`$0$ and $2$`,
      String.raw`$-2$ and $8$`,
      String.raw`$-2$ and $7$`,
    ],
    answer: 2,
    explanation: String.raw`Set $x^2 - 5x - 14 = x + 2$, so $x^2 - 6x - 16 = 0$ and $(x - 8)(x + 2) = 0$, giving $x = 8$ or $x = -2$.`,
  },
  {
    id: "sys-mc-0825-q06",
    mode: "mc",
    standard: "AI-A.REI.7",
    topic: "Systems — linear-quadratic (where f(x) = g(x))",
    examCitation: "regents-algI-0825-q06",
    part: "I",
    credits: 2,
    prompt: String.raw`Given $f(x) = x^2$ and $g(x) = 8x - 15$ graphed on the same set of axes, which value(s) of $x$ will make $f(x) = g(x)$?`,
    choices: [
      String.raw`$3$, only`,
      String.raw`$9$, only`,
      String.raw`$3$ and $5$`,
      String.raw`$9$ and $25$`,
    ],
    answer: 2,
    explanation: String.raw`Set $x^2 = 8x - 15$, so $x^2 - 8x + 15 = 0$ and $(x - 3)(x - 5) = 0$, giving $x = 3$ or $x = 5$.`,
  },
  {
    id: "sys-mc-0119-q18",
    mode: "mc",
    standard: "AI-A.REI.7",
    topic: "Systems — verify a solution",
    examCitation: "regents-algI-0119-q18",
    part: "I",
    credits: 2,
    prompt: String.raw`Which pair of equations would have $(-1, 2)$ as a solution?`,
    choices: [
      String.raw`$y = x + 3$ and $y = 2x$`,
      String.raw`$y = x - 1$ and $y = 2x$`,
      String.raw`$y = x^2 - 3x - 2$ and $y = 4x + 6$`,
      String.raw`$2x + 3y = -4$ and $y = -\frac{1}{2}x - \frac{3}{2}$`,
    ],
    answer: 2,
    explanation: String.raw`Substitute $(-1, 2)$. In choice 3, $y = (-1)^2 - 3(-1) - 2 = 1 + 3 - 2 = 2$ and $y = 4(-1) + 6 = 2$ — both equations give $y = 2$, so $(-1, 2)$ satisfies both. The other pairs fail at least one equation.`,
  },

  // ——— Constructed-response: linear systems in context & reasoning (AI-A.REI.6) ———
  {
    id: "sys-cr-0814-q27",
    mode: "self-score",
    standard: "AI-A.REI.6",
    topic: "Systems — linear word problem (equal value)",
    examCitation: "regents-algI-0814-q27",
    part: "II",
    credits: 2,
    prompt: String.raw`Guy and Jim work at a furniture store. Guy is paid \$185 per week plus 3% of his total sales in dollars, $x$, which can be represented by $g(x) = 185 + 0.03x$. Jim is paid \$275 per week plus 2.5% of his total sales in dollars, $x$, which can be represented by $f(x) = 275 + 0.025x$. Determine the value of $x$, in dollars, that will make their weekly pay the same.`,
    answerSummary: String.raw`$x = 18{,}000$ — their pay is equal at \$18,000 in sales.`,
    modelSolution: String.raw`Set the pay functions equal: $185 + 0.03x = 275 + 0.025x$. Subtracting $0.025x$ and $185$ from both sides gives $0.005x = 90$, so $x = \dfrac{90}{0.005} = 18{,}000$. Their weekly pay is the same at \$18,000 in sales.`,
    rubric: [
      { credits: 2, criteria: "18,000, and correct work is shown." },
      { credits: 1, criteria: "Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but one conceptual error is made. OR 18,000, but no work is shown." },
      { credits: 0, criteria: String.raw`$185 + 0.03x = 275 + 0.025x$, but no further correct work is shown. OR A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure.` },
    ],
  },
  {
    id: "sys-cr-0117-q25",
    mode: "self-score",
    standard: "AI-A.REI.6",
    topic: "Systems — reasoning about the solution set",
    examCitation: "regents-algI-0117-q25",
    part: "II",
    credits: 2,
    prompt: String.raw`In attempting to solve the system of equations $y = 3x - 2$ and $6x - 2y = 4$, John graphed the two equations on his graphing calculator. Because he saw only one line, John wrote that the answer to the system is the empty set. Is he correct? Explain your answer.`,
    answerSummary: String.raw`No — the two equations are the same line, so the system has infinitely many solutions, not the empty set.`,
    modelSolution: String.raw`Rewrite $6x - 2y = 4$ in slope-intercept form: $-2y = -6x + 4$, so $y = 3x - 2$ — exactly the first equation. The two equations represent the same line, so every point on that line is a solution. John is not correct: the solution set is infinite, not empty.`,
    rubric: [
      { credits: 2, criteria: "No, and a correct explanation is written." },
      { credits: 1, criteria: "Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but one conceptual error is made. OR No, but an incomplete explanation is written." },
      { credits: 0, criteria: "No is stated, but the explanation is missing. OR A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "sys-cr-0615-q33",
    mode: "self-score",
    standard: "AI-A.REI.6",
    topic: "Systems — equivalent systems (justify)",
    examCitation: "regents-algI-0615-q33",
    part: "III",
    credits: 4,
    prompt: String.raw`Albert says that the two systems of equations shown below have the same solutions.

First System: $8x + 9y = 48$ and $12x + 5y = 21$.

Second System: $8x + 9y = 48$ and $-8.5y = -51$.

Determine and state whether you agree with Albert. Justify your answer.`,
    answerSummary: String.raw`Agree — both systems have the solution $\left(-\frac{3}{4}, 6\right)$.`,
    modelSolution: String.raw`Solve the first system by elimination. Multiply $8x + 9y = 48$ by $3$ and $12x + 5y = 21$ by $2$: $24x + 27y = 144$ and $24x + 10y = 42$. Subtracting, $17y = 102$, so $y = 6$; then $8x + 9(6) = 48$ gives $8x = -6$ and $x = -\frac{3}{4}$. In the second system, $-8.5y = -51$ gives $y = 6$, and $8x + 9(6) = 48$ again gives $x = -\frac{3}{4}$. Both systems share the solution $\left(-\frac{3}{4}, 6\right)$, so I agree with Albert.`,
    rubric: [
      { credits: 4, criteria: "Agree (or yes), and a correct justification is given." },
      { credits: 3, criteria: "Appropriate work is shown, but one computational error is made. OR Appropriate work is shown, but agree is not stated." },
      { credits: 2, criteria: "Appropriate work is shown, but two or more computational errors are made. OR Appropriate work is shown, but one conceptual error is made." },
      { credits: 1, criteria: String.raw`Appropriate work is shown, but one conceptual error and one computational error are made. OR $x = -\frac{3}{4}$ and $y = 6$, but no work is shown.` },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
  {
    id: "sys-cr-0615-q27",
    mode: "self-score",
    standard: "AI-A.REI.7",
    topic: "Systems — linear-quadratic word problem",
    examCitation: "regents-algI-0615-q27",
    part: "II",
    credits: 2,
    prompt: String.raw`John and Sarah are each saving money for a car. The total amount of money John will save is given by the function $f(x) = 60 + 5x$. The total amount of money Sarah will save is given by the function $g(x) = x^2 + 46$. After how many weeks, $x$, will they have the same amount of money saved? Explain how you arrived at your answer.`,
    answerSummary: String.raw`After $7$ weeks.`,
    modelSolution: String.raw`Set the functions equal: $60 + 5x = x^2 + 46$, so $0 = x^2 - 5x - 14$ and $(x - 7)(x + 2) = 0$, giving $x = 7$ or $x = -2$. A number of weeks cannot be negative, so they will have saved the same amount after $7$ weeks.`,
    rubric: [
      { credits: 2, criteria: "7, and a correct explanation is given." },
      { credits: 1, criteria: "Appropriate work is shown, but one computational or factoring error is made. OR Appropriate work is shown, but one conceptual error is made. OR 7, but the explanation is incomplete, incorrect, or missing." },
      { credits: 0, criteria: "A zero response is completely incorrect, irrelevant, or incoherent or is a correct response that was obtained by an obviously incorrect procedure." },
    ],
  },
];

export default bank;
